// Code generated by cmd/typegen; DO NOT EDIT.

use serde::{Deserialize, Deserializer, Serialize};
use std::collections::HashMap;

/// Deserialize null JSON values as the type's default.
/// Go serializes nil slices/maps as null, but Rust expects a sequence/map.
fn deserialize_null_default<'de, D, T>(deserializer: D) -> Result<T, D::Error>
where
    D: Deserializer<'de>,
    T: Default + Deserialize<'de>,
{
    Ok(Option::deserialize(deserializer)?.unwrap_or_default())
}

/// Status represents the entire state of the IPN network.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct Status {
    /// Version is the daemon's long version (see version.Long).
    #[serde(default)]
    pub version: String,
    /// TUN is whether /dev/net/tun (or equivalent kernel interface) is being
    /// used. If false, it's running in userspace mode.
    #[serde(rename = "TUN")]
    #[serde(default)]
    pub tun: bool,
    /// ```text
    /// BackendState is an ipn.State string value:
    ///  "NoState", "NeedsLogin", "NeedsMachineAuth", "Stopped",
    ///  "Starting", "Running".
    /// ```
    #[serde(default)]
    pub backend_state: String,
    /// HaveNodeKey is whether the current profile has a node key configured.
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub have_node_key: bool,
    /// current URL provided by control to authorize client
    #[serde(rename = "AuthURL")]
    #[serde(default)]
    pub auth_url: String,
    /// Tailscale IP(s) assigned to this node
    #[serde(rename = "TailscaleIPs")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub tailscale_ips: Vec<String>,
    #[serde(default)]
    pub self_: PeerStatus,
    /// ExitNodeStatus describes the current exit node.
    /// If nil, an exit node is not in use.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub exit_node_status: Option<ExitNodeStatus>,
    /// Health contains health check problems.
    /// Empty means everything is good. (or at least that no known
    /// problems are detected)
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub health: Vec<String>,
    /// This field is the legacy name of CurrentTailnet.MagicDNSSuffix.
    /// 
    /// Deprecated: use CurrentTailnet.MagicDNSSuffix instead.
    #[serde(rename = "MagicDNSSuffix")]
    #[serde(default)]
    pub magic_dns_suffix: String,
    /// CurrentTailnet is information about the tailnet that the node
    /// is currently connected to. When not connected, this field is nil.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub current_tailnet: Option<TailnetStatus>,
    /// CertDomains are the set of DNS names for which the control
    /// plane server will assist with provisioning TLS
    /// certificates. See SetDNSRequest for dns-01 ACME challenges
    /// for e.g. LetsEncrypt. These names are FQDNs without
    /// trailing periods, and without any "_acme-challenge." prefix.
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub cert_domains: Vec<String>,
    /// Peer is the state of each peer, keyed by each peer's current public key.
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub peer: HashMap<String, PeerStatus>,
    /// User contains profile information about UserIDs referenced by
    /// PeerStatus.UserID, PeerStatus.AltSharerUserID, etc.
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub user: HashMap<i64, UserProfile>,
    /// ClientVersion, when non-nil, contains information about the latest
    /// version of the Tailscale client that's available. Depending on
    /// the platform and client settings, it may not be available.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub client_version: Option<ClientVersion>,
}

/// PeerStatus describes a peer node and its current state.
/// WARNING: The fields in PeerStatus are merged by the AddPeer method in the StatusBuilder.
/// When adding a new field to PeerStatus, you must update AddPeer to handle merging
/// the new field. The AddPeer function is responsible for combining multiple updates
/// to the same peer, and any new field that is not merged properly may lead to
/// inconsistencies or lost data in the peer status.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct PeerStatus {
    #[serde(rename = "ID")]
    #[serde(default)]
    pub id: String,
    #[serde(default)]
    pub public_key: String,
    /// HostInfo's Hostname (not a DNS name or necessarily unique)
    #[serde(default)]
    pub host_name: String,
    /// DNSName is the Peer's FQDN. It ends with a dot.
    /// It has the form "host.<MagicDNSSuffix>."
    #[serde(rename = "DNSName")]
    #[serde(default)]
    pub dns_name: String,
    /// HostInfo.OS
    #[serde(rename = "OS")]
    #[serde(default)]
    pub os: String,
    #[serde(rename = "UserID")]
    #[serde(default)]
    pub user_id: i64,
    /// AltSharerUserID is the user who shared this node
    /// if it's different than UserID. Otherwise it's zero.
    #[serde(rename = "AltSharerUserID")]
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub alt_sharer_user_id: i64,
    /// TailscaleIPs are the IP addresses assigned to the node.
    #[serde(rename = "TailscaleIPs")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub tailscale_ips: Vec<String>,
    /// AllowedIPs are IP addresses allowed to route to this node.
    #[serde(rename = "AllowedIPs")]
    #[serde(skip_serializing_if = "Vec::is_empty")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub allowed_ips: Vec<String>,
    /// Tags are the list of ACL tags applied to this node.
    /// See tailscale.com/tailcfg#Node.Tags for more information.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub tags: Vec<String>,
    /// PrimaryRoutes are the routes this node is currently the primary
    /// subnet router for, as determined by the control plane. It does
    /// not include the IPs in TailscaleIPs.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub primary_routes: Vec<String>,
    /// Endpoints:
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub addrs: Vec<String>,
    /// one of Addrs, or unique if roaming
    #[serde(default)]
    pub cur_addr: String,
    /// DERP region
    #[serde(default)]
    pub relay: String,
    /// peer relay address (ip:port:vni)
    #[serde(default)]
    pub peer_relay: String,
    #[serde(default)]
    pub rx_bytes: i64,
    #[serde(default)]
    pub tx_bytes: i64,
    /// time registered with tailcontrol
    #[serde(default)]
    pub created: String,
    /// time last packet sent
    #[serde(default)]
    pub last_write: String,
    /// last seen to tailcontrol; only present if offline
    #[serde(default)]
    pub last_seen: String,
    /// with local wireguard
    #[serde(default)]
    pub last_handshake: String,
    /// whether node is connected to the control plane
    #[serde(default)]
    pub online: bool,
    /// true if this is the currently selected exit node.
    #[serde(default)]
    pub exit_node: bool,
    /// true if this node can be an exit node (offered && approved)
    #[serde(default)]
    pub exit_node_option: bool,
    /// Active is whether the node was recently active. The
    /// definition is somewhat undefined but has historically and
    /// currently means that there was some packet sent to this
    /// peer in the past two minutes. That definition is subject to
    /// change.
    #[serde(default)]
    pub active: bool,
    /// PeerAPIURL are the URLs of the node's PeerAPI servers.
    #[serde(rename = "PeerAPIURL")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub peer_api_url: Vec<String>,
    /// TaildropTargetStatus represents the node's eligibility to have files shared to it.
    #[serde(default)]
    pub taildrop_target: i64,
    /// Reason why this peer cannot receive files. Empty if CanReceiveFiles=true
    #[serde(default)]
    pub no_file_sharing_reason: String,
    /// ```text
    /// Capabilities are capabilities that the node has.
    /// They're free-form strings, but should be in the form of URLs/URIs
    /// such as:
    ///    "https://tailscale.com/cap/is-admin"
    ///    "https://tailscale.com/cap/file-sharing"
    ///    "funnel"
    /// 
    /// Deprecated: use CapMap instead. See https://github.com/tailscale/tailscale/issues/11508
    /// Every value is Capabilities is also a key in CapMap, even if it
    /// has no values in that map.
    /// ```
    #[serde(skip_serializing_if = "Vec::is_empty")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub capabilities: Vec<String>,
    /// CapMap is a map of capabilities to their values.
    #[serde(skip_serializing_if = "HashMap::is_empty")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub cap_map: HashMap<String, Option<Vec<serde_json::Value>>>,
    /// SSH_HostKeys are the node's SSH host keys, if known.
    #[serde(rename = "sshHostKeys")]
    #[serde(skip_serializing_if = "Vec::is_empty")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub ssh_host_keys: Vec<String>,
    /// ShareeNode indicates this node exists in the netmap because
    /// it's owned by a shared-to user and that node might connect
    /// to us. These nodes should be hidden by "tailscale status"
    /// etc by default.
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub sharee_node: bool,
    /// InNetworkMap means that this peer was seen in our latest network map.
    /// In theory, all of InNetworkMap and InMagicSock and InEngine should all be true.
    #[serde(default)]
    pub in_network_map: bool,
    /// InMagicSock means that this peer is being tracked by magicsock.
    /// In theory, all of InNetworkMap and InMagicSock and InEngine should all be true.
    #[serde(default)]
    pub in_magic_sock: bool,
    /// InEngine means that this peer is tracked by the wireguard engine.
    /// In theory, all of InNetworkMap and InMagicSock and InEngine should all be true.
    #[serde(default)]
    pub in_engine: bool,
    /// Expired means that this peer's node key has expired, based on either
    /// information from control or optimisically set on the client if the
    /// expiration time has passed.
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub expired: bool,
    /// KeyExpiry, if present, is the time at which the node key expired or
    /// will expire.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub key_expiry: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub location: Option<Location>,
}

/// TailnetStatus is information about a Tailscale network ("tailnet").
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct TailnetStatus {
    /// Name is the name of the network that's currently in use.
    #[serde(default)]
    pub name: String,
    /// MagicDNSSuffix is the network's MagicDNS suffix for nodes
    /// in the network such as "userfoo.tailscale.net".
    /// There are no surrounding dots.
    /// MagicDNSSuffix should be populated regardless of whether a domain
    /// has MagicDNS enabled.
    #[serde(rename = "MagicDNSSuffix")]
    #[serde(default)]
    pub magic_dns_suffix: String,
    /// ```text
    /// MagicDNSEnabled is whether or not the network has MagicDNS enabled.
    /// Note that the current device may still not support MagicDNS if
    /// `--accept-dns=false` was used.
    /// ```
    #[serde(rename = "MagicDNSEnabled")]
    #[serde(default)]
    pub magic_dns_enabled: bool,
}

/// ExitNodeStatus describes the current exit node.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct ExitNodeStatus {
    /// ID is the exit node's ID.
    #[serde(rename = "ID")]
    #[serde(default)]
    pub id: String,
    /// Online is whether the exit node is alive.
    #[serde(default)]
    pub online: bool,
    /// TailscaleIPs are the exit node's IP addresses assigned to the node.
    #[serde(rename = "TailscaleIPs")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub tailscale_ips: Vec<String>,
}

/// A UserProfile is display-friendly data for a [User].
/// It includes the LoginName for display purposes but *not* the Provider.
/// It also includes derived data from one of the user's logins.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct UserProfile {
    #[serde(rename = "ID")]
    #[serde(default)]
    pub id: i64,
    /// ```text
    /// "alice@smith.com"; for display purposes only (provider is not listed)
    /// ```
    #[serde(default)]
    pub login_name: String,
    /// ```text
    /// "Alice Smith"
    /// ```
    #[serde(default)]
    pub display_name: String,
    #[serde(rename = "ProfilePicURL")]
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub profile_pic_url: String,
}

/// Node is a Tailscale device in a tailnet.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct Node {
    #[serde(rename = "ID")]
    #[serde(default)]
    pub id: i64,
    #[serde(rename = "StableID")]
    #[serde(default)]
    pub stable_id: String,
    /// Name is the FQDN of the node.
    /// It is also the MagicDNS name for the node.
    /// It has a trailing dot.
    /// e.g. "host.tail-scale.ts.net."
    #[serde(default)]
    pub name: String,
    /// User is the user who created the node. If ACL tags are in use for the
    /// node then it doesn't reflect the ACL identity that the node is running
    /// as.
    #[serde(default)]
    pub user: i64,
    /// Sharer, if non-zero, is the user who shared this node, if different than User.
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub sharer: i64,
    #[serde(default)]
    pub key: String,
    /// the zero value if this node does not expire
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub key_expiry: String,
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub key_signature: String,
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub machine: String,
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub disco_key: String,
    /// Addresses are the IP addresses of this Node directly.
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub addresses: Vec<String>,
    /// AllowedIPs are the IP ranges to route to this node.
    /// 
    /// As of CapabilityVersion 112, this may be nil (null or undefined) on the wire
    /// to mean the same as Addresses. Internally, it is always filled in with
    /// its possibly-implicit value.
    #[serde(rename = "AllowedIPs")]
    #[serde(skip_serializing_if = "Vec::is_empty")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub allowed_ips: Vec<String>,
    /// IP+port (public via STUN, and local LANs)
    #[serde(skip_serializing_if = "Vec::is_empty")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub endpoints: Vec<String>,
    /// LegacyDERPString is this node's home LegacyDERPString region ID integer, but shoved into an
    /// IP:port string for legacy reasons. The IP address is always "127.3.3.40"
    /// (a loopback address (127) followed by the digits over the letters DERP on
    /// a QWERTY keyboard (3.3.40)). The "port number" is the home LegacyDERPString region ID
    /// integer.
    /// 
    /// Deprecated: HomeDERP has replaced this, but old servers might still send
    /// this field. See tailscale/tailscale#14636. Do not use this field in code
    /// other than in the upgradeNode func, which canonicalizes it to HomeDERP
    /// if it arrives as a LegacyDERPString string on the wire.
    #[serde(rename = "DERP")]
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub legacy_derp_string: String,
    /// HomeDERP is the modern version of the DERP string field, with just an
    /// integer. The client advertises support for this as of capver 111.
    /// 
    /// HomeDERP may be zero if not (yet) known, but ideally always be non-zero
    /// for magicsock connectivity to function normally.
    #[serde(rename = "HomeDERP")]
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub home_derp: i64,
    #[serde(default)]
    pub hostinfo: Hostinfo,
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub created: String,
    /// if non-zero, the node's capability version; old servers might not send
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub cap: i64,
    /// ```text
    /// Tags are the list of ACL tags applied to this node.
    /// Tags take the form of `tag:<value>` where value starts
    /// with a letter and only contains alphanumerics and dashes `-`.
    /// Some valid tag examples:
    ///   `tag:prod`
    ///   `tag:database`
    ///   `tag:lab-1`
    /// ```
    #[serde(skip_serializing_if = "Vec::is_empty")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub tags: Vec<String>,
    /// PrimaryRoutes are the routes from AllowedIPs that this node
    /// is currently the primary subnet router for, as determined
    /// by the control plane. It does not include the self address
    /// values from Addresses that are in AllowedIPs.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub primary_routes: Vec<String>,
    /// LastSeen is when the node was last online. It is not
    /// updated when Online is true. It is nil if the current
    /// node doesn't have permission to know, or the node
    /// has never been online.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub last_seen: Option<String>,
    /// Online is whether the node is currently connected to the
    /// coordination server.  A value of nil means unknown, or the
    /// current node doesn't have permission to know.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub online: Option<bool>,
    /// TODO(crawshaw): replace with MachineStatus
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub machine_authorized: bool,
    /// ```text
    /// Capabilities are capabilities that the node has.
    /// They're free-form strings, but should be in the form of URLs/URIs
    /// such as:
    ///    "https://tailscale.com/cap/is-admin"
    ///    "https://tailscale.com/cap/file-sharing"
    /// 
    /// Deprecated: use CapMap instead. See https://github.com/tailscale/tailscale/issues/11508
    /// ```
    #[serde(skip_serializing_if = "Vec::is_empty")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub capabilities: Vec<String>,
    /// CapMap is a map of capabilities to their optional argument/data values.
    /// 
    /// It is valid for a capability to not have any argument/data values; such
    /// capabilities can be tested for using the HasCap method. These type of
    /// capabilities are used to indicate that a node has a capability, but there
    /// is no additional data associated with it. These were previously
    /// represented by the Capabilities field, but can now be represented by
    /// CapMap with an empty value.
    /// 
    /// See NodeCapability for more information on keys.
    /// 
    /// Metadata about nodes can be transmitted in 3 ways:
    /// 1. MapResponse.Node.CapMap describes attributes that affect behavior for
    ///    this node, such as which features have been enabled through the admin
    ///    panel and any associated configuration details.
    /// 2. MapResponse.PacketFilter(s) describes access (both IP and application
    ///    based) that should be granted to peers.
    /// 3. MapResponse.Peers[].CapMap describes attributes regarding a peer node,
    ///    such as which features the peer supports or if that peer is preferred
    ///    for a particular task vs other peers that could also be chosen.
    #[serde(skip_serializing_if = "HashMap::is_empty")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub cap_map: HashMap<String, Option<Vec<serde_json::Value>>>,
    /// UnsignedPeerAPIOnly means that this node is not signed nor subject to TKA
    /// restrictions. However, in exchange for that privilege, it does not get
    /// network access. It can only access this node's peerapi, which may not let
    /// it do anything. It is the tailscaled client's job to double-check the
    /// MapResponse's PacketFilter to verify that its AllowedIPs will not be
    /// accepted by the packet filter.
    #[serde(rename = "UnsignedPeerAPIOnly")]
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub unsigned_peer_api_only: bool,
    /// MagicDNS base name (for normal non-shared-in nodes), FQDN (without trailing dot, for shared-in nodes), or Hostname (if no MagicDNS)
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub computed_name: String,
    /// either "ComputedName" or "ComputedName (computedHostIfDifferent)", if computedHostIfDifferent is set
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub computed_name_with_host: String,
    /// DataPlaneAuditLogID is the per-node logtail ID used for data plane audit logging.
    #[serde(rename = "DataPlaneAuditLogID")]
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub data_plane_audit_log_id: String,
    /// Expired is whether this node's key has expired. Control may send
    /// this; clients are only allowed to set this from false to true. On
    /// the client, this is calculated client-side based on a timestamp sent
    /// from control, to avoid clock skew issues.
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub expired: bool,
    /// SelfNodeV4MasqAddrForThisPeer is the IPv4 that this peer knows the current node as.
    /// It may be empty if the peer knows the current node by its native
    /// IPv4 address.
    /// This field is only populated in a MapResponse for peers and not
    /// for the current node.
    /// 
    /// If set, it should be used to masquerade traffic originating from the
    /// current node to this peer. The masquerade address is only relevant
    /// for this peer and not for other peers.
    /// 
    /// This only applies to traffic originating from the current node to the
    /// peer or any of its subnets. Traffic originating from subnet routes will
    /// not be masqueraded (e.g. in case of --snat-subnet-routes).
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub self_node_v4_masq_addr_for_this_peer: Option<String>,
    /// SelfNodeV6MasqAddrForThisPeer is the IPv6 that this peer knows the current node as.
    /// It may be empty if the peer knows the current node by its native
    /// IPv6 address.
    /// This field is only populated in a MapResponse for peers and not
    /// for the current node.
    /// 
    /// If set, it should be used to masquerade traffic originating from the
    /// current node to this peer. The masquerade address is only relevant
    /// for this peer and not for other peers.
    /// 
    /// This only applies to traffic originating from the current node to the
    /// peer or any of its subnets. Traffic originating from subnet routes will
    /// not be masqueraded (e.g. in case of --snat-subnet-routes).
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub self_node_v6_masq_addr_for_this_peer: Option<String>,
    /// IsWireGuardOnly indicates that this is a non-Tailscale WireGuard peer, it
    /// is not expected to speak Disco or DERP, and it must have Endpoints in
    /// order to be reachable.
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub is_wire_guard_only: bool,
    /// IsJailed indicates that this node is jailed and should not be allowed
    /// initiate connections, however outbound connections to it should still be
    /// allowed.
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub is_jailed: bool,
    /// ExitNodeDNSResolvers is the list of DNS servers that should be used when this
    /// node is marked IsWireGuardOnly and being used as an exit node.
    #[serde(rename = "ExitNodeDNSResolvers")]
    #[serde(skip_serializing_if = "Vec::is_empty")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub exit_node_dns_resolvers: Vec<Resolver>,
}

/// Hostinfo contains a summary of a Tailscale host.
/// 
/// Because it contains pointers (slices), this type should not be used
/// as a value type.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct Hostinfo {
    /// version of this code (in version.Long format)
    #[serde(rename = "IPNVersion")]
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub ipn_version: String,
    /// logtail ID of frontend instance
    #[serde(rename = "FrontendLogID")]
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub frontend_log_id: String,
    /// logtail ID of backend instance
    #[serde(rename = "BackendLogID")]
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub backend_log_id: String,
    /// operating system the client runs on (a version.OS value)
    #[serde(rename = "OS")]
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub os: String,
    /// ```text
    /// OSVersion is the version of the OS, if available.
    /// 
    /// For Android, it's like "10", "11", "12", etc. For iOS and macOS it's like
    /// "15.6.1" or "12.4.0". For Windows it's like "10.0.19044.1889". For
    /// FreeBSD it's like "12.3-STABLE".
    /// 
    /// For Linux, prior to Tailscale 1.32, we jammed a bunch of fields into this
    /// string on Linux, like "Debian 10.4; kernel=xxx; container; env=kn" and so
    /// on. As of Tailscale 1.32, this is simply the kernel version on Linux, like
    /// "5.10.0-17-amd64".
    /// ```
    #[serde(rename = "OSVersion")]
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub os_version: String,
    /// best-effort whether the client is running in a container
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub container: Option<bool>,
    /// a hostinfo.EnvType in string form
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub env: String,
    /// ```text
    /// "debian", "ubuntu", "nixos", ...
    /// ```
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub distro: String,
    /// ```text
    /// "20.04", ...
    /// ```
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub distro_version: String,
    /// ```text
    /// "jammy", "bullseye", ...
    /// ```
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub distro_code_name: String,
    /// App is used to disambiguate Tailscale clients that run using tsnet.
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub app: String,
    /// if a desktop was detected on Linux
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub desktop: Option<bool>,
    /// Tailscale package to disambiguate ("choco", "appstore", etc; "" for unknown)
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub package: String,
    /// mobile phone model ("Pixel 3a", "iPhone12,3")
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub device_model: String,
    /// macOS/iOS APNs device token for notifications (and Android in the future)
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub push_device_token: String,
    /// name of the host the client runs on
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub hostname: String,
    /// indicates whether the host is blocking incoming connections
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub shields_up: bool,
    /// indicates this node exists in netmap because it's owned by a shared-to user
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub sharee_node: bool,
    /// indicates that the user has opted out of sending logs and support
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub no_logs_no_support: bool,
    /// WireIngress indicates that the node would like to be wired up server-side
    /// (DNS, etc) to be able to use Tailscale Funnel, even if it's not currently
    /// enabled. For example, the user might only use it for intermittent
    /// foreground CLI serve sessions, for which they'd like it to work right
    /// away, even if it's disabled most of the time. As an optimization, this is
    /// only sent if IngressEnabled is false, as IngressEnabled implies that this
    /// option is true.
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub wire_ingress: bool,
    /// if the node has any funnel endpoint enabled
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub ingress_enabled: bool,
    /// indicates that the node has opted-in to admin-console-drive remote updates
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub allows_update: bool,
    /// the current host's machine type (uname -m)
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub machine: String,
    /// GOARCH value (of the built binary)
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub go_arch: String,
    /// GOARM, GOAMD64, etc (of the built binary)
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub go_arch_var: String,
    /// Go version binary was built with
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub go_version: String,
    /// set of IP ranges this client can route
    #[serde(rename = "RoutableIPs")]
    #[serde(skip_serializing_if = "Vec::is_empty")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub routable_ips: Vec<String>,
    /// set of ACL tags this node wants to claim
    #[serde(skip_serializing_if = "Vec::is_empty")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub request_tags: Vec<String>,
    /// MAC address(es) to send Wake-on-LAN packets to wake this node (lowercase hex w/ colons)
    #[serde(rename = "WoLMACs")]
    #[serde(skip_serializing_if = "Vec::is_empty")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub wol_macs: Vec<String>,
    /// services advertised by this machine
    #[serde(skip_serializing_if = "Vec::is_empty")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub services: Vec<Service>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub net_info: Option<NetInfo>,
    /// if advertised
    #[serde(rename = "sshHostKeys")]
    #[serde(skip_serializing_if = "Vec::is_empty")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub ssh_host_keys: Vec<String>,
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub cloud: String,
    /// if the client is running in userspace (netstack) mode
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub userspace: Option<bool>,
    /// if the client's subnet router is running in userspace (netstack) mode
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub userspace_router: Option<bool>,
    /// if the client is running the app-connector service
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub app_connector: Option<bool>,
    /// opaque hash of the most recent list of tailnet services, change in hash indicates config should be fetched via c2n
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub services_hash: String,
    /// the client’s selected exit node, empty when unselected.
    #[serde(rename = "ExitNodeID")]
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub exit_node_id: String,
    /// Location represents geographical location data about a
    /// Tailscale host. Location is optional and only set if
    /// explicitly declared by a node.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub location: Option<Location>,
    /// TPM device metadata, if available
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub t_p_m: Option<TPMInfo>,
    /// ```text
    /// StateEncrypted reports whether the node state is stored encrypted on
    /// disk. The actual mechanism is platform-specific:
    ///   * Apple nodes use the Keychain
    ///   * Linux and Windows nodes use the TPM
    ///   * Android apps use EncryptedSharedPreferences
    /// ```
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub state_encrypted: Option<bool>,
}

/// NetInfo contains information about the host's network state.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct NetInfo {
    /// MappingVariesByDestIP says whether the host's NAT mappings
    /// vary based on the destination IP.
    #[serde(rename = "MappingVariesByDestIP")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub mapping_varies_by_dest_ip: Option<bool>,
    /// WorkingIPv6 is whether the host has IPv6 internet connectivity.
    #[serde(rename = "WorkingIPv6")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub working_ipv6: Option<bool>,
    /// OSHasIPv6 is whether the OS supports IPv6 at all, regardless of
    /// whether IPv6 internet connectivity is available.
    #[serde(rename = "OSHasIPv6")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub os_has_ipv6: Option<bool>,
    /// WorkingUDP is whether the host has UDP internet connectivity.
    #[serde(rename = "WorkingUDP")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub working_udp: Option<bool>,
    /// WorkingICMPv4 is whether ICMPv4 works.
    /// Empty means not checked.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub working_i_c_m_pv4: Option<bool>,
    /// HavePortMap is whether we have an existing portmap open
    /// (UPnP, PMP, or PCP).
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub have_port_map: bool,
    /// UPnP is whether UPnP appears present on the LAN.
    /// Empty means not checked.
    #[serde(rename = "UPnP")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub upnp: Option<bool>,
    /// PMP is whether NAT-PMP appears present on the LAN.
    /// Empty means not checked.
    #[serde(rename = "PMP")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub pmp: Option<bool>,
    /// PCP is whether PCP appears present on the LAN.
    /// Empty means not checked.
    #[serde(rename = "PCP")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub pcp: Option<bool>,
    /// PreferredDERP is this node's preferred (home) DERP region ID.
    /// This is where the node expects to be contacted to begin a
    /// peer-to-peer connection. The node might be be temporarily
    /// connected to multiple DERP servers (to speak to other nodes
    /// that are located elsewhere) but PreferredDERP is the region ID
    /// that the node subscribes to traffic at.
    /// Zero means disconnected or unknown.
    #[serde(rename = "PreferredDERP")]
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub preferred_derp: i64,
    /// LinkType is the current link type, if known.
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub link_type: String,
    /// ```text
    /// DERPLatency is the fastest recent time to reach various
    /// DERP STUN servers, in seconds. The map key is the
    /// "regionID-v4" or "-v6"; it was previously the DERP server's
    /// STUN host:port.
    /// 
    /// This should only be updated rarely, or when there's a
    /// material change, as any change here also gets uploaded to
    /// the control plane.
    /// ```
    #[serde(rename = "DERPLatency")]
    #[serde(skip_serializing_if = "HashMap::is_empty")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub derp_latency: HashMap<String, f64>,
    /// ```text
    /// FirewallMode encodes both which firewall mode was selected and why.
    /// It is Linux-specific (at least as of 2023-08-19) and is meant to help
    /// debug iptables-vs-nftables issues. The string is of the form
    /// "{nft,ift}-REASON", like "nft-forced" or "ipt-default". Empty means
    /// either not Linux or a configuration in which the host firewall rules
    /// are not managed by tailscaled.
    /// ```
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub firewall_mode: String,
}

/// Service represents a service running on a node.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct Service {
    /// ```text
    /// Proto is the type of service. It's usually the constant TCP
    /// or UDP ("tcp" or "udp"), but it can also be one of the
    /// following meta service values:
    /// 
    ///     * "peerapi4": peerapi is available on IPv4; Port is the
    ///        port number that the peerapi is running on the
    ///        node's Tailscale IPv4 address.
    ///     * "peerapi6": peerapi is available on IPv6; Port is the
    ///        port number that the peerapi is running on the
    ///        node's Tailscale IPv6 address.
    ///     * "peerapi-dns-proxy": the local peerapi service supports
    ///        being a DNS proxy (when the node is an exit
    ///        node). For this service, the Port number must only be 1.
    /// ```
    #[serde(default)]
    pub proto: String,
    /// Port is the port number.
    /// 
    /// For Proto "peerapi-dns", it must be 1.
    #[serde(default)]
    pub port: u16,
    /// Description is the textual description of the service,
    /// usually the process name that's running.
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub description: String,
}

/// Location represents geographical location data about a
/// Tailscale host. Location is optional and only set if
/// explicitly declared by a node.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct Location {
    /// User friendly country name, with proper capitalization ("Canada")
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub country: String,
    /// ISO 3166-1 alpha-2 in upper case ("CA")
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub country_code: String,
    /// User friendly city name, with proper capitalization ("Squamish")
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub city: String,
    /// CityCode is a short code representing the city in upper case.
    /// CityCode is used to disambiguate a city from another location
    /// with the same city name. It uniquely identifies a particular
    /// geographical location, within the tailnet.
    /// IATA, ICAO or ISO 3166-2 codes are recommended ("YSE")
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub city_code: String,
    /// Latitude, Longitude are optional geographical coordinates of the node, in degrees.
    /// No particular accuracy level is promised; the coordinates may simply be the center of the city or country.
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub latitude: f64,
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub longitude: f64,
    /// Priority determines the order of use of an exit node when a
    /// location based preference matches more than one exit node,
    /// the node with the highest priority wins. Nodes of equal
    /// probability may be selected arbitrarily.
    /// 
    /// A value of 0 means the exit node does not have a priority
    /// preference. A negative int is not allowed.
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub priority: i64,
}

/// TPMInfo contains information about a TPM 2.0 device present on a node.
/// All fields are read from TPM_CAP_TPM_PROPERTIES, see Part 2, section 6.13 of
/// https://trustedcomputinggroup.org/resource/tpm-library-specification/.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct TPMInfo {
    /// Manufacturer is a 4-letter code from section 4.1 of
    /// https://trustedcomputinggroup.org/resource/vendor-id-registry/,
    /// for example "MSFT" for Microsoft.
    /// Read from TPM_PT_MANUFACTURER.
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub manufacturer: String,
    /// Vendor is a vendor ID string, up to 16 characters.
    /// Read from TPM_PT_VENDOR_STRING_*.
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub vendor: String,
    /// Model is a vendor-defined TPM model.
    /// Read from TPM_PT_VENDOR_TPM_TYPE.
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub model: i64,
    /// FirmwareVersion is the version number of the firmware.
    /// Read from TPM_PT_FIRMWARE_VERSION_*.
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub firmware_version: u64,
    /// SpecRevision is the TPM 2.0 spec revision encoded as a single number. All
    /// revisions can be found at
    /// https://trustedcomputinggroup.org/resource/tpm-library-specification/.
    /// Before revision 184, TCG used the "01.83" format for revision 183.
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub spec_revision: i64,
    /// FamilyIndicator is the TPM spec family, like "2.0".
    /// Read from TPM_PT_FAMILY_INDICATOR.
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub family_indicator: String,
}

/// ClientVersion is information about the latest client version that's available
/// for the client (and whether they're already running it).
/// 
/// It does not include a URL to download the client, as that varies by platform.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct ClientVersion {
    /// RunningLatest is true if the client is running the latest build.
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub running_latest: bool,
    /// LatestVersion is the latest version.Short ("1.34.2") version available
    /// for download for the client's platform and packaging type.
    /// It won't be populated if RunningLatest is true.
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub latest_version: String,
    /// UrgentSecurityUpdate is set when the client is missing an important
    /// security update. That update may be in LatestVersion or earlier.
    /// UrgentSecurityUpdate should not be set if RunningLatest is false.
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub urgent_security_update: bool,
    /// Notify is whether the client should do an OS-specific notification about
    /// a new version being available. This should not be populated if
    /// RunningLatest is true. The client should not notify multiple times for
    /// the same LatestVersion value.
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub notify: bool,
    /// NotifyURL is a URL to open in the browser when the user clicks on the
    /// notification, when Notify is true.
    #[serde(rename = "NotifyURL")]
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub notify_url: String,
    /// NotifyText is the text to show in the notification, when Notify is true.
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub notify_text: String,
}

/// ServeConfig is the JSON type stored in the StateStore for
/// StateKey "_serve/$PROFILE_ID" as returned by ServeConfigKey.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct ServeConfig {
    /// TCP are the list of TCP port numbers that tailscaled should handle for
    /// the Tailscale IP addresses. (not subnet routers, etc)
    #[serde(rename = "TCP")]
    #[serde(skip_serializing_if = "HashMap::is_empty")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub tcp: HashMap<u16, TCPPortHandler>,
    /// Web maps from "$SNI_NAME:$PORT" to a set of HTTP handlers
    /// keyed by mount point ("/", "/foo", etc)
    #[serde(skip_serializing_if = "HashMap::is_empty")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub web: HashMap<String, WebServerConfig>,
    /// Services maps from service name (in the form "svc:dns-label") to a ServiceConfig.
    /// Which describes the L3, L4, and L7 forwarding information for the service.
    #[serde(skip_serializing_if = "HashMap::is_empty")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub services: HashMap<String, ServiceConfig>,
    /// AllowFunnel is the set of SNI:port values for which funnel
    /// traffic is allowed, from trusted ingress peers.
    #[serde(skip_serializing_if = "HashMap::is_empty")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub allow_funnel: HashMap<String, bool>,
    /// Foreground is a map of an IPN Bus session ID to an alternate foreground serve config that's valid for the
    /// life of that WatchIPNBus session ID. This allows the config to specify ephemeral configs that are used
    /// in the CLI's foreground mode to ensure ungraceful shutdowns of either the client or the LocalBackend does not
    /// expose ports that users are not aware of. In practice this contains any serve config set via 'tailscale
    /// serve' command run without the '--bg' flag. ServeConfig contained by Foreground is not expected itself to contain
    /// another Foreground block.
    #[serde(skip_serializing_if = "HashMap::is_empty")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub foreground: HashMap<String, ServeConfig>,
    /// ETag is the checksum of the serve config that's populated
    /// by the LocalClient through the HTTP ETag header during a
    /// GetServeConfig request and is translated to an If-Match header
    /// during a SetServeConfig request.
    #[serde(skip)]
    pub e_tag: String,
}

/// TCPPortHandler describes what to do when handling a TCP
/// connection.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct TCPPortHandler {
    /// HTTPS, if true, means that tailscaled should handle this connection as an
    /// HTTPS request as configured by ServeConfig.Web.
    /// 
    /// It is mutually exclusive with TCPForward.
    #[serde(rename = "HTTPS")]
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub https: bool,
    /// HTTP, if true, means that tailscaled should handle this connection as an
    /// HTTP request as configured by ServeConfig.Web.
    /// 
    /// It is mutually exclusive with TCPForward.
    #[serde(rename = "HTTP")]
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub http: bool,
    /// TCPForward is the IP:port to forward TCP connections to.
    /// Whether or not TLS is terminated by tailscaled depends on
    /// TerminateTLS.
    /// 
    /// It is mutually exclusive with HTTPS.
    #[serde(rename = "TCPForward")]
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub tcp_forward: String,
    /// TerminateTLS, if non-empty, means that tailscaled should terminate the
    /// TLS connections before forwarding them to TCPForward, permitting only the
    /// SNI name with this value. It is only used if TCPForward is non-empty.
    /// (the HTTPS mode uses ServeConfig.Web)
    #[serde(rename = "TerminateTLS")]
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub terminate_tls: String,
    /// ProxyProtocol indicates whether to send a PROXY protocol header
    /// before forwarding the connection to TCPForward.
    /// 
    /// This is only valid if TCPForward is non-empty.
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub proxy_protocol: i64,
}

/// WebServerConfig describes a web server's configuration.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct WebServerConfig {
    /// mountPoint => handler
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub handlers: HashMap<String, HTTPHandler>,
}

/// HTTPHandler is either a path or a proxy to serve.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct HTTPHandler {
    /// absolute path to directory or file to serve
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub path: String,
    /// http://localhost:3000/, localhost:3030, 3030
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub proxy: String,
    /// plaintext to serve (primarily for testing)
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub text: String,
    /// peer capabilities to forward in grant header, e.g. example.com/cap/mon
    #[serde(skip_serializing_if = "Vec::is_empty")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub accept_app_caps: Vec<String>,
    /// Redirect, if not empty, is the target URL to redirect requests to.
    /// By default, we redirect with HTTP 302 (Found) status.
    /// If Redirect starts with '<httpcode>:', then we use that status instead.
    /// 
    /// The target URL supports the following expansion variables:
    ///   - ${HOST}: replaced with the request's Host header value
    ///   - ${REQUEST_URI}: replaced with the request's full URI (path and query string)
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub redirect: String,
}

/// ServiceConfig contains the config information for a single service.
/// it contains a bool to indicate if the service is in Tun mode (L3 forwarding).
/// If the service is not in Tun mode, the service is configured by the L4 forwarding
/// (TCP ports) and/or the L7 forwarding (http handlers) information.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct ServiceConfig {
    /// TCP are the list of TCP port numbers that tailscaled should handle for
    /// the Tailscale IP addresses. (not subnet routers, etc)
    #[serde(rename = "TCP")]
    #[serde(skip_serializing_if = "HashMap::is_empty")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub tcp: HashMap<u16, TCPPortHandler>,
    /// Web maps from "$SNI_NAME:$PORT" to a set of HTTP handlers
    /// keyed by mount point ("/", "/foo", etc)
    #[serde(skip_serializing_if = "HashMap::is_empty")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub web: HashMap<String, WebServerConfig>,
    /// Tun determines if the service should be using L3 forwarding (Tun mode).
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub tun: bool,
}

/// WhoIsResponse is the JSON type returned by tailscaled debug server's /whois?ip=$IP handler.
/// In successful whois responses, Node and UserProfile are never nil.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct WhoIsResponse {
    #[serde(default)]
    pub node: Node,
    #[serde(default)]
    pub user_profile: UserProfile,
    /// CapMap is a map of capabilities to their values.
    /// See tailcfg.PeerCapMap and tailcfg.PeerCapability for details.
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub cap_map: HashMap<String, Option<Vec<serde_json::Value>>>,
}

/// Resolver is the configuration for one DNS resolver.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct Resolver {
    /// Addr is the address of the DNS resolver, one of:
    ///  - A plain IP address for a "classic" UDP+TCP DNS resolver.
    ///    This is the common format as sent by the control plane.
    ///  - An IP:port, for tests.
    ///  - "https://resolver.com/path" for DNS over HTTPS; currently
    ///    as of 2022-09-08 only used for certain well-known resolvers
    ///    (see the publicdns package) for which the IP addresses to dial DoH are
    ///    known ahead of time, so bootstrap DNS resolution is not required.
    ///  - "http://node-address:port/path" for DNS over HTTP over WireGuard. This
    ///    is implemented in the PeerAPI for exit nodes and app connectors.
    ///  - [TODO] "tls://resolver.com" for DNS over TCP+TLS
    #[serde(skip_serializing_if = "String::is_empty")]
    #[serde(default)]
    pub addr: String,
    /// BootstrapResolution is an optional suggested resolution for the
    /// DoT/DoH resolver, if the resolver URL does not reference an IP
    /// address directly.
    /// BootstrapResolution may be empty, in which case clients should
    /// look up the DoT/DoH server using their local "classic" DNS
    /// resolver.
    /// 
    /// As of 2022-09-08, BootstrapResolution is not yet used.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub bootstrap_resolution: Vec<String>,
    /// UseWithExitNode designates that this resolver should continue to be used when an
    /// exit node is in use. Normally, DNS resolution is delegated to the exit node but
    /// there are situations where it is preferable to still use a Split DNS server and/or
    /// global DNS server instead of the exit node.
    #[serde(skip_serializing_if = "is_default")]
    #[serde(default)]
    pub use_with_exit_node: bool,
}

fn is_default<T: Default + PartialEq>(v: &T) -> bool {
    *v == T::default()
}
