# Code generated by cmd/typegen; DO NOT EDIT.

from __future__ import annotations

from typing import Any

import msgspec


class Status(msgspec.Struct, rename="pascal", omit_defaults=True):
    "Status represents the entire state of the IPN network."

    # Version is the daemon's long version (see version.Long).
    version: str = ""
    # TUN is whether /dev/net/tun (or equivalent kernel interface) is being
    # used. If false, it's running in userspace mode.
    tun: bool = msgspec.field(default=False, name="TUN")
    # BackendState is an ipn.State string value:
    #  "NoState", "NeedsLogin", "NeedsMachineAuth", "Stopped",
    #  "Starting", "Running".
    backend_state: str = ""
    # HaveNodeKey is whether the current profile has a node key configured.
    have_node_key: bool = False
    # current URL provided by control to authorize client
    auth_url: str = msgspec.field(default="", name="AuthURL")
    # Tailscale IP(s) assigned to this node
    tailscale_ips: list[str] = msgspec.field(default_factory=list, name="TailscaleIPs")
    self_: PeerStatus = msgspec.field(default_factory=lambda: PeerStatus())
    # ExitNodeStatus describes the current exit node.
    # If nil, an exit node is not in use.
    exit_node_status: ExitNodeStatus | None = None
    # Health contains health check problems.
    # Empty means everything is good. (or at least that no known
    # problems are detected)
    health: list[str] = []
    # This field is the legacy name of CurrentTailnet.MagicDNSSuffix.
    # 
    # Deprecated: use CurrentTailnet.MagicDNSSuffix instead.
    magic_dns_suffix: str = msgspec.field(default="", name="MagicDNSSuffix")
    # CurrentTailnet is information about the tailnet that the node
    # is currently connected to. When not connected, this field is nil.
    current_tailnet: TailnetStatus | None = None
    # CertDomains are the set of DNS names for which the control
    # plane server will assist with provisioning TLS
    # certificates. See SetDNSRequest for dns-01 ACME challenges
    # for e.g. LetsEncrypt. These names are FQDNs without
    # trailing periods, and without any "_acme-challenge." prefix.
    cert_domains: list[str] = []
    # Peer is the state of each peer, keyed by each peer's current public key.
    peer: dict[str, PeerStatus] = {}
    # User contains profile information about UserIDs referenced by
    # PeerStatus.UserID, PeerStatus.AltSharerUserID, etc.
    user: dict[str, UserProfile] = {}
    # ClientVersion, when non-nil, contains information about the latest
    # version of the Tailscale client that's available. Depending on
    # the platform and client settings, it may not be available.
    client_version: ClientVersion | None = None


class PeerStatus(msgspec.Struct, rename="pascal", omit_defaults=True):
    "PeerStatus describes a peer node and its current state.\nWARNING: The fields in PeerStatus are merged by the AddPeer method in the StatusBuilder.\nWhen adding a new field to PeerStatus, you must update AddPeer to handle merging\nthe new field. The AddPeer function is responsible for combining multiple updates\nto the same peer, and any new field that is not merged properly may lead to\ninconsistencies or lost data in the peer status."

    id: str = msgspec.field(default="", name="ID")
    public_key: str = ""
    # HostInfo's Hostname (not a DNS name or necessarily unique)
    host_name: str = ""
    # DNSName is the Peer's FQDN. It ends with a dot.
    # It has the form "host.<MagicDNSSuffix>."
    dns_name: str = msgspec.field(default="", name="DNSName")
    # HostInfo.OS
    os: str = msgspec.field(default="", name="OS")
    user_id: int = msgspec.field(default=0, name="UserID")
    # AltSharerUserID is the user who shared this node
    # if it's different than UserID. Otherwise it's zero.
    alt_sharer_user_id: int = msgspec.field(default=0, name="AltSharerUserID")
    # TailscaleIPs are the IP addresses assigned to the node.
    tailscale_ips: list[str] = msgspec.field(default_factory=list, name="TailscaleIPs")
    # AllowedIPs are IP addresses allowed to route to this node.
    allowed_ips: list[str] | None = msgspec.field(default=None, name="AllowedIPs")
    # Tags are the list of ACL tags applied to this node.
    # See tailscale.com/tailcfg#Node.Tags for more information.
    tags: list[str] | None = None
    # PrimaryRoutes are the routes this node is currently the primary
    # subnet router for, as determined by the control plane. It does
    # not include the IPs in TailscaleIPs.
    primary_routes: list[str] | None = None
    # Endpoints:
    addrs: list[str] = []
    # one of Addrs, or unique if roaming
    cur_addr: str = ""
    # DERP region
    relay: str = ""
    # peer relay address (ip:port:vni)
    peer_relay: str = ""
    rx_bytes: int = 0
    tx_bytes: int = 0
    # time registered with tailcontrol
    created: str = ""
    # time last packet sent
    last_write: str = ""
    # last seen to tailcontrol; only present if offline
    last_seen: str = ""
    # with local wireguard
    last_handshake: str = ""
    # whether node is connected to the control plane
    online: bool = False
    # true if this is the currently selected exit node.
    exit_node: bool = False
    # true if this node can be an exit node (offered && approved)
    exit_node_option: bool = False
    # Active is whether the node was recently active. The
    # definition is somewhat undefined but has historically and
    # currently means that there was some packet sent to this
    # peer in the past two minutes. That definition is subject to
    # change.
    active: bool = False
    # PeerAPIURL are the URLs of the node's PeerAPI servers.
    peer_api_url: list[str] = msgspec.field(default_factory=list, name="PeerAPIURL")
    # TaildropTargetStatus represents the node's eligibility to have files shared to it.
    taildrop_target: int = 0
    # Reason why this peer cannot receive files. Empty if CanReceiveFiles=true
    no_file_sharing_reason: str = ""
    # Capabilities are capabilities that the node has.
    # They're free-form strings, but should be in the form of URLs/URIs
    # such as:
    #    "https://tailscale.com/cap/is-admin"
    #    "https://tailscale.com/cap/file-sharing"
    #    "funnel"
    # 
    # Deprecated: use CapMap instead. See https://github.com/tailscale/tailscale/issues/11508
    # Every value is Capabilities is also a key in CapMap, even if it
    # has no values in that map.
    capabilities: list[str] = []
    # CapMap is a map of capabilities to their values.
    cap_map: dict[str, list[Any] | None] = {}
    # SSH_HostKeys are the node's SSH host keys, if known.
    ssh_host_keys: list[str] = msgspec.field(default_factory=list, name="sshHostKeys")
    # ShareeNode indicates this node exists in the netmap because
    # it's owned by a shared-to user and that node might connect
    # to us. These nodes should be hidden by "tailscale status"
    # etc by default.
    sharee_node: bool = False
    # InNetworkMap means that this peer was seen in our latest network map.
    # In theory, all of InNetworkMap and InMagicSock and InEngine should all be true.
    in_network_map: bool = False
    # InMagicSock means that this peer is being tracked by magicsock.
    # In theory, all of InNetworkMap and InMagicSock and InEngine should all be true.
    in_magic_sock: bool = False
    # InEngine means that this peer is tracked by the wireguard engine.
    # In theory, all of InNetworkMap and InMagicSock and InEngine should all be true.
    in_engine: bool = False
    # Expired means that this peer's node key has expired, based on either
    # information from control or optimisically set on the client if the
    # expiration time has passed.
    expired: bool = False
    # KeyExpiry, if present, is the time at which the node key expired or
    # will expire.
    key_expiry: str | None = None
    location: Location | None = None


class TailnetStatus(msgspec.Struct, rename="pascal"):
    "TailnetStatus is information about a Tailscale network (\"tailnet\")."

    # Name is the name of the network that's currently in use.
    name: str = ""
    # MagicDNSSuffix is the network's MagicDNS suffix for nodes
    # in the network such as "userfoo.tailscale.net".
    # There are no surrounding dots.
    # MagicDNSSuffix should be populated regardless of whether a domain
    # has MagicDNS enabled.
    magic_dns_suffix: str = msgspec.field(default="", name="MagicDNSSuffix")
    # MagicDNSEnabled is whether or not the network has MagicDNS enabled.
    # Note that the current device may still not support MagicDNS if
    # `--accept-dns=false` was used.
    magic_dns_enabled: bool = msgspec.field(default=False, name="MagicDNSEnabled")


class ExitNodeStatus(msgspec.Struct, rename="pascal"):
    "ExitNodeStatus describes the current exit node."

    # ID is the exit node's ID.
    id: str = msgspec.field(default="", name="ID")
    # Online is whether the exit node is alive.
    online: bool = False
    # TailscaleIPs are the exit node's IP addresses assigned to the node.
    tailscale_ips: list[str] = msgspec.field(default_factory=list, name="TailscaleIPs")


class UserProfile(msgspec.Struct, rename="pascal", omit_defaults=True):
    "A UserProfile is display-friendly data for a [User].\nIt includes the LoginName for display purposes but *not* the Provider.\nIt also includes derived data from one of the user's logins."

    id: int = msgspec.field(default=0, name="ID")
    # "alice@smith.com"; for display purposes only (provider is not listed)
    login_name: str = ""
    # "Alice Smith"
    display_name: str = ""
    profile_pic_url: str = msgspec.field(default="", name="ProfilePicURL")


class Node(msgspec.Struct, rename="pascal", omit_defaults=True):
    "Node is a Tailscale device in a tailnet."

    id: int = msgspec.field(default=0, name="ID")
    stable_id: str = msgspec.field(default="", name="StableID")
    # Name is the FQDN of the node.
    # It is also the MagicDNS name for the node.
    # It has a trailing dot.
    # e.g. "host.tail-scale.ts.net."
    name: str = ""
    # User is the user who created the node. If ACL tags are in use for the
    # node then it doesn't reflect the ACL identity that the node is running
    # as.
    user: int = 0
    # Sharer, if non-zero, is the user who shared this node, if different than User.
    sharer: int = 0
    key: str = ""
    # the zero value if this node does not expire
    key_expiry: str = ""
    key_signature: str = ""
    machine: str = ""
    disco_key: str = ""
    # Addresses are the IP addresses of this Node directly.
    addresses: list[str] = []
    # AllowedIPs are the IP ranges to route to this node.
    # 
    # As of CapabilityVersion 112, this may be nil (null or undefined) on the wire
    # to mean the same as Addresses. Internally, it is always filled in with
    # its possibly-implicit value.
    allowed_ips: list[str] = msgspec.field(default_factory=list, name="AllowedIPs")
    # IP+port (public via STUN, and local LANs)
    endpoints: list[str] = []
    # LegacyDERPString is this node's home LegacyDERPString region ID integer, but shoved into an
    # IP:port string for legacy reasons. The IP address is always "127.3.3.40"
    # (a loopback address (127) followed by the digits over the letters DERP on
    # a QWERTY keyboard (3.3.40)). The "port number" is the home LegacyDERPString region ID
    # integer.
    # 
    # Deprecated: HomeDERP has replaced this, but old servers might still send
    # this field. See tailscale/tailscale#14636. Do not use this field in code
    # other than in the upgradeNode func, which canonicalizes it to HomeDERP
    # if it arrives as a LegacyDERPString string on the wire.
    legacy_derp_string: str = msgspec.field(default="", name="DERP")
    # HomeDERP is the modern version of the DERP string field, with just an
    # integer. The client advertises support for this as of capver 111.
    # 
    # HomeDERP may be zero if not (yet) known, but ideally always be non-zero
    # for magicsock connectivity to function normally.
    home_derp: int = msgspec.field(default=0, name="HomeDERP")
    hostinfo: Hostinfo | None = None
    created: str = ""
    # if non-zero, the node's capability version; old servers might not send
    cap: int = 0
    # Tags are the list of ACL tags applied to this node.
    # Tags take the form of `tag:<value>` where value starts
    # with a letter and only contains alphanumerics and dashes `-`.
    # Some valid tag examples:
    #   `tag:prod`
    #   `tag:database`
    #   `tag:lab-1`
    tags: list[str] = []
    # PrimaryRoutes are the routes from AllowedIPs that this node
    # is currently the primary subnet router for, as determined
    # by the control plane. It does not include the self address
    # values from Addresses that are in AllowedIPs.
    primary_routes: list[str] = []
    # LastSeen is when the node was last online. It is not
    # updated when Online is true. It is nil if the current
    # node doesn't have permission to know, or the node
    # has never been online.
    last_seen: str | None = None
    # Online is whether the node is currently connected to the
    # coordination server.  A value of nil means unknown, or the
    # current node doesn't have permission to know.
    online: bool | None = None
    # TODO(crawshaw): replace with MachineStatus
    machine_authorized: bool = False
    # Capabilities are capabilities that the node has.
    # They're free-form strings, but should be in the form of URLs/URIs
    # such as:
    #    "https://tailscale.com/cap/is-admin"
    #    "https://tailscale.com/cap/file-sharing"
    # 
    # Deprecated: use CapMap instead. See https://github.com/tailscale/tailscale/issues/11508
    capabilities: list[str] = []
    # CapMap is a map of capabilities to their optional argument/data values.
    # 
    # It is valid for a capability to not have any argument/data values; such
    # capabilities can be tested for using the HasCap method. These type of
    # capabilities are used to indicate that a node has a capability, but there
    # is no additional data associated with it. These were previously
    # represented by the Capabilities field, but can now be represented by
    # CapMap with an empty value.
    # 
    # See NodeCapability for more information on keys.
    # 
    # Metadata about nodes can be transmitted in 3 ways:
    # 1. MapResponse.Node.CapMap describes attributes that affect behavior for
    #    this node, such as which features have been enabled through the admin
    #    panel and any associated configuration details.
    # 2. MapResponse.PacketFilter(s) describes access (both IP and application
    #    based) that should be granted to peers.
    # 3. MapResponse.Peers[].CapMap describes attributes regarding a peer node,
    #    such as which features the peer supports or if that peer is preferred
    #    for a particular task vs other peers that could also be chosen.
    cap_map: dict[str, list[Any] | None] = {}
    # UnsignedPeerAPIOnly means that this node is not signed nor subject to TKA
    # restrictions. However, in exchange for that privilege, it does not get
    # network access. It can only access this node's peerapi, which may not let
    # it do anything. It is the tailscaled client's job to double-check the
    # MapResponse's PacketFilter to verify that its AllowedIPs will not be
    # accepted by the packet filter.
    unsigned_peer_api_only: bool = msgspec.field(default=False, name="UnsignedPeerAPIOnly")
    # MagicDNS base name (for normal non-shared-in nodes), FQDN (without trailing dot, for shared-in nodes), or Hostname (if no MagicDNS)
    computed_name: str = ""
    # either "ComputedName" or "ComputedName (computedHostIfDifferent)", if computedHostIfDifferent is set
    computed_name_with_host: str = ""
    # DataPlaneAuditLogID is the per-node logtail ID used for data plane audit logging.
    data_plane_audit_log_id: str = msgspec.field(default="", name="DataPlaneAuditLogID")
    # Expired is whether this node's key has expired. Control may send
    # this; clients are only allowed to set this from false to true. On
    # the client, this is calculated client-side based on a timestamp sent
    # from control, to avoid clock skew issues.
    expired: bool = False
    # SelfNodeV4MasqAddrForThisPeer is the IPv4 that this peer knows the current node as.
    # It may be empty if the peer knows the current node by its native
    # IPv4 address.
    # This field is only populated in a MapResponse for peers and not
    # for the current node.
    # 
    # If set, it should be used to masquerade traffic originating from the
    # current node to this peer. The masquerade address is only relevant
    # for this peer and not for other peers.
    # 
    # This only applies to traffic originating from the current node to the
    # peer or any of its subnets. Traffic originating from subnet routes will
    # not be masqueraded (e.g. in case of --snat-subnet-routes).
    self_node_v4_masq_addr_for_this_peer: str | None = None
    # SelfNodeV6MasqAddrForThisPeer is the IPv6 that this peer knows the current node as.
    # It may be empty if the peer knows the current node by its native
    # IPv6 address.
    # This field is only populated in a MapResponse for peers and not
    # for the current node.
    # 
    # If set, it should be used to masquerade traffic originating from the
    # current node to this peer. The masquerade address is only relevant
    # for this peer and not for other peers.
    # 
    # This only applies to traffic originating from the current node to the
    # peer or any of its subnets. Traffic originating from subnet routes will
    # not be masqueraded (e.g. in case of --snat-subnet-routes).
    self_node_v6_masq_addr_for_this_peer: str | None = None
    # IsWireGuardOnly indicates that this is a non-Tailscale WireGuard peer, it
    # is not expected to speak Disco or DERP, and it must have Endpoints in
    # order to be reachable.
    is_wire_guard_only: bool = False
    # IsJailed indicates that this node is jailed and should not be allowed
    # initiate connections, however outbound connections to it should still be
    # allowed.
    is_jailed: bool = False
    # ExitNodeDNSResolvers is the list of DNS servers that should be used when this
    # node is marked IsWireGuardOnly and being used as an exit node.
    exit_node_dns_resolvers: list[Resolver] = msgspec.field(default_factory=list, name="ExitNodeDNSResolvers")


class Hostinfo(msgspec.Struct, rename="pascal", omit_defaults=True):
    "Hostinfo contains a summary of a Tailscale host.\n\nBecause it contains pointers (slices), this type should not be used\nas a value type."

    # version of this code (in version.Long format)
    ipn_version: str = msgspec.field(default="", name="IPNVersion")
    # logtail ID of frontend instance
    frontend_log_id: str = msgspec.field(default="", name="FrontendLogID")
    # logtail ID of backend instance
    backend_log_id: str = msgspec.field(default="", name="BackendLogID")
    # operating system the client runs on (a version.OS value)
    os: str = msgspec.field(default="", name="OS")
    # OSVersion is the version of the OS, if available.
    # 
    # For Android, it's like "10", "11", "12", etc. For iOS and macOS it's like
    # "15.6.1" or "12.4.0". For Windows it's like "10.0.19044.1889". For
    # FreeBSD it's like "12.3-STABLE".
    # 
    # For Linux, prior to Tailscale 1.32, we jammed a bunch of fields into this
    # string on Linux, like "Debian 10.4; kernel=xxx; container; env=kn" and so
    # on. As of Tailscale 1.32, this is simply the kernel version on Linux, like
    # "5.10.0-17-amd64".
    os_version: str = msgspec.field(default="", name="OSVersion")
    # best-effort whether the client is running in a container
    container: bool | None = None
    # a hostinfo.EnvType in string form
    env: str = ""
    # "debian", "ubuntu", "nixos", ...
    distro: str = ""
    # "20.04", ...
    distro_version: str = ""
    # "jammy", "bullseye", ...
    distro_code_name: str = ""
    # App is used to disambiguate Tailscale clients that run using tsnet.
    app: str = ""
    # if a desktop was detected on Linux
    desktop: bool | None = None
    # Tailscale package to disambiguate ("choco", "appstore", etc; "" for unknown)
    package: str = ""
    # mobile phone model ("Pixel 3a", "iPhone12,3")
    device_model: str = ""
    # macOS/iOS APNs device token for notifications (and Android in the future)
    push_device_token: str = ""
    # name of the host the client runs on
    hostname: str = ""
    # indicates whether the host is blocking incoming connections
    shields_up: bool = False
    # indicates this node exists in netmap because it's owned by a shared-to user
    sharee_node: bool = False
    # indicates that the user has opted out of sending logs and support
    no_logs_no_support: bool = False
    # WireIngress indicates that the node would like to be wired up server-side
    # (DNS, etc) to be able to use Tailscale Funnel, even if it's not currently
    # enabled. For example, the user might only use it for intermittent
    # foreground CLI serve sessions, for which they'd like it to work right
    # away, even if it's disabled most of the time. As an optimization, this is
    # only sent if IngressEnabled is false, as IngressEnabled implies that this
    # option is true.
    wire_ingress: bool = False
    # if the node has any funnel endpoint enabled
    ingress_enabled: bool = False
    # indicates that the node has opted-in to admin-console-drive remote updates
    allows_update: bool = False
    # the current host's machine type (uname -m)
    machine: str = ""
    # GOARCH value (of the built binary)
    go_arch: str = ""
    # GOARM, GOAMD64, etc (of the built binary)
    go_arch_var: str = ""
    # Go version binary was built with
    go_version: str = ""
    # set of IP ranges this client can route
    routable_ips: list[str] = msgspec.field(default_factory=list, name="RoutableIPs")
    # set of ACL tags this node wants to claim
    request_tags: list[str] = []
    # MAC address(es) to send Wake-on-LAN packets to wake this node (lowercase hex w/ colons)
    wol_macs: list[str] = msgspec.field(default_factory=list, name="WoLMACs")
    # services advertised by this machine
    services: list[Service] = []
    net_info: NetInfo | None = None
    # if advertised
    ssh_host_keys: list[str] = msgspec.field(default_factory=list, name="sshHostKeys")
    cloud: str = ""
    # if the client is running in userspace (netstack) mode
    userspace: bool | None = None
    # if the client's subnet router is running in userspace (netstack) mode
    userspace_router: bool | None = None
    # if the client is running the app-connector service
    app_connector: bool | None = None
    # opaque hash of the most recent list of tailnet services, change in hash indicates config should be fetched via c2n
    services_hash: str = ""
    # the client’s selected exit node, empty when unselected.
    exit_node_id: str = msgspec.field(default="", name="ExitNodeID")
    # Location represents geographical location data about a
    # Tailscale host. Location is optional and only set if
    # explicitly declared by a node.
    location: Location | None = None
    # TPM device metadata, if available
    t_p_m: TPMInfo | None = None
    # StateEncrypted reports whether the node state is stored encrypted on
    # disk. The actual mechanism is platform-specific:
    #   * Apple nodes use the Keychain
    #   * Linux and Windows nodes use the TPM
    #   * Android apps use EncryptedSharedPreferences
    state_encrypted: bool | None = None


class NetInfo(msgspec.Struct, rename="pascal", omit_defaults=True):
    "NetInfo contains information about the host's network state."

    # MappingVariesByDestIP says whether the host's NAT mappings
    # vary based on the destination IP.
    mapping_varies_by_dest_ip: bool | None = msgspec.field(default=None, name="MappingVariesByDestIP")
    # WorkingIPv6 is whether the host has IPv6 internet connectivity.
    working_ipv6: bool | None = msgspec.field(default=None, name="WorkingIPv6")
    # OSHasIPv6 is whether the OS supports IPv6 at all, regardless of
    # whether IPv6 internet connectivity is available.
    os_has_ipv6: bool | None = msgspec.field(default=None, name="OSHasIPv6")
    # WorkingUDP is whether the host has UDP internet connectivity.
    working_udp: bool | None = msgspec.field(default=None, name="WorkingUDP")
    # WorkingICMPv4 is whether ICMPv4 works.
    # Empty means not checked.
    working_i_c_m_pv4: bool | None = None
    # HavePortMap is whether we have an existing portmap open
    # (UPnP, PMP, or PCP).
    have_port_map: bool = False
    # UPnP is whether UPnP appears present on the LAN.
    # Empty means not checked.
    upnp: bool | None = msgspec.field(default=None, name="UPnP")
    # PMP is whether NAT-PMP appears present on the LAN.
    # Empty means not checked.
    pmp: bool | None = msgspec.field(default=None, name="PMP")
    # PCP is whether PCP appears present on the LAN.
    # Empty means not checked.
    pcp: bool | None = msgspec.field(default=None, name="PCP")
    # PreferredDERP is this node's preferred (home) DERP region ID.
    # This is where the node expects to be contacted to begin a
    # peer-to-peer connection. The node might be be temporarily
    # connected to multiple DERP servers (to speak to other nodes
    # that are located elsewhere) but PreferredDERP is the region ID
    # that the node subscribes to traffic at.
    # Zero means disconnected or unknown.
    preferred_derp: int = msgspec.field(default=0, name="PreferredDERP")
    # LinkType is the current link type, if known.
    link_type: str = ""
    # DERPLatency is the fastest recent time to reach various
    # DERP STUN servers, in seconds. The map key is the
    # "regionID-v4" or "-v6"; it was previously the DERP server's
    # STUN host:port.
    # 
    # This should only be updated rarely, or when there's a
    # material change, as any change here also gets uploaded to
    # the control plane.
    derp_latency: dict[str, float] = msgspec.field(default_factory=dict, name="DERPLatency")
    # FirewallMode encodes both which firewall mode was selected and why.
    # It is Linux-specific (at least as of 2023-08-19) and is meant to help
    # debug iptables-vs-nftables issues. The string is of the form
    # "{nft,ift}-REASON", like "nft-forced" or "ipt-default". Empty means
    # either not Linux or a configuration in which the host firewall rules
    # are not managed by tailscaled.
    firewall_mode: str = ""


class Service(msgspec.Struct, rename="pascal", omit_defaults=True):
    "Service represents a service running on a node."

    # Proto is the type of service. It's usually the constant TCP
    # or UDP ("tcp" or "udp"), but it can also be one of the
    # following meta service values:
    # 
    #     * "peerapi4": peerapi is available on IPv4; Port is the
    #        port number that the peerapi is running on the
    #        node's Tailscale IPv4 address.
    #     * "peerapi6": peerapi is available on IPv6; Port is the
    #        port number that the peerapi is running on the
    #        node's Tailscale IPv6 address.
    #     * "peerapi-dns-proxy": the local peerapi service supports
    #        being a DNS proxy (when the node is an exit
    #        node). For this service, the Port number must only be 1.
    proto: str = ""
    # Port is the port number.
    # 
    # For Proto "peerapi-dns", it must be 1.
    port: int = 0
    # Description is the textual description of the service,
    # usually the process name that's running.
    description: str = ""


class Location(msgspec.Struct, rename="pascal", omit_defaults=True):
    "Location represents geographical location data about a\nTailscale host. Location is optional and only set if\nexplicitly declared by a node."

    # User friendly country name, with proper capitalization ("Canada")
    country: str = ""
    # ISO 3166-1 alpha-2 in upper case ("CA")
    country_code: str = ""
    # User friendly city name, with proper capitalization ("Squamish")
    city: str = ""
    # CityCode is a short code representing the city in upper case.
    # CityCode is used to disambiguate a city from another location
    # with the same city name. It uniquely identifies a particular
    # geographical location, within the tailnet.
    # IATA, ICAO or ISO 3166-2 codes are recommended ("YSE")
    city_code: str = ""
    # Latitude, Longitude are optional geographical coordinates of the node, in degrees.
    # No particular accuracy level is promised; the coordinates may simply be the center of the city or country.
    latitude: float = 0.0
    longitude: float = 0.0
    # Priority determines the order of use of an exit node when a
    # location based preference matches more than one exit node,
    # the node with the highest priority wins. Nodes of equal
    # probability may be selected arbitrarily.
    # 
    # A value of 0 means the exit node does not have a priority
    # preference. A negative int is not allowed.
    priority: int = 0


class TPMInfo(msgspec.Struct, rename="pascal", omit_defaults=True):
    "TPMInfo contains information about a TPM 2.0 device present on a node.\nAll fields are read from TPM_CAP_TPM_PROPERTIES, see Part 2, section 6.13 of\nhttps://trustedcomputinggroup.org/resource/tpm-library-specification/."

    # Manufacturer is a 4-letter code from section 4.1 of
    # https://trustedcomputinggroup.org/resource/vendor-id-registry/,
    # for example "MSFT" for Microsoft.
    # Read from TPM_PT_MANUFACTURER.
    manufacturer: str = ""
    # Vendor is a vendor ID string, up to 16 characters.
    # Read from TPM_PT_VENDOR_STRING_*.
    vendor: str = ""
    # Model is a vendor-defined TPM model.
    # Read from TPM_PT_VENDOR_TPM_TYPE.
    model: int = 0
    # FirmwareVersion is the version number of the firmware.
    # Read from TPM_PT_FIRMWARE_VERSION_*.
    firmware_version: int = 0
    # SpecRevision is the TPM 2.0 spec revision encoded as a single number. All
    # revisions can be found at
    # https://trustedcomputinggroup.org/resource/tpm-library-specification/.
    # Before revision 184, TCG used the "01.83" format for revision 183.
    spec_revision: int = 0
    # FamilyIndicator is the TPM spec family, like "2.0".
    # Read from TPM_PT_FAMILY_INDICATOR.
    family_indicator: str = ""


class ClientVersion(msgspec.Struct, rename="pascal", omit_defaults=True):
    "ClientVersion is information about the latest client version that's available\nfor the client (and whether they're already running it).\n\nIt does not include a URL to download the client, as that varies by platform."

    # RunningLatest is true if the client is running the latest build.
    running_latest: bool = False
    # LatestVersion is the latest version.Short ("1.34.2") version available
    # for download for the client's platform and packaging type.
    # It won't be populated if RunningLatest is true.
    latest_version: str = ""
    # UrgentSecurityUpdate is set when the client is missing an important
    # security update. That update may be in LatestVersion or earlier.
    # UrgentSecurityUpdate should not be set if RunningLatest is false.
    urgent_security_update: bool = False
    # Notify is whether the client should do an OS-specific notification about
    # a new version being available. This should not be populated if
    # RunningLatest is true. The client should not notify multiple times for
    # the same LatestVersion value.
    notify: bool = False
    # NotifyURL is a URL to open in the browser when the user clicks on the
    # notification, when Notify is true.
    notify_url: str = msgspec.field(default="", name="NotifyURL")
    # NotifyText is the text to show in the notification, when Notify is true.
    notify_text: str = ""


class ServeConfig(msgspec.Struct, rename="pascal", omit_defaults=True):
    "ServeConfig is the JSON type stored in the StateStore for\nStateKey \"_serve/$PROFILE_ID\" as returned by ServeConfigKey."

    # TCP are the list of TCP port numbers that tailscaled should handle for
    # the Tailscale IP addresses. (not subnet routers, etc)
    tcp: dict[str, TCPPortHandler] = msgspec.field(default_factory=dict, name="TCP")
    # Web maps from "$SNI_NAME:$PORT" to a set of HTTP handlers
    # keyed by mount point ("/", "/foo", etc)
    web: dict[str, WebServerConfig] = {}
    # Services maps from service name (in the form "svc:dns-label") to a ServiceConfig.
    # Which describes the L3, L4, and L7 forwarding information for the service.
    services: dict[str, ServiceConfig] = {}
    # AllowFunnel is the set of SNI:port values for which funnel
    # traffic is allowed, from trusted ingress peers.
    allow_funnel: dict[str, bool] = {}
    # Foreground is a map of an IPN Bus session ID to an alternate foreground serve config that's valid for the
    # life of that WatchIPNBus session ID. This allows the config to specify ephemeral configs that are used
    # in the CLI's foreground mode to ensure ungraceful shutdowns of either the client or the LocalBackend does not
    # expose ports that users are not aware of. In practice this contains any serve config set via 'tailscale
    # serve' command run without the '--bg' flag. ServeConfig contained by Foreground is not expected itself to contain
    # another Foreground block.
    foreground: dict[str, ServeConfig] = {}
    # ETag is the checksum of the serve config that's populated
    # by the LocalClient through the HTTP ETag header during a
    # GetServeConfig request and is translated to an If-Match header
    # during a SetServeConfig request.


class TCPPortHandler(msgspec.Struct, rename="pascal", omit_defaults=True):
    "TCPPortHandler describes what to do when handling a TCP\nconnection."

    # HTTPS, if true, means that tailscaled should handle this connection as an
    # HTTPS request as configured by ServeConfig.Web.
    # 
    # It is mutually exclusive with TCPForward.
    https: bool = msgspec.field(default=False, name="HTTPS")
    # HTTP, if true, means that tailscaled should handle this connection as an
    # HTTP request as configured by ServeConfig.Web.
    # 
    # It is mutually exclusive with TCPForward.
    http: bool = msgspec.field(default=False, name="HTTP")
    # TCPForward is the IP:port to forward TCP connections to.
    # Whether or not TLS is terminated by tailscaled depends on
    # TerminateTLS.
    # 
    # It is mutually exclusive with HTTPS.
    tcp_forward: str = msgspec.field(default="", name="TCPForward")
    # TerminateTLS, if non-empty, means that tailscaled should terminate the
    # TLS connections before forwarding them to TCPForward, permitting only the
    # SNI name with this value. It is only used if TCPForward is non-empty.
    # (the HTTPS mode uses ServeConfig.Web)
    terminate_tls: str = msgspec.field(default="", name="TerminateTLS")
    # ProxyProtocol indicates whether to send a PROXY protocol header
    # before forwarding the connection to TCPForward.
    # 
    # This is only valid if TCPForward is non-empty.
    proxy_protocol: int = 0


class WebServerConfig(msgspec.Struct, rename="pascal"):
    "WebServerConfig describes a web server's configuration."

    # mountPoint => handler
    handlers: dict[str, HTTPHandler] = {}


class HTTPHandler(msgspec.Struct, rename="pascal", omit_defaults=True):
    "HTTPHandler is either a path or a proxy to serve."

    # absolute path to directory or file to serve
    path: str = ""
    # http://localhost:3000/, localhost:3030, 3030
    proxy: str = ""
    # plaintext to serve (primarily for testing)
    text: str = ""
    # peer capabilities to forward in grant header, e.g. example.com/cap/mon
    accept_app_caps: list[str] = []
    # Redirect, if not empty, is the target URL to redirect requests to.
    # By default, we redirect with HTTP 302 (Found) status.
    # If Redirect starts with '<httpcode>:', then we use that status instead.
    # 
    # The target URL supports the following expansion variables:
    #   - ${HOST}: replaced with the request's Host header value
    #   - ${REQUEST_URI}: replaced with the request's full URI (path and query string)
    redirect: str = ""


class ServiceConfig(msgspec.Struct, rename="pascal", omit_defaults=True):
    "ServiceConfig contains the config information for a single service.\nit contains a bool to indicate if the service is in Tun mode (L3 forwarding).\nIf the service is not in Tun mode, the service is configured by the L4 forwarding\n(TCP ports) and/or the L7 forwarding (http handlers) information."

    # TCP are the list of TCP port numbers that tailscaled should handle for
    # the Tailscale IP addresses. (not subnet routers, etc)
    tcp: dict[str, TCPPortHandler] = msgspec.field(default_factory=dict, name="TCP")
    # Web maps from "$SNI_NAME:$PORT" to a set of HTTP handlers
    # keyed by mount point ("/", "/foo", etc)
    web: dict[str, WebServerConfig] = {}
    # Tun determines if the service should be using L3 forwarding (Tun mode).
    tun: bool = False


class WhoIsResponse(msgspec.Struct, rename="pascal"):
    "WhoIsResponse is the JSON type returned by tailscaled debug server's /whois?ip=$IP handler.\nIn successful whois responses, Node and UserProfile are never nil."

    node: Node = msgspec.field(default_factory=lambda: Node())
    user_profile: UserProfile = msgspec.field(default_factory=lambda: UserProfile())
    # CapMap is a map of capabilities to their values.
    # See tailcfg.PeerCapMap and tailcfg.PeerCapability for details.
    cap_map: dict[str, list[Any] | None] = {}


class Resolver(msgspec.Struct, rename="pascal", omit_defaults=True):
    "Resolver is the configuration for one DNS resolver."

    # Addr is the address of the DNS resolver, one of:
    #  - A plain IP address for a "classic" UDP+TCP DNS resolver.
    #    This is the common format as sent by the control plane.
    #  - An IP:port, for tests.
    #  - "https://resolver.com/path" for DNS over HTTPS; currently
    #    as of 2022-09-08 only used for certain well-known resolvers
    #    (see the publicdns package) for which the IP addresses to dial DoH are
    #    known ahead of time, so bootstrap DNS resolution is not required.
    #  - "http://node-address:port/path" for DNS over HTTP over WireGuard. This
    #    is implemented in the PeerAPI for exit nodes and app connectors.
    #  - [TODO] "tls://resolver.com" for DNS over TCP+TLS
    addr: str = ""
    # BootstrapResolution is an optional suggested resolution for the
    # DoT/DoH resolver, if the resolver URL does not reference an IP
    # address directly.
    # BootstrapResolution may be empty, in which case clients should
    # look up the DoT/DoH server using their local "classic" DNS
    # resolver.
    # 
    # As of 2022-09-08, BootstrapResolution is not yet used.
    bootstrap_resolution: list[str] = []
    # UseWithExitNode designates that this resolver should continue to be used when an
    # exit node is in use. Normally, DNS resolution is delegated to the exit node but
    # there are situations where it is preferable to still use a Split DNS server and/or
    # global DNS server instead of the exit node.
    use_with_exit_node: bool = False
