"""Client library for the Tailscale Local API."""

from tslocalapi._client import LocalClient
from tslocalapi._errors import (
    TailscaleError,
    AccessDeniedError,
    PreconditionsFailedError,
    PeerNotFoundError,
    ConnectionError as TailscaleConnectionError,
    DaemonNotRunningError,
    HttpError,
)
from tslocalapi._types import (
    Status,
    PeerStatus,
    UserProfile,
    CurrentTailnet,
    TailnetStatus,
    Prefs,
    MaskedPrefs,
    WhoIsResponse,
    ProfileStatus,
    LoginProfile,
    NetworkProfile,
    PingResult,
    Notify,
    DERPMap,
    DERPRegion,
    DERPNode,
    ClientVersion,
    ServeConfig,
    WaitingFile,
    FileTarget,
    ExitNodeSuggestionResponse,
    ReloadConfigResponse,
    DNSOSConfig,
    OptionalFeatures,
    Node,
    Hostinfo,
)

__version__ = "0.0.1"

__all__ = [
    "LocalClient",
    "TailscaleError",
    "AccessDeniedError",
    "PreconditionsFailedError",
    "PeerNotFoundError",
    "TailscaleConnectionError",
    "DaemonNotRunningError",
    "HttpError",
    "Status",
    "PeerStatus",
    "UserProfile",
    "CurrentTailnet",
    "TailnetStatus",
    "Prefs",
    "MaskedPrefs",
    "WhoIsResponse",
    "ProfileStatus",
    "LoginProfile",
    "NetworkProfile",
    "PingResult",
    "Notify",
    "DERPMap",
    "DERPRegion",
    "DERPNode",
    "ClientVersion",
    "ServeConfig",
    "WaitingFile",
    "FileTarget",
    "ExitNodeSuggestionResponse",
    "ReloadConfigResponse",
    "DNSOSConfig",
    "OptionalFeatures",
    "Node",
    "Hostinfo",
]
