# Code generated by cmd/typegen; DO NOT EDIT.

from __future__ import annotations

from typing import Any

import msgspec


class Status(msgspec.Struct, rename="pascal", omit_defaults=True):
    "Status represents the entire state of the IPN network."

    # Version is the daemon's long version (see version.Long).
    version: str = ""
    # TUN is whether /dev/net/tun (or equivalent kernel interface) is being
    # used. If false, it's running in userspace mode.
    tun: bool = msgspec.field(default=False, name="TUN")
    # BackendState is an ipn.State string value:
    #  "NoState", "NeedsLogin", "NeedsMachineAuth", "Stopped",
    #  "Starting", "Running".
    backend_state: str = ""
    # HaveNodeKey is whether the current profile has a node key configured.
    have_node_key: bool = False
    # current URL provided by control to authorize client
    auth_url: str = msgspec.field(default="", name="AuthURL")
    # Tailscale IP(s) assigned to this node
    tailscale_ips: list[str] | None = msgspec.field(default=None, name="TailscaleIPs")
    self_node: PeerStatus | None = msgspec.field(default=None, name="Self")
    # ExitNodeStatus describes the current exit node.
    # If nil, an exit node is not in use.
    exit_node_status: ExitNodeStatus | None = None
    # Health contains health check problems.
    # Empty means everything is good. (or at least that no known
    # problems are detected)
    health: list[str] | None = None
    # This field is the legacy name of CurrentTailnet.MagicDNSSuffix.
    # 
    # Deprecated: use CurrentTailnet.MagicDNSSuffix instead.
    magic_dns_suffix: str = msgspec.field(default="", name="MagicDNSSuffix")
    # CurrentTailnet is information about the tailnet that the node
    # is currently connected to. When not connected, this field is nil.
    current_tailnet: TailnetStatus | None = None
    # CertDomains are the set of DNS names for which the control
    # plane server will assist with provisioning TLS
    # certificates. See SetDNSRequest for dns-01 ACME challenges
    # for e.g. LetsEncrypt. These names are FQDNs without
    # trailing periods, and without any "_acme-challenge." prefix.
    cert_domains: list[str] | None = None
    # Peer is the state of each peer, keyed by each peer's current public key.
    peer: dict[str, PeerStatus] | None = None
    # User contains profile information about UserIDs referenced by
    # PeerStatus.UserID, PeerStatus.AltSharerUserID, etc.
    user: dict[str, UserProfile] | None = None
    # ClientVersion, when non-nil, contains information about the latest
    # version of the Tailscale client that's available. Depending on
    # the platform and client settings, it may not be available.
    client_version: ClientVersion | None = None


class PeerStatus(msgspec.Struct, rename="pascal", omit_defaults=True):
    "PeerStatus describes a peer node and its current state.\nWARNING: The fields in PeerStatus are merged by the AddPeer method in the StatusBuilder.\nWhen adding a new field to PeerStatus, you must update AddPeer to handle merging\nthe new field. The AddPeer function is responsible for combining multiple updates\nto the same peer, and any new field that is not merged properly may lead to\ninconsistencies or lost data in the peer status."

    id: str = msgspec.field(default="", name="ID")
    public_key: str = ""
    # HostInfo's Hostname (not a DNS name or necessarily unique)
    host_name: str = ""
    # DNSName is the Peer's FQDN. It ends with a dot.
    # It has the form "host.<MagicDNSSuffix>."
    dns_name: str = msgspec.field(default="", name="DNSName")
    # HostInfo.OS
    os: str = msgspec.field(default="", name="OS")
    user_id: int = msgspec.field(default=0, name="UserID")
    # AltSharerUserID is the user who shared this node
    # if it's different than UserID. Otherwise it's zero.
    alt_sharer_user_id: int = msgspec.field(default=0, name="AltSharerUserID")
    # TailscaleIPs are the IP addresses assigned to the node.
    tailscale_ips: list[str] | None = msgspec.field(default=None, name="TailscaleIPs")
    # AllowedIPs are IP addresses allowed to route to this node.
    allowed_ips: list[str] | None = msgspec.field(default=None, name="AllowedIPs")
    # Tags are the list of ACL tags applied to this node.
    # See tailscale.com/tailcfg#Node.Tags for more information.
    tags: list[str] | None = None
    # PrimaryRoutes are the routes this node is currently the primary
    # subnet router for, as determined by the control plane. It does
    # not include the IPs in TailscaleIPs.
    primary_routes: list[str] | None = None
    # Endpoints:
    addrs: list[str] | None = None
    # one of Addrs, or unique if roaming
    cur_addr: str = ""
    # DERP region
    relay: str = ""
    # peer relay address (ip:port:vni)
    peer_relay: str = ""
    rx_bytes: int = 0
    tx_bytes: int = 0
    # time registered with tailcontrol
    created: str = ""
    # time last packet sent
    last_write: str = ""
    # last seen to tailcontrol; only present if offline
    last_seen: str = ""
    # with local wireguard
    last_handshake: str = ""
    # whether node is connected to the control plane
    online: bool = False
    # true if this is the currently selected exit node.
    exit_node: bool = False
    # true if this node can be an exit node (offered && approved)
    exit_node_option: bool = False
    # Active is whether the node was recently active. The
    # definition is somewhat undefined but has historically and
    # currently means that there was some packet sent to this
    # peer in the past two minutes. That definition is subject to
    # change.
    active: bool = False
    # PeerAPIURL are the URLs of the node's PeerAPI servers.
    peer_api_url: list[str] | None = msgspec.field(default=None, name="PeerAPIURL")
    # TaildropTargetStatus represents the node's eligibility to have files shared to it.
    taildrop_target: int = 0
    # Reason why this peer cannot receive files. Empty if CanReceiveFiles=true
    no_file_sharing_reason: str = ""
    # Capabilities are capabilities that the node has.
    # They're free-form strings, but should be in the form of URLs/URIs
    # such as:
    #    "https://tailscale.com/cap/is-admin"
    #    "https://tailscale.com/cap/file-sharing"
    #    "funnel"
    # 
    # Deprecated: use CapMap instead. See https://github.com/tailscale/tailscale/issues/11508
    # Every value is Capabilities is also a key in CapMap, even if it
    # has no values in that map.
    capabilities: list[str] = []
    # CapMap is a map of capabilities to their values.
    cap_map: dict[str, list[Any] | None] = {}
    # SSH_HostKeys are the node's SSH host keys, if known.
    ssh_host_keys: list[str] = msgspec.field(default_factory=list, name="sshHostKeys")
    # ShareeNode indicates this node exists in the netmap because
    # it's owned by a shared-to user and that node might connect
    # to us. These nodes should be hidden by "tailscale status"
    # etc by default.
    sharee_node: bool = False
    # InNetworkMap means that this peer was seen in our latest network map.
    # In theory, all of InNetworkMap and InMagicSock and InEngine should all be true.
    in_network_map: bool = False
    # InMagicSock means that this peer is being tracked by magicsock.
    # In theory, all of InNetworkMap and InMagicSock and InEngine should all be true.
    in_magic_sock: bool = False
    # InEngine means that this peer is tracked by the wireguard engine.
    # In theory, all of InNetworkMap and InMagicSock and InEngine should all be true.
    in_engine: bool = False
    # Expired means that this peer's node key has expired, based on either
    # information from control or optimisically set on the client if the
    # expiration time has passed.
    expired: bool = False
    # KeyExpiry, if present, is the time at which the node key expired or
    # will expire.
    key_expiry: str | None = None
    location: Location | None = None


class TailnetStatus(msgspec.Struct, rename="pascal"):
    "TailnetStatus is information about a Tailscale network (\"tailnet\")."

    # Name is the name of the network that's currently in use.
    name: str = ""
    # MagicDNSSuffix is the network's MagicDNS suffix for nodes
    # in the network such as "userfoo.tailscale.net".
    # There are no surrounding dots.
    # MagicDNSSuffix should be populated regardless of whether a domain
    # has MagicDNS enabled.
    magic_dns_suffix: str = msgspec.field(default="", name="MagicDNSSuffix")
    # MagicDNSEnabled is whether or not the network has MagicDNS enabled.
    # Note that the current device may still not support MagicDNS if
    # `--accept-dns=false` was used.
    magic_dns_enabled: bool = msgspec.field(default=False, name="MagicDNSEnabled")


class ExitNodeStatus(msgspec.Struct, rename="pascal"):
    "ExitNodeStatus describes the current exit node."

    # ID is the exit node's ID.
    id: str = msgspec.field(default="", name="ID")
    # Online is whether the exit node is alive.
    online: bool = False
    # TailscaleIPs are the exit node's IP addresses assigned to the node.
    tailscale_ips: list[str] | None = msgspec.field(default=None, name="TailscaleIPs")


class PingResult(msgspec.Struct, rename="pascal", omit_defaults=True):
    "PingResult contains response information for the \"tailscale ping\" subcommand,\nsaying how Tailscale can reach a Tailscale IP or subnet-routed IP.\nSee tailcfg.PingResponse for a related response that is sent back to control\nfor remote diagnostic pings."

    # ping destination
    ip: str = msgspec.field(default="", name="IP")
    # Tailscale IP of node handling IP (different for subnet routers)
    node_ip: str = msgspec.field(default="", name="NodeIP")
    # DNS name base or (possibly not unique) hostname
    node_name: str = ""
    err: str = ""
    latency_seconds: float = 0.0
    # Endpoint is a string of the form "{ip}:{port}" if direct UDP was used. It
    # is not currently set for TSMP.
    endpoint: str = ""
    # PeerRelay is a string of the form "{ip}:{port}:vni:{vni}" if a peer
    # relay was used. It is not currently set for TSMP. Note that this field
    # is not omitted during JSON encoding if it contains a zero value. This is
    # done for consistency with the Endpoint field; this structure is exposed
    # externally via localAPI, so we want to maintain the existing convention.
    peer_relay: str = ""
    # DERPRegionID is non-zero DERP region ID if DERP was used.
    # It is not currently set for TSMP pings.
    derp_region_id: int = msgspec.field(default=0, name="DERPRegionID")
    # DERPRegionCode is the three-letter region code
    # corresponding to DERPRegionID.
    # It is not currently set for TSMP pings.
    derp_region_code: str = msgspec.field(default="", name="DERPRegionCode")
    # PeerAPIPort is set by TSMP ping responses for peers that
    # are running a peerapi server. This is the port they're
    # running the server on.
    peer_api_port: int = msgspec.field(default=0, name="PeerAPIPort")
    # PeerAPIURL is the URL that was hit for pings of type "peerapi" (tailcfg.PingPeerAPI).
    # It's of the form "http://ip:port" (or [ip]:port for IPv6).
    peer_api_url: str = msgspec.field(default="", name="PeerAPIURL")
    # IsLocalIP is whether the ping request error is due to it being
    # a ping to the local node.
    is_local_ip: bool = msgspec.field(default=False, name="IsLocalIP")


class NetworkLockStatus(msgspec.Struct, rename="pascal"):
    "NetworkLockStatus represents whether network-lock is enabled,\nalong with details about the locally-known state of the tailnet\nkey authority."

    # Enabled is true if network lock is enabled.
    enabled: bool = False
    # Head describes the AUM hash of the leaf AUM. Head is nil
    # if network lock is not enabled.
    head: str | None = None
    # PublicKey describes the node's network-lock public key.
    # It may be zero if the node has not logged in.
    public_key: str = ""
    # NodeKey describes the node's current node-key. This field is not
    # populated if the node is not operating (i.e. waiting for a login).
    node_key: str | None = None
    # NodeKeySigned is true if our node is authorized by network-lock.
    node_key_signed: bool = False
    # NodeKeySignature is the current signature of this node's key.
    node_key_signature: Any | None = None
    # TrustedKeys describes the keys currently trusted to make changes
    # to network-lock.
    trusted_keys: list[TKAKey] | None = None
    # VisiblePeers describes peers which are visible in the netmap that
    # have valid Tailnet Lock signatures signatures.
    visible_peers: list[TKAPeer] | None = None
    # FilteredPeers describes peers which were removed from the netmap
    # (i.e. no connectivity) because they failed tailnet lock
    # checks.
    filtered_peers: list[TKAPeer] | None = None
    # StateID is a nonce associated with the network lock authority,
    # generated upon enablement. This field is not populated if the
    # network lock is disabled.
    state_id: int = msgspec.field(default=0, name="StateID")


class TKAKey(msgspec.Struct, rename="pascal"):
    "TKAKey describes a key trusted by network lock."

    kind: str = ""
    key: str = ""
    metadata: dict[str, str] | None = None
    votes: int = 0


class TKAPeer(msgspec.Struct, rename="pascal"):
    "TKAPeer describes a peer and its network lock details."

    # DNS
    name: str = ""
    id: int = msgspec.field(default=0, name="ID")
    stable_id: str = msgspec.field(default="", name="StableID")
    # Tailscale IP(s) assigned to this node
    tailscale_ips: list[str] | None = msgspec.field(default=None, name="TailscaleIPs")
    node_key: str = ""
    node_key_signature: Any = None


class PeerStatusLite(msgspec.Struct, rename="pascal"):
    # NodeKey is this peer's public node key.
    node_key: str = ""
    # TxBytes/RxBytes are the total number of bytes transmitted to/received
    # from this peer.
    tx_bytes: int = 0
    # TxBytes/RxBytes are the total number of bytes transmitted to/received
    # from this peer.
    rx_bytes: int = 0
    # LastHandshake is the last time a handshake succeeded with this peer. (Or
    # we got key confirmation via the first data message, which is
    # approximately the same thing.)
    # 
    # The time.Time zero value means that no handshake has succeeded, at least
    # since this peer was last known to WireGuard. (Tailscale removes peers
    # from the wireguard peer that are idle.)
    last_handshake: str = ""


class UserProfile(msgspec.Struct, rename="pascal", omit_defaults=True):
    "A UserProfile is display-friendly data for a [User].\nIt includes the LoginName for display purposes but *not* the Provider.\nIt also includes derived data from one of the user's logins."

    id: int = msgspec.field(default=0, name="ID")
    # "alice@smith.com"; for display purposes only (provider is not listed)
    login_name: str = ""
    # "Alice Smith"
    display_name: str = ""
    profile_pic_url: str = msgspec.field(default="", name="ProfilePicURL")


class Node(msgspec.Struct, rename="pascal", omit_defaults=True):
    "Node is a Tailscale device in a tailnet."

    id: int = msgspec.field(default=0, name="ID")
    stable_id: str = msgspec.field(default="", name="StableID")
    # Name is the FQDN of the node.
    # It is also the MagicDNS name for the node.
    # It has a trailing dot.
    # e.g. "host.tail-scale.ts.net."
    name: str = ""
    # User is the user who created the node. If ACL tags are in use for the
    # node then it doesn't reflect the ACL identity that the node is running
    # as.
    user: int = 0
    # Sharer, if non-zero, is the user who shared this node, if different than User.
    sharer: int = 0
    key: str = ""
    # the zero value if this node does not expire
    key_expiry: str = ""
    key_signature: str = ""
    machine: str = ""
    disco_key: str = ""
    # Addresses are the IP addresses of this Node directly.
    addresses: list[str] | None = None
    # AllowedIPs are the IP ranges to route to this node.
    # 
    # As of CapabilityVersion 112, this may be nil (null or undefined) on the wire
    # to mean the same as Addresses. Internally, it is always filled in with
    # its possibly-implicit value.
    allowed_ips: list[str] = msgspec.field(default_factory=list, name="AllowedIPs")
    # IP+port (public via STUN, and local LANs)
    endpoints: list[str] = []
    # LegacyDERPString is this node's home LegacyDERPString region ID integer, but shoved into an
    # IP:port string for legacy reasons. The IP address is always "127.3.3.40"
    # (a loopback address (127) followed by the digits over the letters DERP on
    # a QWERTY keyboard (3.3.40)). The "port number" is the home LegacyDERPString region ID
    # integer.
    # 
    # Deprecated: HomeDERP has replaced this, but old servers might still send
    # this field. See tailscale/tailscale#14636. Do not use this field in code
    # other than in the upgradeNode func, which canonicalizes it to HomeDERP
    # if it arrives as a LegacyDERPString string on the wire.
    legacy_derp_string: str = msgspec.field(default="", name="DERP")
    # HomeDERP is the modern version of the DERP string field, with just an
    # integer. The client advertises support for this as of capver 111.
    # 
    # HomeDERP may be zero if not (yet) known, but ideally always be non-zero
    # for magicsock connectivity to function normally.
    home_derp: int = msgspec.field(default=0, name="HomeDERP")
    hostinfo: Hostinfo | None = None
    created: str = ""
    # if non-zero, the node's capability version; old servers might not send
    cap: int = 0
    # Tags are the list of ACL tags applied to this node.
    # Tags take the form of `tag:<value>` where value starts
    # with a letter and only contains alphanumerics and dashes `-`.
    # Some valid tag examples:
    #   `tag:prod`
    #   `tag:database`
    #   `tag:lab-1`
    tags: list[str] = []
    # PrimaryRoutes are the routes from AllowedIPs that this node
    # is currently the primary subnet router for, as determined
    # by the control plane. It does not include the self address
    # values from Addresses that are in AllowedIPs.
    primary_routes: list[str] = []
    # LastSeen is when the node was last online. It is not
    # updated when Online is true. It is nil if the current
    # node doesn't have permission to know, or the node
    # has never been online.
    last_seen: str | None = None
    # Online is whether the node is currently connected to the
    # coordination server.  A value of nil means unknown, or the
    # current node doesn't have permission to know.
    online: bool | None = None
    # TODO(crawshaw): replace with MachineStatus
    machine_authorized: bool = False
    # Capabilities are capabilities that the node has.
    # They're free-form strings, but should be in the form of URLs/URIs
    # such as:
    #    "https://tailscale.com/cap/is-admin"
    #    "https://tailscale.com/cap/file-sharing"
    # 
    # Deprecated: use CapMap instead. See https://github.com/tailscale/tailscale/issues/11508
    capabilities: list[str] = []
    # CapMap is a map of capabilities to their optional argument/data values.
    # 
    # It is valid for a capability to not have any argument/data values; such
    # capabilities can be tested for using the HasCap method. These type of
    # capabilities are used to indicate that a node has a capability, but there
    # is no additional data associated with it. These were previously
    # represented by the Capabilities field, but can now be represented by
    # CapMap with an empty value.
    # 
    # See NodeCapability for more information on keys.
    # 
    # Metadata about nodes can be transmitted in 3 ways:
    # 1. MapResponse.Node.CapMap describes attributes that affect behavior for
    #    this node, such as which features have been enabled through the admin
    #    panel and any associated configuration details.
    # 2. MapResponse.PacketFilter(s) describes access (both IP and application
    #    based) that should be granted to peers.
    # 3. MapResponse.Peers[].CapMap describes attributes regarding a peer node,
    #    such as which features the peer supports or if that peer is preferred
    #    for a particular task vs other peers that could also be chosen.
    cap_map: dict[str, list[Any] | None] = {}
    # UnsignedPeerAPIOnly means that this node is not signed nor subject to TKA
    # restrictions. However, in exchange for that privilege, it does not get
    # network access. It can only access this node's peerapi, which may not let
    # it do anything. It is the tailscaled client's job to double-check the
    # MapResponse's PacketFilter to verify that its AllowedIPs will not be
    # accepted by the packet filter.
    unsigned_peer_api_only: bool = msgspec.field(default=False, name="UnsignedPeerAPIOnly")
    # MagicDNS base name (for normal non-shared-in nodes), FQDN (without trailing dot, for shared-in nodes), or Hostname (if no MagicDNS)
    computed_name: str = ""
    # either "ComputedName" or "ComputedName (computedHostIfDifferent)", if computedHostIfDifferent is set
    computed_name_with_host: str = ""
    # DataPlaneAuditLogID is the per-node logtail ID used for data plane audit logging.
    data_plane_audit_log_id: str = msgspec.field(default="", name="DataPlaneAuditLogID")
    # Expired is whether this node's key has expired. Control may send
    # this; clients are only allowed to set this from false to true. On
    # the client, this is calculated client-side based on a timestamp sent
    # from control, to avoid clock skew issues.
    expired: bool = False
    # SelfNodeV4MasqAddrForThisPeer is the IPv4 that this peer knows the current node as.
    # It may be empty if the peer knows the current node by its native
    # IPv4 address.
    # This field is only populated in a MapResponse for peers and not
    # for the current node.
    # 
    # If set, it should be used to masquerade traffic originating from the
    # current node to this peer. The masquerade address is only relevant
    # for this peer and not for other peers.
    # 
    # This only applies to traffic originating from the current node to the
    # peer or any of its subnets. Traffic originating from subnet routes will
    # not be masqueraded (e.g. in case of --snat-subnet-routes).
    self_node_v4_masq_addr_for_this_peer: str | None = None
    # SelfNodeV6MasqAddrForThisPeer is the IPv6 that this peer knows the current node as.
    # It may be empty if the peer knows the current node by its native
    # IPv6 address.
    # This field is only populated in a MapResponse for peers and not
    # for the current node.
    # 
    # If set, it should be used to masquerade traffic originating from the
    # current node to this peer. The masquerade address is only relevant
    # for this peer and not for other peers.
    # 
    # This only applies to traffic originating from the current node to the
    # peer or any of its subnets. Traffic originating from subnet routes will
    # not be masqueraded (e.g. in case of --snat-subnet-routes).
    self_node_v6_masq_addr_for_this_peer: str | None = None
    # IsWireGuardOnly indicates that this is a non-Tailscale WireGuard peer, it
    # is not expected to speak Disco or DERP, and it must have Endpoints in
    # order to be reachable.
    is_wire_guard_only: bool = False
    # IsJailed indicates that this node is jailed and should not be allowed
    # initiate connections, however outbound connections to it should still be
    # allowed.
    is_jailed: bool = False
    # ExitNodeDNSResolvers is the list of DNS servers that should be used when this
    # node is marked IsWireGuardOnly and being used as an exit node.
    exit_node_dns_resolvers: list[Resolver] = msgspec.field(default_factory=list, name="ExitNodeDNSResolvers")


class Hostinfo(msgspec.Struct, rename="pascal", omit_defaults=True):
    "Hostinfo contains a summary of a Tailscale host.\n\nBecause it contains pointers (slices), this type should not be used\nas a value type."

    # version of this code (in version.Long format)
    ipn_version: str = msgspec.field(default="", name="IPNVersion")
    # logtail ID of frontend instance
    frontend_log_id: str = msgspec.field(default="", name="FrontendLogID")
    # logtail ID of backend instance
    backend_log_id: str = msgspec.field(default="", name="BackendLogID")
    # operating system the client runs on (a version.OS value)
    os: str = msgspec.field(default="", name="OS")
    # OSVersion is the version of the OS, if available.
    # 
    # For Android, it's like "10", "11", "12", etc. For iOS and macOS it's like
    # "15.6.1" or "12.4.0". For Windows it's like "10.0.19044.1889". For
    # FreeBSD it's like "12.3-STABLE".
    # 
    # For Linux, prior to Tailscale 1.32, we jammed a bunch of fields into this
    # string on Linux, like "Debian 10.4; kernel=xxx; container; env=kn" and so
    # on. As of Tailscale 1.32, this is simply the kernel version on Linux, like
    # "5.10.0-17-amd64".
    os_version: str = msgspec.field(default="", name="OSVersion")
    # best-effort whether the client is running in a container
    container: bool | None = None
    # a hostinfo.EnvType in string form
    env: str = ""
    # "debian", "ubuntu", "nixos", ...
    distro: str = ""
    # "20.04", ...
    distro_version: str = ""
    # "jammy", "bullseye", ...
    distro_code_name: str = ""
    # App is used to disambiguate Tailscale clients that run using tsnet.
    app: str = ""
    # if a desktop was detected on Linux
    desktop: bool | None = None
    # Tailscale package to disambiguate ("choco", "appstore", etc; "" for unknown)
    package: str = ""
    # mobile phone model ("Pixel 3a", "iPhone12,3")
    device_model: str = ""
    # macOS/iOS APNs device token for notifications (and Android in the future)
    push_device_token: str = ""
    # name of the host the client runs on
    hostname: str = ""
    # indicates whether the host is blocking incoming connections
    shields_up: bool = False
    # indicates this node exists in netmap because it's owned by a shared-to user
    sharee_node: bool = False
    # indicates that the user has opted out of sending logs and support
    no_logs_no_support: bool = False
    # WireIngress indicates that the node would like to be wired up server-side
    # (DNS, etc) to be able to use Tailscale Funnel, even if it's not currently
    # enabled. For example, the user might only use it for intermittent
    # foreground CLI serve sessions, for which they'd like it to work right
    # away, even if it's disabled most of the time. As an optimization, this is
    # only sent if IngressEnabled is false, as IngressEnabled implies that this
    # option is true.
    wire_ingress: bool = False
    # if the node has any funnel endpoint enabled
    ingress_enabled: bool = False
    # indicates that the node has opted-in to admin-console-drive remote updates
    allows_update: bool = False
    # the current host's machine type (uname -m)
    machine: str = ""
    # GOARCH value (of the built binary)
    go_arch: str = ""
    # GOARM, GOAMD64, etc (of the built binary)
    go_arch_var: str = ""
    # Go version binary was built with
    go_version: str = ""
    # set of IP ranges this client can route
    routable_ips: list[str] = msgspec.field(default_factory=list, name="RoutableIPs")
    # set of ACL tags this node wants to claim
    request_tags: list[str] = []
    # MAC address(es) to send Wake-on-LAN packets to wake this node (lowercase hex w/ colons)
    wol_macs: list[str] = msgspec.field(default_factory=list, name="WoLMACs")
    # services advertised by this machine
    services: list[Service] = []
    net_info: NetInfo | None = None
    # if advertised
    ssh_host_keys: list[str] = msgspec.field(default_factory=list, name="sshHostKeys")
    cloud: str = ""
    # if the client is running in userspace (netstack) mode
    userspace: bool | None = None
    # if the client's subnet router is running in userspace (netstack) mode
    userspace_router: bool | None = None
    # if the client is running the app-connector service
    app_connector: bool | None = None
    # opaque hash of the most recent list of tailnet services, change in hash indicates config should be fetched via c2n
    services_hash: str = ""
    # the client’s selected exit node, empty when unselected.
    exit_node_id: str = msgspec.field(default="", name="ExitNodeID")
    # Location represents geographical location data about a
    # Tailscale host. Location is optional and only set if
    # explicitly declared by a node.
    location: Location | None = None
    # TPM device metadata, if available
    t_p_m: TPMInfo | None = None
    # StateEncrypted reports whether the node state is stored encrypted on
    # disk. The actual mechanism is platform-specific:
    #   * Apple nodes use the Keychain
    #   * Linux and Windows nodes use the TPM
    #   * Android apps use EncryptedSharedPreferences
    state_encrypted: bool | None = None


class NetInfo(msgspec.Struct, rename="pascal", omit_defaults=True):
    "NetInfo contains information about the host's network state."

    # MappingVariesByDestIP says whether the host's NAT mappings
    # vary based on the destination IP.
    mapping_varies_by_dest_ip: bool | None = msgspec.field(default=None, name="MappingVariesByDestIP")
    # WorkingIPv6 is whether the host has IPv6 internet connectivity.
    working_ipv6: bool | None = msgspec.field(default=None, name="WorkingIPv6")
    # OSHasIPv6 is whether the OS supports IPv6 at all, regardless of
    # whether IPv6 internet connectivity is available.
    os_has_ipv6: bool | None = msgspec.field(default=None, name="OSHasIPv6")
    # WorkingUDP is whether the host has UDP internet connectivity.
    working_udp: bool | None = msgspec.field(default=None, name="WorkingUDP")
    # WorkingICMPv4 is whether ICMPv4 works.
    # Empty means not checked.
    working_i_c_m_pv4: bool | None = None
    # HavePortMap is whether we have an existing portmap open
    # (UPnP, PMP, or PCP).
    have_port_map: bool = False
    # UPnP is whether UPnP appears present on the LAN.
    # Empty means not checked.
    upnp: bool | None = msgspec.field(default=None, name="UPnP")
    # PMP is whether NAT-PMP appears present on the LAN.
    # Empty means not checked.
    pmp: bool | None = msgspec.field(default=None, name="PMP")
    # PCP is whether PCP appears present on the LAN.
    # Empty means not checked.
    pcp: bool | None = msgspec.field(default=None, name="PCP")
    # PreferredDERP is this node's preferred (home) DERP region ID.
    # This is where the node expects to be contacted to begin a
    # peer-to-peer connection. The node might be be temporarily
    # connected to multiple DERP servers (to speak to other nodes
    # that are located elsewhere) but PreferredDERP is the region ID
    # that the node subscribes to traffic at.
    # Zero means disconnected or unknown.
    preferred_derp: int = msgspec.field(default=0, name="PreferredDERP")
    # LinkType is the current link type, if known.
    link_type: str = ""
    # DERPLatency is the fastest recent time to reach various
    # DERP STUN servers, in seconds. The map key is the
    # "regionID-v4" or "-v6"; it was previously the DERP server's
    # STUN host:port.
    # 
    # This should only be updated rarely, or when there's a
    # material change, as any change here also gets uploaded to
    # the control plane.
    derp_latency: dict[str, float] = msgspec.field(default_factory=dict, name="DERPLatency")
    # FirewallMode encodes both which firewall mode was selected and why.
    # It is Linux-specific (at least as of 2023-08-19) and is meant to help
    # debug iptables-vs-nftables issues. The string is of the form
    # "{nft,ift}-REASON", like "nft-forced" or "ipt-default". Empty means
    # either not Linux or a configuration in which the host firewall rules
    # are not managed by tailscaled.
    firewall_mode: str = ""


class Service(msgspec.Struct, rename="pascal", omit_defaults=True):
    "Service represents a service running on a node."

    # Proto is the type of service. It's usually the constant TCP
    # or UDP ("tcp" or "udp"), but it can also be one of the
    # following meta service values:
    # 
    #     * "peerapi4": peerapi is available on IPv4; Port is the
    #        port number that the peerapi is running on the
    #        node's Tailscale IPv4 address.
    #     * "peerapi6": peerapi is available on IPv6; Port is the
    #        port number that the peerapi is running on the
    #        node's Tailscale IPv6 address.
    #     * "peerapi-dns-proxy": the local peerapi service supports
    #        being a DNS proxy (when the node is an exit
    #        node). For this service, the Port number must only be 1.
    proto: str = ""
    # Port is the port number.
    # 
    # For Proto "peerapi-dns", it must be 1.
    port: int = 0
    # Description is the textual description of the service,
    # usually the process name that's running.
    description: str = ""


class Location(msgspec.Struct, rename="pascal", omit_defaults=True):
    "Location represents geographical location data about a\nTailscale host. Location is optional and only set if\nexplicitly declared by a node."

    # User friendly country name, with proper capitalization ("Canada")
    country: str = ""
    # ISO 3166-1 alpha-2 in upper case ("CA")
    country_code: str = ""
    # User friendly city name, with proper capitalization ("Squamish")
    city: str = ""
    # CityCode is a short code representing the city in upper case.
    # CityCode is used to disambiguate a city from another location
    # with the same city name. It uniquely identifies a particular
    # geographical location, within the tailnet.
    # IATA, ICAO or ISO 3166-2 codes are recommended ("YSE")
    city_code: str = ""
    # Latitude, Longitude are optional geographical coordinates of the node, in degrees.
    # No particular accuracy level is promised; the coordinates may simply be the center of the city or country.
    latitude: float = 0.0
    longitude: float = 0.0
    # Priority determines the order of use of an exit node when a
    # location based preference matches more than one exit node,
    # the node with the highest priority wins. Nodes of equal
    # probability may be selected arbitrarily.
    # 
    # A value of 0 means the exit node does not have a priority
    # preference. A negative int is not allowed.
    priority: int = 0


class TPMInfo(msgspec.Struct, rename="pascal", omit_defaults=True):
    "TPMInfo contains information about a TPM 2.0 device present on a node.\nAll fields are read from TPM_CAP_TPM_PROPERTIES, see Part 2, section 6.13 of\nhttps://trustedcomputinggroup.org/resource/tpm-library-specification/."

    # Manufacturer is a 4-letter code from section 4.1 of
    # https://trustedcomputinggroup.org/resource/vendor-id-registry/,
    # for example "MSFT" for Microsoft.
    # Read from TPM_PT_MANUFACTURER.
    manufacturer: str = ""
    # Vendor is a vendor ID string, up to 16 characters.
    # Read from TPM_PT_VENDOR_STRING_*.
    vendor: str = ""
    # Model is a vendor-defined TPM model.
    # Read from TPM_PT_VENDOR_TPM_TYPE.
    model: int = 0
    # FirmwareVersion is the version number of the firmware.
    # Read from TPM_PT_FIRMWARE_VERSION_*.
    firmware_version: int = 0
    # SpecRevision is the TPM 2.0 spec revision encoded as a single number. All
    # revisions can be found at
    # https://trustedcomputinggroup.org/resource/tpm-library-specification/.
    # Before revision 184, TCG used the "01.83" format for revision 183.
    spec_revision: int = 0
    # FamilyIndicator is the TPM spec family, like "2.0".
    # Read from TPM_PT_FAMILY_INDICATOR.
    family_indicator: str = ""


class ClientVersion(msgspec.Struct, rename="pascal", omit_defaults=True):
    "ClientVersion is information about the latest client version that's available\nfor the client (and whether they're already running it).\n\nIt does not include a URL to download the client, as that varies by platform."

    # RunningLatest is true if the client is running the latest build.
    running_latest: bool = False
    # LatestVersion is the latest version.Short ("1.34.2") version available
    # for download for the client's platform and packaging type.
    # It won't be populated if RunningLatest is true.
    latest_version: str = ""
    # UrgentSecurityUpdate is set when the client is missing an important
    # security update. That update may be in LatestVersion or earlier.
    # UrgentSecurityUpdate should not be set if RunningLatest is false.
    urgent_security_update: bool = False
    # Notify is whether the client should do an OS-specific notification about
    # a new version being available. This should not be populated if
    # RunningLatest is true. The client should not notify multiple times for
    # the same LatestVersion value.
    notify: bool = False
    # NotifyURL is a URL to open in the browser when the user clicks on the
    # notification, when Notify is true.
    notify_url: str = msgspec.field(default="", name="NotifyURL")
    # NotifyText is the text to show in the notification, when Notify is true.
    notify_text: str = ""


class DERPMap(msgspec.Struct, rename="pascal", omit_defaults=True):
    "DERPMap describes the set of DERP packet relay servers that are available."

    # HomeParams, if non-nil, is a change in home parameters.
    # 
    # The rest of the DEPRMap fields, if zero, means unchanged.
    home_params: DERPHomeParams | None = None
    # Regions is the set of geographic regions running DERP node(s).
    # 
    # It's keyed by the DERPRegion.RegionID.
    # 
    # The numbers are not necessarily contiguous.
    regions: dict[str, DERPRegion] | None = None
    # OmitDefaultRegions specifies to not use Tailscale's DERP servers, and only use those
    # specified in this DERPMap. If there are none set outside of the defaults, this is a noop.
    # 
    # This field is only meaningful if the Regions map is non-nil (indicating a change).
    omit_default_regions: bool = msgspec.field(default=False, name="omitDefaultRegions")


class DERPRegion(msgspec.Struct, rename="pascal", omit_defaults=True):
    "DERPRegion is a geographic region running DERP relay node(s).\n\nClient nodes discover which region they're closest to, advertise\nthat \"home\" DERP region (previously called \"home node\", when there\nwas only 1 node per region) and maintain a persistent connection\nthat region as long as it's the closest. Client nodes will further\nconnect to other regions as necessary to communicate with peers\nadvertising other regions as their homes."

    # RegionID is a unique integer for a geographic region.
    # 
    # It corresponds to the legacy derpN.tailscale.com hostnames
    # used by older clients. (Older clients will continue to resolve
    # derpN.tailscale.com when contacting peers, rather than use
    # the server-provided DERPMap)
    # 
    # RegionIDs must be non-zero, positive, and guaranteed to fit
    # in a JavaScript number.
    # 
    # RegionIDs in range 900-999 are reserved for end users to run their
    # own DERP nodes.
    region_id: int = msgspec.field(default=0, name="RegionID")
    # RegionCode is a short name for the region. It's usually a popular
    # city or airport code in the region: "nyc", "sf", "sin",
    # "fra", etc.
    region_code: str = ""
    # RegionName is a long English name for the region: "New York City",
    # "San Francisco", "Singapore", "Frankfurt", etc.
    region_name: str = ""
    # Latitude, Longitude are optional geographical coordinates of the DERP region's city, in degrees.
    latitude: float = 0.0
    longitude: float = 0.0
    # Avoid is whether the client should avoid picking this as its home region.
    # The region should only be used if a peer is there. Clients already using
    # this region as their home should migrate away to a new region without
    # Avoid set.
    # 
    # Deprecated: because of bugs in past implementations combined with unclear
    # docs that caused people to think the bugs were intentional, this field is
    # deprecated. It was never supposed to cause STUN/DERP measurement probes,
    # but due to bugs, it sometimes did. And then some parts of the code began
    # to rely on that property. But then we were unable to use this field for
    # its original purpose, nor its later imagined purpose, because various
    # parts of the codebase thought it meant one thing and others thought it
    # meant another. But it did something in the middle instead. So we're retiring
    # it. Use NoMeasureNoHome instead.
    avoid: bool = False
    # NoMeasureNoHome says that this regions should not be measured for its
    # latency distance (STUN, HTTPS, etc) or availability (e.g. captive portal
    # checks) and should never be selected as the node's home region. However,
    # if a peer declares this region as its home, then this client is allowed
    # to connect to it for the purpose of communicating with that peer.
    # 
    # This is what the now deprecated Avoid bool was supposed to mean
    # originally but had implementation bugs and documentation omissions.
    no_measure_no_home: bool = False
    # Nodes are the DERP nodes running in this region, in
    # priority order for the current client. Client TLS
    # connections should ideally only go to the first entry
    # (falling back to the second if necessary). STUN packets
    # should go to the first 1 or 2.
    # 
    # If nodes within a region route packets amongst themselves,
    # but not to other regions. That said, each user/domain
    # should get a the same preferred node order, so if all nodes
    # for a user/network pick the first one (as they should, when
    # things are healthy), the inter-cluster routing is minimal
    # to zero.
    nodes: list[DERPNode] | None = None


class DERPNode(msgspec.Struct, rename="pascal", omit_defaults=True):
    "DERPNode describes a DERP packet relay node running within a DERPRegion."

    # Name is a unique node name (across all regions).
    # It is not a host name.
    # It's typically of the form "1b", "2a", "3b", etc. (region
    # ID + suffix within that region)
    name: str = ""
    # RegionID is the RegionID of the DERPRegion that this node
    # is running in.
    region_id: int = msgspec.field(default=0, name="RegionID")
    # HostName is the DERP node's hostname.
    # 
    # It is required but need not be unique; multiple nodes may
    # have the same HostName but vary in configuration otherwise.
    host_name: str = ""
    # CertName optionally specifies the expected TLS cert common
    # name. If empty, HostName is used. If CertName is non-empty,
    # HostName is only used for the TCP dial (if IPv4/IPv6 are
    # not present) + TLS ClientHello.
    # 
    # As a special case, if CertName starts with "sha256-raw:",
    # then the rest of the string is a hex-encoded SHA256 of the
    # cert to expect. This is used for self-signed certs.
    # In this case, the HostName field will typically be an IP
    # address literal.
    cert_name: str = ""
    # IPv4 optionally forces an IPv4 address to use, instead of using DNS.
    # If empty, A record(s) from DNS lookups of HostName are used.
    # If the string is not an IPv4 address, IPv4 is not used; the
    # conventional string to disable IPv4 (and not use DNS) is
    # "none".
    ipv4: str = msgspec.field(default="", name="IPv4")
    # IPv6 optionally forces an IPv6 address to use, instead of using DNS.
    # If empty, AAAA record(s) from DNS lookups of HostName are used.
    # If the string is not an IPv6 address, IPv6 is not used; the
    # conventional string to disable IPv6 (and not use DNS) is
    # "none".
    ipv6: str = msgspec.field(default="", name="IPv6")
    # Port optionally specifies a STUN port to use.
    # Zero means 3478.
    # To disable STUN on this node, use -1.
    stun_port: int = msgspec.field(default=0, name="STUNPort")
    # STUNOnly marks a node as only a STUN server and not a DERP
    # server.
    stun_only: bool = msgspec.field(default=False, name="STUNOnly")
    # DERPPort optionally provides an alternate TLS port number
    # for the DERP HTTPS server.
    # 
    # If zero, 443 is used.
    derp_port: int = msgspec.field(default=0, name="DERPPort")
    # InsecureForTests is used by unit tests to disable TLS verification.
    # It should not be set by users.
    insecure_for_tests: bool = False
    # STUNTestIP is used in tests to override the STUN server's IP.
    # If empty, it's assumed to be the same as the DERP server.
    stun_test_ip: str = msgspec.field(default="", name="STUNTestIP")
    # CanPort80 specifies whether this DERP node is accessible over HTTP
    # on port 80 specifically. This is used for captive portal checks.
    can_port80: bool = False


class DERPHomeParams(msgspec.Struct, rename="pascal", omit_defaults=True):
    "DERPHomeParams contains parameters from the server related to selecting a\nDERP home region (sometimes referred to as the \"preferred DERP\")."

    # RegionScore scales latencies of DERP regions by a given scaling
    # factor when determining which region to use as the home
    # ("preferred") DERP. Scores in the range (0, 1) will cause this
    # region to be proportionally more preferred, and scores in the range
    # (1, ∞) will penalize a region.
    # 
    # If a region is not present in this map, it is treated as having a
    # score of 1.0.
    # 
    # Scores should not be 0 or negative; such scores will be ignored.
    # 
    # A nil map means no change from the previous value (if any); an empty
    # non-nil map can be sent to reset all scores back to 1.0.
    region_score: dict[str, float] = {}


class VIPService(msgspec.Struct, rename="pascal"):
    "VIPService represents a service created on a tailnet from the\nperspective of a node providing that service. These services\nhave an virtual IP (VIP) address pair distinct from the node's IPs."

    # Name is the name of the service. The Name uniquely identifies a service
    # on a particular tailnet, and so also corresponds uniquely to the pair of
    # IP addresses belonging to the VIP service.
    name: str = ""
    # Ports specify which ProtoPorts are made available by this node
    # on the service's IPs.
    ports: list[ProtoPortRange] | None = None
    # Active specifies whether new requests for the service should be
    # sent to this node by control.
    active: bool = False


class PortRange(msgspec.Struct, rename="pascal"):
    "PortRange represents a range of UDP or TCP port numbers."

    first: int = 0
    last: int = 0


class ProtoPortRange(msgspec.Struct, rename="pascal"):
    "ProtoPortRange is used to encode \"proto:port\" format.\nThe following formats are supported:\n\n    \"*\" allows all TCP, UDP and ICMP traffic on all ports.\n    \"<ports>\" allows all TCP, UDP and ICMP traffic on the specified ports.\n    \"proto:*\" allows traffic of the specified proto on all ports.\n    \"proto:<port>\" allows traffic of the specified proto on the specified port.\n\nPorts are either a single port number or a range of ports (e.g. \"80-90\").\nString named protocols support names that ipproto.Proto accepts."

    # Proto is the IP protocol number.
    # If Proto is 0, it means TCP+UDP+ICMP(4+6).
    proto: int = 0
    ports: PortRange | None = None


class Prefs(msgspec.Struct, rename="pascal", omit_defaults=True):
    "Prefs are the user modifiable settings of the Tailscale node agent.\nWhen you add a Pref to this struct, remember to add a corresponding\nfield in MaskedPrefs, and check your field for equality in Prefs.Equals()."

    # ControlURL is the URL of the control server to use.
    # 
    # If empty, the default for new installs, DefaultControlURL
    # is used. It's set non-empty once the daemon has been started
    # for the first time.
    # 
    # TODO(apenwarr): Make it safe to update this with EditPrefs().
    # Right now, you have to pass it in the initial prefs in Start(),
    # which is the only code that actually uses the ControlURL value.
    # It would be more consistent to restart controlclient
    # automatically whenever this variable changes.
    # 
    # Meanwhile, you have to provide this as part of
    # Options.LegacyMigrationPrefs or Options.UpdatePrefs when
    # calling Backend.Start().
    control_url: str = msgspec.field(default="", name="ControlURL")
    # RouteAll specifies whether to accept subnets advertised by
    # other nodes on the Tailscale network. Note that this does not
    # include default routes (0.0.0.0/0 and ::/0), those are
    # controlled by ExitNodeID/IP below.
    route_all: bool = False
    # ExitNodeID and ExitNodeIP specify the node that should be used
    # as an exit node for internet traffic. At most one of these
    # should be non-zero.
    # 
    # The preferred way to express the chosen node is ExitNodeID, but
    # in some cases it's not possible to use that ID (e.g. in the
    # linux CLI, before tailscaled has a netmap). For those
    # situations, we allow specifying the exit node by IP, and
    # ipnlocal.LocalBackend will translate the IP into an ID when the
    # node is found in the netmap.
    # 
    # If the selected exit node doesn't exist (e.g. it's not part of
    # the current tailnet), or it doesn't offer exit node services, a
    # blackhole route will be installed on the local system to
    # prevent any traffic escaping to the local network.
    exit_node_id: str = msgspec.field(default="", name="ExitNodeID")
    exit_node_ip: str = msgspec.field(default="", name="ExitNodeIP")
    # AutoExitNode is an optional expression that specifies whether and how
    # tailscaled should pick an exit node automatically.
    # 
    # If specified, tailscaled will use an exit node based on the expression,
    # and will re-evaluate the selection periodically as network conditions,
    # available exit nodes, or policy settings change. A blackhole route will
    # be installed to prevent traffic from escaping to the local network until
    # an exit node is selected. It takes precedence over ExitNodeID and ExitNodeIP.
    # 
    # If empty, tailscaled will not automatically select an exit node.
    # 
    # If the specified expression is invalid or unsupported by the client,
    # it falls back to the behavior of [AnyExitNode].
    # 
    # As of 2025-07-02, the only supported value is [AnyExitNode].
    # It's a string rather than a boolean to allow future extensibility
    # (e.g., AutoExitNode = "mullvad" or AutoExitNode = "geo:us").
    auto_exit_node: str = ""
    # InternalExitNodePrior is the most recently used ExitNodeID in string form. It is set by
    # the backend on transition from exit node on to off and used by the
    # backend.
    # 
    # As an Internal field, it can't be set by LocalAPI clients, rather it is set indirectly
    # when the ExitNodeID value is zero'd and via the set-use-exit-node-enabled endpoint.
    internal_exit_node_prior: str = ""
    # ExitNodeAllowLANAccess indicates whether locally accessible subnets should be
    # routed directly or via the exit node.
    exit_node_allow_lan_access: bool = msgspec.field(default=False, name="ExitNodeAllowLANAccess")
    # CorpDNS specifies whether to install the Tailscale network's
    # DNS configuration, if it exists.
    corp_dns: bool = msgspec.field(default=False, name="CorpDNS")
    # RunSSH bool is whether this node should run an SSH
    # server, permitting access to peers according to the
    # policies as configured by the Tailnet's admin(s).
    run_ssh: bool = msgspec.field(default=False, name="RunSSH")
    # RunWebClient bool is whether this node should expose
    # its web client over Tailscale at port 5252,
    # permitting access to peers according to the
    # policies as configured by the Tailnet's admin(s).
    run_web_client: bool = False
    # WantRunning indicates whether networking should be active on
    # this node.
    want_running: bool = False
    # LoggedOut indicates whether the user intends to be logged out.
    # There are other reasons we may be logged out, including no valid
    # keys.
    # We need to remember this state so that, on next startup, we can
    # generate the "Login" vs "Connect" buttons correctly, without having
    # to contact the server to confirm our nodekey status first.
    logged_out: bool = False
    # ShieldsUp indicates whether to block all incoming connections,
    # regardless of the control-provided packet filter. If false, we
    # use the packet filter as provided. If true, we block incoming
    # connections. This overrides tailcfg.Hostinfo's ShieldsUp.
    shields_up: bool = False
    # AdvertiseTags specifies tags that should be applied to this node, for
    # purposes of ACL enforcement. These can be referenced from the ACL policy
    # document. Note that advertising a tag on the client doesn't guarantee
    # that the control server will allow the node to adopt that tag.
    advertise_tags: list[str] | None = None
    # Hostname is the hostname to use for identifying the node. If
    # not set, os.Hostname is used.
    hostname: str = ""
    # NotepadURLs is a debugging setting that opens OAuth URLs in
    # notepad.exe on Windows, rather than loading them in a browser.
    # 
    # apenwarr 2020-04-29: Unfortunately this is still needed sometimes.
    # Windows' default browser setting is sometimes screwy and this helps
    # users narrow it down a bit.
    notepad_urls: bool = msgspec.field(default=False, name="NotepadURLs")
    # ForceDaemon specifies whether a platform that normally
    # operates in "client mode" (that is, requires an active user
    # logged in with the GUI app running) should keep running after the
    # GUI ends and/or the user logs out.
    # 
    # The only current applicable platform is Windows. This
    # forced Windows to go into "server mode" where Tailscale is
    # running even with no users logged in. This might also be
    # used for macOS in the future. This setting has no effect
    # for Linux/etc, which always operate in daemon mode.
    force_daemon: bool = False
    # Egg is a optional debug flag.
    egg: bool = False
    # AdvertiseRoutes specifies CIDR prefixes to advertise into the
    # Tailscale network as reachable through the current
    # node.
    advertise_routes: list[str] | None = None
    # AdvertiseServices specifies the list of services that this
    # node can serve as a destination for. Note that an advertised
    # service must still go through the approval process from the
    # control server.
    advertise_services: list[str] | None = None
    # Sync is whether this node should sync its configuration from
    # the control plane. If unset, this defaults to true.
    # This exists primarily for testing, to verify that netmap caching
    # and offline operation work correctly.
    sync: bool | None = None
    # NoSNAT specifies whether to source NAT traffic going to
    # destinations in AdvertiseRoutes. The default is to apply source
    # NAT, which makes the traffic appear to come from the router
    # machine rather than the peer's Tailscale IP.
    # 
    # Disabling SNAT requires additional manual configuration in your
    # network to route Tailscale traffic back to the subnet relay
    # machine.
    # 
    # Linux-only.
    no_snat: bool = msgspec.field(default=False, name="NoSNAT")
    # NoStatefulFiltering specifies whether to apply stateful filtering when
    # advertising routes in AdvertiseRoutes. The default is to not apply
    # stateful filtering.
    # 
    # To allow inbound connections from advertised routes, both NoSNAT and
    # NoStatefulFiltering must be true.
    # 
    # This is an opt.Bool because it was first added after NoSNAT, with a
    # backfill based on the value of that parameter. The backfill has been
    # removed since then, but the field remains an opt.Bool.
    # 
    # Linux-only.
    no_stateful_filtering: bool | None = None
    # NetfilterMode specifies how much to manage netfilter rules for
    # Tailscale, if at all.
    netfilter_mode: int = 0
    # OperatorUser is the local machine user name who is allowed to
    # operate tailscaled without being root or using sudo.
    operator_user: str = ""
    # ProfileName is the desired name of the profile. If empty, then the user's
    # LoginName is used. It is only used for display purposes in the client UI
    # and CLI.
    profile_name: str = ""
    # AutoUpdate sets the auto-update preferences for the node agent. See
    # AutoUpdatePrefs docs for more details.
    auto_update: AutoUpdatePrefs | None = None
    # AppConnector sets the app connector preferences for the node agent. See
    # AppConnectorPrefs docs for more details.
    app_connector: AppConnectorPrefs | None = None
    # PostureChecking enables the collection of information used for device
    # posture checks.
    # 
    # Note: this should be named ReportPosture, but it was shipped as
    # PostureChecking in some early releases and this JSON field is written to
    # disk, so we just keep its old name. (akin to CorpDNS which is an internal
    # pref name that doesn't match the public interface)
    posture_checking: bool = False
    # NetfilterKind specifies what netfilter implementation to use.
    # 
    # It can be "iptables", "nftables", or "" to auto-detect.
    # 
    # Linux-only.
    netfilter_kind: str = ""
    # DriveShares are the configured DriveShares, stored in increasing order
    # by name.
    drive_shares: list[Any] | None = None
    # RelayServerPort is the UDP port number for the relay server to bind to,
    # on all interfaces. A non-nil zero value signifies a random unused port
    # should be used. A nil value signifies relay server functionality
    # should be disabled.
    relay_server_port: int | None = None
    # RelayServerStaticEndpoints are static IP:port endpoints to advertise as
    # candidates for relay connections. Only relevant when RelayServerPort is
    # non-nil.
    relay_server_static_endpoints: list[str] = []
    # AllowSingleHosts was a legacy field that was always true
    # for the past 4.5 years. It controlled whether Tailscale
    # peers got /32 or /128 routes for each other.
    # As of 2024-05-17 we're starting to ignore it, but to let
    # people still downgrade Tailscale versions and not break
    # all peer-to-peer networking we still write it to disk (as JSON)
    # so it can be loaded back by old versions.
    # TODO(bradfitz): delete this in 2025 sometime. See #12058.
    allow_single_hosts: Any = None
    # The Persist field is named 'Config' in the file for backward
    # compatibility with earlier versions.
    # TODO(apenwarr): We should move this out of here, it's not a pref.
    #  We can maybe do that once we're sure which module should persist
    #  it (backend or frontend?)
    persist: Any | None = msgspec.field(default=None, name="Config")


class MaskedPrefs(msgspec.Struct, rename="pascal", omit_defaults=True):
    "MaskedPrefs is a Prefs with an associated bitmask of which fields are set.\n\nEach FooSet field maps to a corresponding Foo field in Prefs. FooSet can be\na struct, in which case inner fields of FooSet map to inner fields of Foo in\nPrefs (see AutoUpdateSet for example)."

    # ControlURL is the URL of the control server to use.
    # 
    # If empty, the default for new installs, DefaultControlURL
    # is used. It's set non-empty once the daemon has been started
    # for the first time.
    # 
    # TODO(apenwarr): Make it safe to update this with EditPrefs().
    # Right now, you have to pass it in the initial prefs in Start(),
    # which is the only code that actually uses the ControlURL value.
    # It would be more consistent to restart controlclient
    # automatically whenever this variable changes.
    # 
    # Meanwhile, you have to provide this as part of
    # Options.LegacyMigrationPrefs or Options.UpdatePrefs when
    # calling Backend.Start().
    control_url: str = msgspec.field(default="", name="ControlURL")
    # RouteAll specifies whether to accept subnets advertised by
    # other nodes on the Tailscale network. Note that this does not
    # include default routes (0.0.0.0/0 and ::/0), those are
    # controlled by ExitNodeID/IP below.
    route_all: bool = False
    # ExitNodeID and ExitNodeIP specify the node that should be used
    # as an exit node for internet traffic. At most one of these
    # should be non-zero.
    # 
    # The preferred way to express the chosen node is ExitNodeID, but
    # in some cases it's not possible to use that ID (e.g. in the
    # linux CLI, before tailscaled has a netmap). For those
    # situations, we allow specifying the exit node by IP, and
    # ipnlocal.LocalBackend will translate the IP into an ID when the
    # node is found in the netmap.
    # 
    # If the selected exit node doesn't exist (e.g. it's not part of
    # the current tailnet), or it doesn't offer exit node services, a
    # blackhole route will be installed on the local system to
    # prevent any traffic escaping to the local network.
    exit_node_id: str = msgspec.field(default="", name="ExitNodeID")
    exit_node_ip: str = msgspec.field(default="", name="ExitNodeIP")
    # AutoExitNode is an optional expression that specifies whether and how
    # tailscaled should pick an exit node automatically.
    # 
    # If specified, tailscaled will use an exit node based on the expression,
    # and will re-evaluate the selection periodically as network conditions,
    # available exit nodes, or policy settings change. A blackhole route will
    # be installed to prevent traffic from escaping to the local network until
    # an exit node is selected. It takes precedence over ExitNodeID and ExitNodeIP.
    # 
    # If empty, tailscaled will not automatically select an exit node.
    # 
    # If the specified expression is invalid or unsupported by the client,
    # it falls back to the behavior of [AnyExitNode].
    # 
    # As of 2025-07-02, the only supported value is [AnyExitNode].
    # It's a string rather than a boolean to allow future extensibility
    # (e.g., AutoExitNode = "mullvad" or AutoExitNode = "geo:us").
    auto_exit_node: str = ""
    # InternalExitNodePrior is the most recently used ExitNodeID in string form. It is set by
    # the backend on transition from exit node on to off and used by the
    # backend.
    # 
    # As an Internal field, it can't be set by LocalAPI clients, rather it is set indirectly
    # when the ExitNodeID value is zero'd and via the set-use-exit-node-enabled endpoint.
    internal_exit_node_prior: str = ""
    # ExitNodeAllowLANAccess indicates whether locally accessible subnets should be
    # routed directly or via the exit node.
    exit_node_allow_lan_access: bool = msgspec.field(default=False, name="ExitNodeAllowLANAccess")
    # CorpDNS specifies whether to install the Tailscale network's
    # DNS configuration, if it exists.
    corp_dns: bool = msgspec.field(default=False, name="CorpDNS")
    # RunSSH bool is whether this node should run an SSH
    # server, permitting access to peers according to the
    # policies as configured by the Tailnet's admin(s).
    run_ssh: bool = msgspec.field(default=False, name="RunSSH")
    # RunWebClient bool is whether this node should expose
    # its web client over Tailscale at port 5252,
    # permitting access to peers according to the
    # policies as configured by the Tailnet's admin(s).
    run_web_client: bool = False
    # WantRunning indicates whether networking should be active on
    # this node.
    want_running: bool = False
    # LoggedOut indicates whether the user intends to be logged out.
    # There are other reasons we may be logged out, including no valid
    # keys.
    # We need to remember this state so that, on next startup, we can
    # generate the "Login" vs "Connect" buttons correctly, without having
    # to contact the server to confirm our nodekey status first.
    logged_out: bool = False
    # ShieldsUp indicates whether to block all incoming connections,
    # regardless of the control-provided packet filter. If false, we
    # use the packet filter as provided. If true, we block incoming
    # connections. This overrides tailcfg.Hostinfo's ShieldsUp.
    shields_up: bool = False
    # AdvertiseTags specifies tags that should be applied to this node, for
    # purposes of ACL enforcement. These can be referenced from the ACL policy
    # document. Note that advertising a tag on the client doesn't guarantee
    # that the control server will allow the node to adopt that tag.
    advertise_tags: list[str] | None = None
    # Hostname is the hostname to use for identifying the node. If
    # not set, os.Hostname is used.
    hostname: str = ""
    # NotepadURLs is a debugging setting that opens OAuth URLs in
    # notepad.exe on Windows, rather than loading them in a browser.
    # 
    # apenwarr 2020-04-29: Unfortunately this is still needed sometimes.
    # Windows' default browser setting is sometimes screwy and this helps
    # users narrow it down a bit.
    notepad_urls: bool = msgspec.field(default=False, name="NotepadURLs")
    # ForceDaemon specifies whether a platform that normally
    # operates in "client mode" (that is, requires an active user
    # logged in with the GUI app running) should keep running after the
    # GUI ends and/or the user logs out.
    # 
    # The only current applicable platform is Windows. This
    # forced Windows to go into "server mode" where Tailscale is
    # running even with no users logged in. This might also be
    # used for macOS in the future. This setting has no effect
    # for Linux/etc, which always operate in daemon mode.
    force_daemon: bool = False
    # Egg is a optional debug flag.
    egg: bool = False
    # AdvertiseRoutes specifies CIDR prefixes to advertise into the
    # Tailscale network as reachable through the current
    # node.
    advertise_routes: list[str] | None = None
    # AdvertiseServices specifies the list of services that this
    # node can serve as a destination for. Note that an advertised
    # service must still go through the approval process from the
    # control server.
    advertise_services: list[str] | None = None
    # Sync is whether this node should sync its configuration from
    # the control plane. If unset, this defaults to true.
    # This exists primarily for testing, to verify that netmap caching
    # and offline operation work correctly.
    sync: bool | None = None
    # NoSNAT specifies whether to source NAT traffic going to
    # destinations in AdvertiseRoutes. The default is to apply source
    # NAT, which makes the traffic appear to come from the router
    # machine rather than the peer's Tailscale IP.
    # 
    # Disabling SNAT requires additional manual configuration in your
    # network to route Tailscale traffic back to the subnet relay
    # machine.
    # 
    # Linux-only.
    no_snat: bool = msgspec.field(default=False, name="NoSNAT")
    # NoStatefulFiltering specifies whether to apply stateful filtering when
    # advertising routes in AdvertiseRoutes. The default is to not apply
    # stateful filtering.
    # 
    # To allow inbound connections from advertised routes, both NoSNAT and
    # NoStatefulFiltering must be true.
    # 
    # This is an opt.Bool because it was first added after NoSNAT, with a
    # backfill based on the value of that parameter. The backfill has been
    # removed since then, but the field remains an opt.Bool.
    # 
    # Linux-only.
    no_stateful_filtering: bool | None = None
    # NetfilterMode specifies how much to manage netfilter rules for
    # Tailscale, if at all.
    netfilter_mode: int = 0
    # OperatorUser is the local machine user name who is allowed to
    # operate tailscaled without being root or using sudo.
    operator_user: str = ""
    # ProfileName is the desired name of the profile. If empty, then the user's
    # LoginName is used. It is only used for display purposes in the client UI
    # and CLI.
    profile_name: str = ""
    # AutoUpdate sets the auto-update preferences for the node agent. See
    # AutoUpdatePrefs docs for more details.
    auto_update: AutoUpdatePrefs | None = None
    # AppConnector sets the app connector preferences for the node agent. See
    # AppConnectorPrefs docs for more details.
    app_connector: AppConnectorPrefs | None = None
    # PostureChecking enables the collection of information used for device
    # posture checks.
    # 
    # Note: this should be named ReportPosture, but it was shipped as
    # PostureChecking in some early releases and this JSON field is written to
    # disk, so we just keep its old name. (akin to CorpDNS which is an internal
    # pref name that doesn't match the public interface)
    posture_checking: bool = False
    # NetfilterKind specifies what netfilter implementation to use.
    # 
    # It can be "iptables", "nftables", or "" to auto-detect.
    # 
    # Linux-only.
    netfilter_kind: str = ""
    # DriveShares are the configured DriveShares, stored in increasing order
    # by name.
    drive_shares: list[Any] | None = None
    # RelayServerPort is the UDP port number for the relay server to bind to,
    # on all interfaces. A non-nil zero value signifies a random unused port
    # should be used. A nil value signifies relay server functionality
    # should be disabled.
    relay_server_port: int | None = None
    # RelayServerStaticEndpoints are static IP:port endpoints to advertise as
    # candidates for relay connections. Only relevant when RelayServerPort is
    # non-nil.
    relay_server_static_endpoints: list[str] = []
    # AllowSingleHosts was a legacy field that was always true
    # for the past 4.5 years. It controlled whether Tailscale
    # peers got /32 or /128 routes for each other.
    # As of 2024-05-17 we're starting to ignore it, but to let
    # people still downgrade Tailscale versions and not break
    # all peer-to-peer networking we still write it to disk (as JSON)
    # so it can be loaded back by old versions.
    # TODO(bradfitz): delete this in 2025 sometime. See #12058.
    allow_single_hosts: Any = None
    # The Persist field is named 'Config' in the file for backward
    # compatibility with earlier versions.
    # TODO(apenwarr): We should move this out of here, it's not a pref.
    #  We can maybe do that once we're sure which module should persist
    #  it (backend or frontend?)
    persist: Any | None = msgspec.field(default=None, name="Config")
    control_url_set: bool = msgspec.field(default=False, name="ControlURLSet")
    route_all_set: bool = False
    exit_node_id_set: bool = msgspec.field(default=False, name="ExitNodeIDSet")
    exit_node_ip_set: bool = msgspec.field(default=False, name="ExitNodeIPSet")
    auto_exit_node_set: bool = False
    # Internal; can't be set by LocalAPI clients
    internal_exit_node_prior_set: bool = False
    exit_node_allow_lan_access_set: bool = msgspec.field(default=False, name="ExitNodeAllowLANAccessSet")
    corp_dns_set: bool = msgspec.field(default=False, name="CorpDNSSet")
    run_ssh_set: bool = msgspec.field(default=False, name="RunSSHSet")
    run_web_client_set: bool = False
    want_running_set: bool = False
    logged_out_set: bool = False
    shields_up_set: bool = False
    advertise_tags_set: bool = False
    hostname_set: bool = False
    notepad_urls_set: bool = msgspec.field(default=False, name="NotepadURLsSet")
    force_daemon_set: bool = False
    egg_set: bool = False
    advertise_routes_set: bool = False
    advertise_services_set: bool = False
    sync_set: bool = False
    no_snat_set: bool = msgspec.field(default=False, name="NoSNATSet")
    no_stateful_filtering_set: bool = False
    netfilter_mode_set: bool = False
    operator_user_set: bool = False
    profile_name_set: bool = False
    auto_update_set: AutoUpdatePrefsMask | None = None
    app_connector_set: bool = False
    posture_checking_set: bool = False
    netfilter_kind_set: bool = False
    drive_shares_set: bool = False
    relay_server_port_set: bool = False
    relay_server_static_endpoints_set: bool = False


class AutoUpdatePrefs(msgspec.Struct, rename="pascal"):
    "AutoUpdatePrefs are the auto update settings for the node agent."

    # Check specifies whether background checks for updates are enabled. When
    # enabled, tailscaled will periodically check for available updates and
    # notify the user about them.
    check: bool = False
    # Apply specifies whether background auto-updates are enabled. When
    # enabled, tailscaled will apply available updates in the background.
    # Check must also be set when Apply is set.
    apply: bool | None = None


class AppConnectorPrefs(msgspec.Struct, rename="pascal"):
    "AppConnectorPrefs are the app connector settings for the node agent."

    # Advertise specifies whether the app connector subsystem is advertising
    # this node as a connector.
    advertise: bool = False


class Notify(msgspec.Struct, rename="pascal", omit_defaults=True):
    "Notify is a communication from a backend (e.g. tailscaled) to a frontend\n(cmd/tailscale, iOS, macOS, Win Tasktray).\nIn any given notification, any or all of these may be nil, meaning\nthat they have not changed.\nThey are JSON-encoded on the wire, despite the lack of struct tags."

    # version number of IPN backend
    version: str = ""
    # SessionID identifies the unique WatchIPNBus session.
    # This field is only set in the first message when requesting
    # NotifyInitialState. Clients must store it on their side as
    # following notifications will not include this field.
    session_id: str = msgspec.field(default="", name="SessionID")
    # ErrMessage, if non-nil, contains a critical error message.
    # For State InUseOtherUser, ErrMessage is not critical and just contains the details.
    err_message: str | None = None
    # non-nil when/if the login process succeeded
    login_finished: Any | None = None
    # if non-nil, the new or current IPN state
    state: int | None = None
    # if non-nil && Valid, the new or current preferences
    prefs: Prefs | None = None
    # if non-nil, the new or current netmap
    net_map: Any | None = None
    # if non-nil, the new or current wireguard stats
    engine: EngineStatus | None = None
    # if non-nil, UI should open a browser right now
    browse_to_url: str | None = msgspec.field(default=None, name="BrowseToURL")
    # FilesWaiting if non-nil means that files are buffered in
    # the Tailscale daemon and ready for local transfer to the
    # user's preferred storage location.
    # 
    # Deprecated: use LocalClient.AwaitWaitingFiles instead.
    files_waiting: Any | None = None
    # IncomingFiles, if non-nil, specifies which files are in the
    # process of being received. A nil IncomingFiles means this
    # Notify should not update the state of file transfers. A non-nil
    # but empty IncomingFiles means that no files are in the middle
    # of being transferred.
    # 
    # Deprecated: use LocalClient.AwaitWaitingFiles instead.
    incoming_files: list[PartialFile] = []
    # OutgoingFiles, if non-nil, tracks which files are in the process of
    # being sent via TailDrop, including files that finished, whether
    # successful or failed. This slice is sorted by Started time, then Name.
    outgoing_files: list[OutgoingFile] = []
    # LocalTCPPort, if non-nil, informs the UI frontend which
    # (non-zero) localhost TCP port it's listening on.
    # This is currently only used by Tailscale when run in the
    # macOS Network Extension.
    local_tcp_port: int | None = msgspec.field(default=None, name="LocalTCPPort")
    # ClientVersion, if non-nil, describes whether a client version update
    # is available.
    client_version: ClientVersion | None = None
    # DriveShares tracks the full set of current DriveShares that we're
    # publishing. Some client applications, like the MacOS and Windows clients,
    # will listen for updates to this and handle serving these shares under
    # the identity of the unprivileged user that is running the application. A
    # nil value here means that we're not broadcasting shares information, an
    # empty value means that there are no shares.
    drive_shares: Any | None = None
    # Health is the last-known health state of the backend. When this field is
    # non-nil, a change in health verified, and the API client should surface
    # any changes to the user in the UI.
    health: Any | None = None
    # SuggestedExitNode, if non-nil, is the node that the backend has determined to
    # be the best exit node for the current network conditions.
    suggested_exit_node: str | None = None


class PartialFile(msgspec.Struct, rename="pascal", omit_defaults=True):
    "PartialFile represents an in-progress incoming file transfer."

    # e.g. "foo.jpg"
    name: str = ""
    # time transfer started
    started: str = ""
    # or -1 if unknown
    declared_size: int = 0
    # bytes copied thus far
    received: int = 0
    # PartialPath is set non-empty in "direct" file mode to the
    # in-progress '*.partial' file's path when the peerapi isn't
    # being used; see LocalBackend.SetDirectFileRoot.
    partial_path: str = ""
    final_path: str = ""
    # Done is set in "direct" mode when the partial file has been
    # closed and is ready for the caller to rename away the
    # ".partial" suffix.
    done: bool = False


class OutgoingFile(msgspec.Struct, rename="pascal", omit_defaults=True):
    "OutgoingFile represents an in-progress outgoing file transfer."

    # unique identifier for this transfer (a type 4 UUID)
    id: str = msgspec.field(default="", name="ID")
    # identifier for the peer to which this is being transferred
    peer_id: str = msgspec.field(default="", name="PeerID")
    # e.g. "foo.jpg"
    name: str = ""
    # time transfer started
    started: str = ""
    # or -1 if unknown
    declared_size: int = 0
    # bytes copied thus far
    sent: int = 0
    # indicates whether or not the transfer finished
    finished: bool = False
    # for a finished transfer, indicates whether or not it was successful
    succeeded: bool = False


class EngineStatus(msgspec.Struct, rename="pascal"):
    "EngineStatus contains WireGuard engine stats."

    r_bytes: int = 0
    w_bytes: int = 0
    num_live: int = 0
    # number of active DERP connections
    live_derps: int = msgspec.field(default=0, name="LiveDERPs")
    live_peers: dict[str, PeerStatusLite] | None = None


class ServeConfig(msgspec.Struct, rename="pascal", omit_defaults=True):
    "ServeConfig is the JSON type stored in the StateStore for\nStateKey \"_serve/$PROFILE_ID\" as returned by ServeConfigKey."

    # TCP are the list of TCP port numbers that tailscaled should handle for
    # the Tailscale IP addresses. (not subnet routers, etc)
    tcp: dict[str, TCPPortHandler] = msgspec.field(default_factory=dict, name="TCP")
    # Web maps from "$SNI_NAME:$PORT" to a set of HTTP handlers
    # keyed by mount point ("/", "/foo", etc)
    web: dict[str, WebServerConfig] = {}
    # Services maps from service name (in the form "svc:dns-label") to a ServiceConfig.
    # Which describes the L3, L4, and L7 forwarding information for the service.
    services: dict[str, ServiceConfig] = {}
    # AllowFunnel is the set of SNI:port values for which funnel
    # traffic is allowed, from trusted ingress peers.
    allow_funnel: dict[str, bool] = {}
    # Foreground is a map of an IPN Bus session ID to an alternate foreground serve config that's valid for the
    # life of that WatchIPNBus session ID. This allows the config to specify ephemeral configs that are used
    # in the CLI's foreground mode to ensure ungraceful shutdowns of either the client or the LocalBackend does not
    # expose ports that users are not aware of. In practice this contains any serve config set via 'tailscale
    # serve' command run without the '--bg' flag. ServeConfig contained by Foreground is not expected itself to contain
    # another Foreground block.
    foreground: dict[str, ServeConfig] = {}
    # ETag is the checksum of the serve config that's populated
    # by the LocalClient through the HTTP ETag header during a
    # GetServeConfig request and is translated to an If-Match header
    # during a SetServeConfig request.


class TCPPortHandler(msgspec.Struct, rename="pascal", omit_defaults=True):
    "TCPPortHandler describes what to do when handling a TCP\nconnection."

    # HTTPS, if true, means that tailscaled should handle this connection as an
    # HTTPS request as configured by ServeConfig.Web.
    # 
    # It is mutually exclusive with TCPForward.
    https: bool = msgspec.field(default=False, name="HTTPS")
    # HTTP, if true, means that tailscaled should handle this connection as an
    # HTTP request as configured by ServeConfig.Web.
    # 
    # It is mutually exclusive with TCPForward.
    http: bool = msgspec.field(default=False, name="HTTP")
    # TCPForward is the IP:port to forward TCP connections to.
    # Whether or not TLS is terminated by tailscaled depends on
    # TerminateTLS.
    # 
    # It is mutually exclusive with HTTPS.
    tcp_forward: str = msgspec.field(default="", name="TCPForward")
    # TerminateTLS, if non-empty, means that tailscaled should terminate the
    # TLS connections before forwarding them to TCPForward, permitting only the
    # SNI name with this value. It is only used if TCPForward is non-empty.
    # (the HTTPS mode uses ServeConfig.Web)
    terminate_tls: str = msgspec.field(default="", name="TerminateTLS")
    # ProxyProtocol indicates whether to send a PROXY protocol header
    # before forwarding the connection to TCPForward.
    # 
    # This is only valid if TCPForward is non-empty.
    proxy_protocol: int = 0


class WebServerConfig(msgspec.Struct, rename="pascal"):
    "WebServerConfig describes a web server's configuration."

    # mountPoint => handler
    handlers: dict[str, HTTPHandler] | None = None


class HTTPHandler(msgspec.Struct, rename="pascal", omit_defaults=True):
    "HTTPHandler is either a path or a proxy to serve."

    # absolute path to directory or file to serve
    path: str = ""
    # http://localhost:3000/, localhost:3030, 3030
    proxy: str = ""
    # plaintext to serve (primarily for testing)
    text: str = ""
    # peer capabilities to forward in grant header, e.g. example.com/cap/mon
    accept_app_caps: list[str] = []
    # Redirect, if not empty, is the target URL to redirect requests to.
    # By default, we redirect with HTTP 302 (Found) status.
    # If Redirect starts with '<httpcode>:', then we use that status instead.
    # 
    # The target URL supports the following expansion variables:
    #   - ${HOST}: replaced with the request's Host header value
    #   - ${REQUEST_URI}: replaced with the request's full URI (path and query string)
    redirect: str = ""


class ServiceConfig(msgspec.Struct, rename="pascal", omit_defaults=True):
    "ServiceConfig contains the config information for a single service.\nit contains a bool to indicate if the service is in Tun mode (L3 forwarding).\nIf the service is not in Tun mode, the service is configured by the L4 forwarding\n(TCP ports) and/or the L7 forwarding (http handlers) information."

    # TCP are the list of TCP port numbers that tailscaled should handle for
    # the Tailscale IP addresses. (not subnet routers, etc)
    tcp: dict[str, TCPPortHandler] = msgspec.field(default_factory=dict, name="TCP")
    # Web maps from "$SNI_NAME:$PORT" to a set of HTTP handlers
    # keyed by mount point ("/", "/foo", etc)
    web: dict[str, WebServerConfig] = {}
    # Tun determines if the service should be using L3 forwarding (Tun mode).
    tun: bool = False


class LoginProfile(msgspec.Struct, rename="pascal"):
    "LoginProfile represents a single login profile as managed\nby the ProfileManager."

    # ID is a unique identifier for this profile.
    # It is assigned on creation and never changes.
    # It may seem redundant to have both ID and UserProfile.ID
    # but they are different things. UserProfile.ID may change
    # over time (e.g. if a device is tagged).
    id: str = msgspec.field(default="", name="ID")
    # Name is the user-visible name of this profile.
    # It is filled in from the UserProfile.LoginName field.
    name: str = ""
    # NetworkProfile is a subset of netmap.NetworkMap that we
    # store to remember information about the tailnet that this
    # profile was logged in with.
    # 
    # This field was added on 2023-11-17.
    network_profile: NetworkProfile | None = None
    # Key is the StateKey under which the profile is stored.
    # It is assigned once at profile creation time and never changes.
    key: str = ""
    # UserProfile is the server provided UserProfile for this profile.
    # This is updated whenever the server provides a new UserProfile.
    user_profile: UserProfile | None = None
    # NodeID is the NodeID of the node that this profile is logged into.
    # This should be stable across tagging and untagging nodes.
    # It may seem redundant to check against both the UserProfile.UserID
    # and the NodeID. However the NodeID can change if the node is deleted
    # from the admin panel.
    node_id: str = msgspec.field(default="", name="NodeID")
    # LocalUserID is the user ID of the user who created this profile.
    # It is only relevant on Windows where we have a multi-user system.
    # It is assigned once at profile creation time and never changes.
    local_user_id: str = msgspec.field(default="", name="LocalUserID")
    # ControlURL is the URL of the control server that this profile is logged
    # into.
    control_url: str = msgspec.field(default="", name="ControlURL")


class NetworkProfile(msgspec.Struct, rename="pascal"):
    "NetworkProfile is a subset of netmap.NetworkMap\nthat should be saved with each user profile."

    magic_dns_name: str = msgspec.field(default="", name="MagicDNSName")
    domain_name: str = ""
    display_name: str = ""


class AutoUpdatePrefsMask(msgspec.Struct, rename="pascal", omit_defaults=True):
    check_set: bool = False
    apply_set: bool = False


class WhoIsResponse(msgspec.Struct, rename="pascal"):
    "WhoIsResponse is the JSON type returned by tailscaled debug server's /whois?ip=$IP handler.\nIn successful whois responses, Node and UserProfile are never nil."

    node: Node | None = None
    user_profile: UserProfile | None = None
    # CapMap is a map of capabilities to their values.
    # See tailcfg.PeerCapMap and tailcfg.PeerCapability for details.
    cap_map: dict[str, list[Any] | None] | None = None


class WaitingFile(msgspec.Struct, rename="pascal"):
    name: str = ""
    size: int = 0


class FileTarget(msgspec.Struct, rename="pascal"):
    "FileTarget is a node to which files can be sent, and the PeerAPI\nURL base to do so via."

    node: Node | None = None
    # PeerAPI is the http://ip:port URL base of the node's PeerAPI,
    # without any path (not even a single slash).
    peer_api_url: str = msgspec.field(default="", name="PeerAPIURL")


class ExitNodeSuggestionResponse(msgspec.Struct, rename="pascal", omit_defaults=True):
    "ExitNodeSuggestionResponse is the response to a LocalAPI suggest-exit-node GET request.\nIt returns the StableNodeID, name, and location of a suggested exit node for the client making the request."

    id: str = msgspec.field(default="", name="ID")
    name: str = ""
    location: Location | None = None


class ReloadConfigResponse(msgspec.Struct, rename="pascal"):
    "ReloadConfigResponse is the response to a LocalAPI reload-config request.\n\nThere are three possible outcomes: (false, \"\") if no config mode in use,\n(true, \"\") on success, or (false, \"error message\") on failure."

    # whether the config was reloaded
    reloaded: bool = False
    # any error message
    err: str = ""


class DNSOSConfig(msgspec.Struct, rename="pascal"):
    "DNSOSConfig mimics dns.OSConfig without forcing us to import the entire dns package\ninto the CLI."

    nameservers: list[str] | None = None
    search_domains: list[str] | None = None
    match_domains: list[str] | None = None


class DNSQueryResponse(msgspec.Struct, rename="pascal"):
    "DNSQueryResponse is the response to a DNS query request sent via LocalAPI."

    # Bytes is the raw DNS response bytes.
    bytes: str = ""
    # Resolvers is the list of resolvers that the forwarder deemed able to resolve the query.
    resolvers: list[Resolver] | None = None


class OptionalFeatures(msgspec.Struct, rename="pascal"):
    "OptionalFeatures describes which optional features are enabled in the build."

    # Features is the map of optional feature names to whether they are
    # enabled.
    # 
    # Disabled features may be absent from the map. (That is, false values
    # are not guaranteed to be present.)
    features: dict[str, bool] | None = None


class SetPushDeviceTokenRequest(msgspec.Struct, rename="pascal"):
    "SetPushDeviceTokenRequest is the body POSTed to the LocalAPI endpoint /set-device-token."

    # PushDeviceToken is the iOS/macOS APNs device token (and any future Android equivalent).
    push_device_token: str = ""


class Resolver(msgspec.Struct, rename="pascal", omit_defaults=True):
    "Resolver is the configuration for one DNS resolver."

    # Addr is the address of the DNS resolver, one of:
    #  - A plain IP address for a "classic" UDP+TCP DNS resolver.
    #    This is the common format as sent by the control plane.
    #  - An IP:port, for tests.
    #  - "https://resolver.com/path" for DNS over HTTPS; currently
    #    as of 2022-09-08 only used for certain well-known resolvers
    #    (see the publicdns package) for which the IP addresses to dial DoH are
    #    known ahead of time, so bootstrap DNS resolution is not required.
    #  - "http://node-address:port/path" for DNS over HTTP over WireGuard. This
    #    is implemented in the PeerAPI for exit nodes and app connectors.
    #  - [TODO] "tls://resolver.com" for DNS over TCP+TLS
    addr: str = ""
    # BootstrapResolution is an optional suggested resolution for the
    # DoT/DoH resolver, if the resolver URL does not reference an IP
    # address directly.
    # BootstrapResolution may be empty, in which case clients should
    # look up the DoT/DoH server using their local "classic" DNS
    # resolver.
    # 
    # As of 2022-09-08, BootstrapResolution is not yet used.
    bootstrap_resolution: list[str] = []
    # UseWithExitNode designates that this resolver should continue to be used when an
    # exit node is in use. Normally, DNS resolution is delegated to the exit node but
    # there are situations where it is preferable to still use a Split DNS server and/or
    # global DNS server instead of the exit node.
    use_with_exit_node: bool = False
