package main

import (
	"fmt"
	"strings"
)

// pythonKeywords maps Python keywords/builtins to safe alternatives.
var pythonKeywords = map[string]string{
	"self":   "self_node",
	"type":   "type_",
	"class":  "class_",
	"import": "import_",
	"from":   "from_",
	"None":   "none",
	"True":   "true_",
	"False":  "false_",
}

func pyFieldName(goName string) string {
	snake := toSnakeCase(goName)
	if replacement, ok := pythonKeywords[snake]; ok {
		return replacement
	}
	return snake
}

func generatePython(structs []*StructInfo) string {
	var b strings.Builder

	b.WriteString("# Code generated by cmd/typegen; DO NOT EDIT.\n\n")
	b.WriteString("from __future__ import annotations\n\n")
	b.WriteString("from typing import Any\n\n")
	b.WriteString("import msgspec\n\n\n")

	for i, si := range structs {
		if i > 0 {
			b.WriteString("\n\n")
		}

		// Determine if any field has omit tags (omitempty/omitzero).
		// When true, we use omit_defaults=True so those fields are
		// omitted from JSON output when they match their default,
		// matching Go's encoding behavior.
		anyOmit := false
		for _, fi := range si.Fields {
			if fi.Omit != "" {
				anyOmit = true
				break
			}
		}

		// Write class definition
		structOpts := `rename="pascal"`
		if anyOmit {
			structOpts += ", omit_defaults=True"
		}
		b.WriteString(fmt.Sprintf("class %s(msgspec.Struct, %s):\n", si.Name, structOpts))

		// Struct docstring
		if si.Comment != "" {
			b.WriteString(fmt.Sprintf("    %q\n\n", si.Comment))
		}

		if len(si.Fields) == 0 {
			b.WriteString("    pass\n")
			continue
		}

		for _, fi := range si.Fields {
			pyType := pythonTypeAnnotation(fi)
			pyName := pyFieldName(fi.GoName)

			if fi.Comment != "" {
				for _, line := range strings.Split(fi.Comment, "\n") {
					b.WriteString("    # " + line + "\n")
				}
			}

			// Check if we need an explicit name override
			expectedPascal := snakeToPascal(pyName)
			needsName := expectedPascal != fi.JSONName

			if needsName {
				defaultVal := pythonMsgspecFieldDefault(fi)
				b.WriteString(fmt.Sprintf("    %s: %s = msgspec.field(%s, name=%q)\n", pyName, pyType, defaultVal, fi.JSONName))
			} else {
				defaultVal := pythonDefault(fi)
				b.WriteString(fmt.Sprintf("    %s: %s = %s\n", pyName, pyType, defaultVal))
			}
		}
	}

	return b.String()
}

// pythonDefault returns the Python default value for a field (simple form, no msgspec.field()).
func pythonDefault(fi FieldInfo) string {
	if fi.IsOptional {
		return "None"
	}
	// Non-optional slices/maps without omit can receive null from Go
	// (nil slices/maps serialize as null). Default to None for these.
	// With omit, the field is absent when nil, so default to []/{}.
	if fi.IsSlice {
		if fi.Omit == "" {
			return "None"
		}
		return "[]"
	}
	if fi.IsMap {
		if fi.Omit == "" {
			return "None"
		}
		return "{}"
	}

	switch fi.PythonType {
	case "str":
		return `""`
	case "bool":
		return "False"
	case "int":
		return "0"
	case "float":
		return "0.0"
	case "bytes":
		return `b""`
	case "Any":
		return "None"
	}

	if fi.IsNestedStruct {
		return "None"
	}

	return "None"
}

// pythonMsgspecFieldDefault returns the default argument for msgspec.field().
func pythonMsgspecFieldDefault(fi FieldInfo) string {
	if fi.IsOptional || fi.IsNestedStruct {
		return "default=None"
	}
	// Non-optional slices/maps without omit can receive null from Go.
	if fi.IsSlice {
		if fi.Omit == "" {
			return "default=None"
		}
		return "default_factory=list"
	}
	if fi.IsMap {
		if fi.Omit == "" {
			return "default=None"
		}
		return "default_factory=dict"
	}

	switch fi.PythonType {
	case "str":
		return `default=""`
	case "bool":
		return "default=False"
	case "int":
		return "default=0"
	case "float":
		return "default=0.0"
	case "bytes":
		return `default=b""`
	case "Any":
		return "default=None"
	}

	return "default=None"
}

// pythonTypeAnnotation returns the Python type annotation for a field,
// making fields nullable when they default to None.
func pythonTypeAnnotation(fi FieldInfo) string {
	pyType := fi.PythonType

	// Ensure optional fields have | None in their type.
	// Some paths (e.g. *views.Slice handling) set IsOptional=true
	// without adding | None to the resolved Python type.
	if fi.IsOptional && !strings.Contains(pyType, "| None") {
		pyType += " | None"
	}

	// Non-optional nested structs default to None, so need | None type.
	if fi.IsNestedStruct && !fi.IsOptional {
		return fi.PythonType + " | None"
	}

	// Non-optional slices/maps without omit can receive null from Go
	// (nil Go slices/maps serialize as JSON null). These default to None.
	if (fi.IsSlice || fi.IsMap) && !fi.IsOptional && fi.Omit == "" {
		return pyType + " | None"
	}

	return pyType
}
