package main

import (
	"fmt"
	"strings"
	"unicode"
)

// rustKeywords that need to be escaped with r# when used as field names.
// Note: "self", "super", "crate", and "Self" cannot use raw identifiers
// and need aliases instead.
var rustKeywords = map[string]bool{
	"type": true, "struct": true,
	"enum": true, "mod": true, "ref": true,
}

// rustKeywordAliases are keywords that cannot use raw identifiers and need
// explicit renames.
var rustKeywordAliases = map[string]string{
	"self": "self_",
}

func generateRust(structs []*StructInfo) string {
	var b strings.Builder

	b.WriteString("// Code generated by cmd/typegen; DO NOT EDIT.\n\n")
	b.WriteString("use serde::{Deserialize, Deserializer, Serialize};\n")
	b.WriteString("use std::collections::HashMap;\n")
	b.WriteString("\n")
	b.WriteString("/// Deserialize null JSON values as the type's default.\n")
	b.WriteString("/// Go serializes nil slices/maps as null, but Rust expects a sequence/map.\n")
	b.WriteString("fn deserialize_null_default<'de, D, T>(deserializer: D) -> Result<T, D::Error>\n")
	b.WriteString("where\n")
	b.WriteString("    D: Deserializer<'de>,\n")
	b.WriteString("    T: Default + Deserialize<'de>,\n")
	b.WriteString("{\n")
	b.WriteString("    Ok(Option::deserialize(deserializer)?.unwrap_or_default())\n")
	b.WriteString("}\n")

	for _, si := range structs {
		b.WriteString("\n")

		// Struct doc comment
		if si.Comment != "" {
			writeRustDoc(&b, si.Comment, "")
		}

		b.WriteString("#[derive(Debug, Clone, Default, Serialize, Deserialize)]\n")
		b.WriteString("#[serde(rename_all = \"PascalCase\")]\n")
		b.WriteString(fmt.Sprintf("pub struct %s {\n", si.Name))

		for _, fi := range si.Fields {
			// Field doc comment
			if fi.Comment != "" {
				writeRustDoc(&b, fi.Comment, "    ")
			}

			rustFieldName := toSnakeCase(fi.GoName)
			rustType := fi.RustType

			// Handle Rust keywords
			if alias, ok := rustKeywordAliases[rustFieldName]; ok {
				rustFieldName = alias
			}

			// Fields with json:"-" are skipped during serialization
			if fi.IsSkipped {
				b.WriteString("    #[serde(skip)]\n")
				b.WriteString(fmt.Sprintf("    pub %s: %s,\n", rustFieldName, rustType))
				continue
			}

			// Determine if we need explicit serde(rename)
			expectedPascal := snakeToPascal(rustFieldName)
			if fi.JSONName != expectedPascal {
				b.WriteString(fmt.Sprintf("    #[serde(rename = %q)]\n", fi.JSONName))
			}

			// Escape remaining Rust keywords with raw identifiers
			if rustKeywords[rustFieldName] {
				rustFieldName = "r#" + rustFieldName
			}

			// Handle omitempty/omitzero
			if fi.Omit == "omitempty" || fi.Omit == "omitzero" {
				if fi.IsSlice {
					b.WriteString("    #[serde(skip_serializing_if = \"Vec::is_empty\")]\n")
				} else if fi.IsMap {
					b.WriteString("    #[serde(skip_serializing_if = \"HashMap::is_empty\")]\n")
				} else if fi.IsOptional {
					b.WriteString("    #[serde(skip_serializing_if = \"Option::is_none\")]\n")
				} else if rustType == "String" {
					b.WriteString("    #[serde(skip_serializing_if = \"String::is_empty\")]\n")
				} else if isIntType(rustType) || rustType == "f64" || rustType == "bool" {
					b.WriteString("    #[serde(skip_serializing_if = \"is_default\")]\n")
				}
			}

			// Add serde attributes for deserialization defaults.
			// Go serializes nil slices/maps as null; use deserialize_null_default
			// to handle both null and missing fields.
			if fi.IsSlice || fi.IsMap {
				b.WriteString("    #[serde(default, deserialize_with = \"deserialize_null_default\")]\n")
			} else if fi.IsOptional {
				// Option fields: always skip serializing None to match Go's omitempty on pointer types
				if fi.Omit != "omitempty" && fi.Omit != "omitzero" {
					b.WriteString("    #[serde(skip_serializing_if = \"Option::is_none\")]\n")
				}
				b.WriteString("    #[serde(default)]\n")
			} else if fi.IsNestedStruct {
				b.WriteString("    #[serde(default)]\n")
			} else if rustType == "String" || rustType == "bool" || isIntType(rustType) || rustType == "f64" {
				b.WriteString("    #[serde(default)]\n")
			}

			b.WriteString(fmt.Sprintf("    pub %s: %s,\n", rustFieldName, rustType))
		}

		b.WriteString("}\n")
	}

	// Add helper function for skip_serializing_if
	b.WriteString("\nfn is_default<T: Default + PartialEq>(v: &T) -> bool {\n    *v == T::default()\n}\n")

	return b.String()
}

// Known acronyms used in Go Tailscale type field names.
// These are matched greedily from left to right to split words correctly.
var knownAcronyms = []string{
	"HTTPS", "HTTP",
	"STUN", "SNAT",
	"DERP", "TURN",
	"DNS", "TUN", "URL", "API", "IPN", "TCP", "UDP", "SSH", "TLS",
	"LAN", "WoL", "MAC", "PCP", "PMP", "UPnP",
	"IPv4", "IPv6",
	"IP", "OS", "ID", "UI",
}

// toSnakeCase converts a Go PascalCase name to Rust snake_case.
func toSnakeCase(s string) string {
	// Handle underscore-containing names like SSH_HostKeys
	if strings.Contains(s, "_") {
		parts := strings.Split(s, "_")
		var result []string
		for _, p := range parts {
			if p != "" {
				result = append(result, toSnakeCase(p))
			}
		}
		return strings.Join(result, "_")
	}

	words := splitWords(s)
	var result []string
	for _, w := range words {
		result = append(result, strings.ToLower(w))
	}
	return strings.Join(result, "_")
}

// splitWords splits a PascalCase string into words, recognizing known acronyms.
func splitWords(s string) []string {
	var words []string
	i := 0

	for i < len(s) {
		// Try to match a known acronym at position i
		matched := false
		if unicode.IsUpper(rune(s[i])) {
			for _, acr := range knownAcronyms {
				if !strings.HasPrefix(s[i:], acr) {
					continue
				}
				after := i + len(acr)
				if after >= len(s) {
					// Acronym at end of string
					words = append(words, acr)
					i = after
					matched = true
					break
				}
				ch := rune(s[after])
				if unicode.IsUpper(ch) {
					// Followed by another uppercase word
					words = append(words, acr)
					i = after
					matched = true
					break
				}
				if unicode.IsDigit(ch) {
					// Followed by digit (e.g., acronym then number) - consume digits too
					k := after
					for k < len(s) && unicode.IsDigit(rune(s[k])) {
						k++
					}
					words = append(words, s[i:k])
					i = k
					matched = true
					break
				}
				if unicode.IsLower(ch) {
					// Followed by lowercase. Check if it's just a short tail (plural 's', etc.)
					// Count the lowercase run
					k := after
					for k < len(s) && (unicode.IsLower(rune(s[k])) || unicode.IsDigit(rune(s[k]))) {
						k++
					}
					lowTail := s[after:k]
					if len(lowTail) <= 1 || lowTail == "es" {
						// Short plural suffix: treat as part of the acronym
						words = append(words, s[i:k])
						i = k
						matched = true
						break
					}
					// Longer lowercase tail means the acronym isn't the right split here
					// (e.g., "IPNVersion" - don't match "IP" leaving "NVersion")
					// Only match if the full acronym ends cleanly
					// Skip this acronym, try shorter ones
				}
			}
		}
		if matched {
			continue
		}

		if unicode.IsUpper(rune(s[i])) {
			// Regular PascalCase word: uppercase letter followed by lowercase/digits
			j := i + 1
			for j < len(s) && !unicode.IsUpper(rune(s[j])) {
				j++
			}
			words = append(words, s[i:j])
			i = j
		} else {
			// Lowercase/digit run (shouldn't normally happen at start of a word)
			j := i + 1
			for j < len(s) && !unicode.IsUpper(rune(s[j])) {
				j++
			}
			words = append(words, s[i:j])
			i = j
		}
	}
	return words
}

// snakeToPascal converts snake_case back to PascalCase (as serde rename_all would).
func snakeToPascal(s string) string {
	parts := strings.Split(s, "_")
	var result string
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		result += strings.ToUpper(p[:1]) + p[1:]
	}
	return result
}

// writeRustDoc writes a doc comment, wrapping code-like content in ```text blocks.
func writeRustDoc(b *strings.Builder, comment string, indent string) {
	lines := strings.Split(comment, "\n")

	// Check if any line looks like code (starts with *, ", or contains backtick-like patterns)
	hasCodeLike := false
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "*") || strings.HasPrefix(trimmed, "\"") || strings.HasPrefix(trimmed, "`") {
			hasCodeLike = true
			break
		}
	}

	if hasCodeLike {
		// Write the comment wrapped in a text block to prevent doc test parsing
		b.WriteString(indent + "/// ```text\n")
		for _, line := range lines {
			b.WriteString(indent + "/// " + line + "\n")
		}
		b.WriteString(indent + "/// ```\n")
	} else {
		for _, line := range lines {
			b.WriteString(indent + "/// " + line + "\n")
		}
	}
}

func isIntType(t string) bool {
	switch t {
	case "i32", "i64", "u16", "u64":
		return true
	}
	return false
}
