package main

import (
	"fmt"
	"strings"
)

func generateTypeScript(structs []*StructInfo) string {
	var b strings.Builder

	b.WriteString("// Code generated by cmd/typegen; DO NOT EDIT.\n\n")

	for i, si := range structs {
		if i > 0 {
			b.WriteString("\n")
		}

		// Struct doc comment
		if si.Comment != "" {
			lines := strings.Split(si.Comment, "\n")
			if len(lines) == 1 {
				b.WriteString(fmt.Sprintf("/** %s */\n", lines[0]))
			} else {
				b.WriteString("/**\n")
				for _, line := range lines {
					b.WriteString(" * " + line + "\n")
				}
				b.WriteString(" */\n")
			}
		}

		b.WriteString(fmt.Sprintf("export interface %s {\n", si.Name))

		for _, fi := range si.Fields {
			// Field doc comment
			if fi.Comment != "" {
				lines := strings.Split(fi.Comment, "\n")
				if len(lines) == 1 {
					b.WriteString(fmt.Sprintf("  /** %s */\n", lines[0]))
				} else {
					b.WriteString("  /**\n")
					for _, line := range lines {
						b.WriteString("   * " + line + "\n")
					}
					b.WriteString("   */\n")
				}
			}

			tsType := fi.TypeScriptType
			optional := ""

			// In TypeScript, optional fields use ?:
			if fi.IsOptional || fi.Omit == "omitempty" || fi.Omit == "omitzero" {
				optional = "?"
				// Clean up " | undefined" from the type since we use ?
				tsType = strings.TrimSuffix(tsType, " | undefined")
			}

			// Go nil slices and maps marshal as JSON null, so non-optional
			// collection fields can be null on the wire.
			if (fi.IsSlice || fi.IsMap) && optional == "" {
				tsType += " | null"
			}

			b.WriteString(fmt.Sprintf("  %s%s: %s;\n", fi.JSONName, optional, tsType))
		}

		b.WriteString("}\n")
	}

	// Append client-specific types not from Go source
	b.WriteString(`
/** Alias for TailnetStatus for backward compatibility. */
export interface CurrentTailnet {
  Name: string;
  MagicDNSSuffix: string;
  MagicDNSEnabled: boolean;
}

/** Profile status containing current and all profiles. */
export interface ProfileStatus {
  CurrentProfile: LoginProfile;
  AllProfiles: LoginProfile[];
}

/** Bitmask for IPN bus watch notifications. */
export enum NotifyWatchOpt {
  /** Receive initial state at start of watch. */
  NotifyInitialState = 1 << 1,
  /** Receive full network map updates. */
  NotifyInitialNetMap = 1 << 2,
  /** Receive partial state updates. */
  NotifyInitialDriveShares = 1 << 3,
  /** Receive full prefs in initial state. */
  NotifyInitialPrefs = 1 << 4,
  /** Receive outgoing file updates. */
  NotifyInitialOutgoingFiles = 1 << 5,
}
`)

	return b.String()
}
