export { LocalClient } from "./client.js";
export {
  TailscaleError,
  AccessDeniedError,
  PreconditionsFailedError,
  PeerNotFoundError,
  ConnectionError,
  DaemonNotRunningError,
  HttpError,
} from "./errors.js";
export {
  ClientVersionSchema,
  CurrentTailnetSchema,
  DERPMapSchema,
  DNSOSConfigSchema,
  DNSQueryResponseSchema,
  ExitNodeSuggestionResponseSchema,
  FileTargetSchema,
  LoginProfileSchema,
  MaskedPrefsSchema,
  NetworkLockStatusSchema,
  NetworkProfileSchema,
  NotifySchema,
  NotifyWatchOpt,
  OptionalFeaturesSchema,
  PeerStatusSchema,
  PingResultSchema,
  PrefsSchema,
  ProfileStatusSchema,
  ReloadConfigResponseSchema,
  ServeConfigSchema,
  StatusSchema,
  TailnetStatusSchema,
  UserProfileSchema,
  WaitingFileSchema,
  WhoIsResponseSchema,
  type ClientVersion,
  type CurrentTailnet,
  type DERPMap,
  type DNSOSConfig,
  type DNSQueryResponse,
  type ExitNodeSuggestionResponse,
  type FileTarget,
  type LoginProfile,
  type MaskedPrefs,
  type NetworkLockStatus,
  type NetworkProfile,
  type Notify,
  type OptionalFeatures,
  type PeerStatus,
  type PingResult,
  type Prefs,
  type ProfileStatus,
  type ReloadConfigResponse,
  type ServeConfig,
  type Status,
  type TailnetStatus,
  type UserProfile,
  type WaitingFile,
  type WhoIsResponse,
} from "./types.js";
export { IPNBusWatcher } from "./ipn-bus-watcher.js";
export { parseJSON, jsonReviver, jsonReplacer } from "./json.js";
