// Code generated by cmd/typegen; DO NOT EDIT.

import { z } from "zod";

const goSlice = <T extends z.ZodTypeAny>(item: T) =>
  z.array(item).nullish().transform(v => v ?? []);

const goMap = <V extends z.ZodTypeAny>(val: V) =>
  z.record(z.string(), val).nullish().transform(v => v ?? {});

const int64 = z.union([z.number().int(), z.bigint()]).transform(v => BigInt(v));

/**
 * Location represents geographical location data about a
 * Tailscale host. Location is optional and only set if
 * explicitly declared by a node.
 */
export const LocationSchema = z.object({
  /** User friendly country name, with proper capitalization ("Canada") */
  Country: z.string().nullish(),
  /** ISO 3166-1 alpha-2 in upper case ("CA") */
  CountryCode: z.string().nullish(),
  /** User friendly city name, with proper capitalization ("Squamish") */
  City: z.string().nullish(),
  /**
   * CityCode is a short code representing the city in upper case.
   * CityCode is used to disambiguate a city from another location
   * with the same city name. It uniquely identifies a particular
   * geographical location, within the tailnet.
   * IATA, ICAO or ISO 3166-2 codes are recommended ("YSE")
   */
  CityCode: z.string().nullish(),
  /**
   * Latitude, Longitude are optional geographical coordinates of the node, in degrees.
   * No particular accuracy level is promised; the coordinates may simply be the center of the city or country.
   */
  Latitude: z.number().nullish(),
  Longitude: z.number().nullish(),
  /**
   * Priority determines the order of use of an exit node when a
   * location based preference matches more than one exit node,
   * the node with the highest priority wins. Nodes of equal
   * probability may be selected arbitrarily.
   * 
   * A value of 0 means the exit node does not have a priority
   * preference. A negative int is not allowed.
   */
  Priority: int64.nullish(),
});
export type Location = z.infer<typeof LocationSchema>;

/**
 * PeerStatus describes a peer node and its current state.
 * WARNING: The fields in PeerStatus are merged by the AddPeer method in the StatusBuilder.
 * When adding a new field to PeerStatus, you must update AddPeer to handle merging
 * the new field. The AddPeer function is responsible for combining multiple updates
 * to the same peer, and any new field that is not merged properly may lead to
 * inconsistencies or lost data in the peer status.
 */
export const PeerStatusSchema = z.object({
  ID: z.string().default(""),
  PublicKey: z.string().default(""),
  /** HostInfo's Hostname (not a DNS name or necessarily unique) */
  HostName: z.string().default(""),
  /**
   * DNSName is the Peer's FQDN. It ends with a dot.
   * It has the form "host.<MagicDNSSuffix>."
   */
  DNSName: z.string().default(""),
  /** HostInfo.OS */
  OS: z.string().default(""),
  UserID: int64.default(0),
  /**
   * AltSharerUserID is the user who shared this node
   * if it's different than UserID. Otherwise it's zero.
   */
  AltSharerUserID: int64.nullish(),
  /** TailscaleIPs are the IP addresses assigned to the node. */
  TailscaleIPs: goSlice(z.string()),
  /** AllowedIPs are IP addresses allowed to route to this node. */
  AllowedIPs: goSlice(z.string()),
  /**
   * Tags are the list of ACL tags applied to this node.
   * See tailscale.com/tailcfg#Node.Tags for more information.
   */
  Tags: goSlice(z.string()),
  /**
   * PrimaryRoutes are the routes this node is currently the primary
   * subnet router for, as determined by the control plane. It does
   * not include the IPs in TailscaleIPs.
   */
  PrimaryRoutes: goSlice(z.string()),
  /** Endpoints: */
  Addrs: goSlice(z.string()),
  /** one of Addrs, or unique if roaming */
  CurAddr: z.string().default(""),
  /** DERP region */
  Relay: z.string().default(""),
  /** peer relay address (ip:port:vni) */
  PeerRelay: z.string().default(""),
  RxBytes: int64.default(0),
  TxBytes: int64.default(0),
  /** time registered with tailcontrol */
  Created: z.string().default(""),
  /** time last packet sent */
  LastWrite: z.string().default(""),
  /** last seen to tailcontrol; only present if offline */
  LastSeen: z.string().default(""),
  /** with local wireguard */
  LastHandshake: z.string().default(""),
  /** whether node is connected to the control plane */
  Online: z.boolean().default(false),
  /** true if this is the currently selected exit node. */
  ExitNode: z.boolean().default(false),
  /** true if this node can be an exit node (offered && approved) */
  ExitNodeOption: z.boolean().default(false),
  /**
   * Active is whether the node was recently active. The
   * definition is somewhat undefined but has historically and
   * currently means that there was some packet sent to this
   * peer in the past two minutes. That definition is subject to
   * change.
   */
  Active: z.boolean().default(false),
  /** PeerAPIURL are the URLs of the node's PeerAPI servers. */
  PeerAPIURL: goSlice(z.string()),
  /** TaildropTargetStatus represents the node's eligibility to have files shared to it. */
  TaildropTarget: int64.default(0),
  /** Reason why this peer cannot receive files. Empty if CanReceiveFiles=true */
  NoFileSharingReason: z.string().default(""),
  /**
   * Capabilities are capabilities that the node has.
   * They're free-form strings, but should be in the form of URLs/URIs
   * such as:
   *    "https://tailscale.com/cap/is-admin"
   *    "https://tailscale.com/cap/file-sharing"
   *    "funnel"
   * 
   * Deprecated: use CapMap instead. See https://github.com/tailscale/tailscale/issues/11508
   * Every value is Capabilities is also a key in CapMap, even if it
   * has no values in that map.
   */
  Capabilities: goSlice(z.string()),
  /** CapMap is a map of capabilities to their values. */
  CapMap: goMap(goSlice(z.unknown())),
  /** SSH_HostKeys are the node's SSH host keys, if known. */
  sshHostKeys: goSlice(z.string()),
  /**
   * ShareeNode indicates this node exists in the netmap because
   * it's owned by a shared-to user and that node might connect
   * to us. These nodes should be hidden by "tailscale status"
   * etc by default.
   */
  ShareeNode: z.boolean().nullish(),
  /**
   * InNetworkMap means that this peer was seen in our latest network map.
   * In theory, all of InNetworkMap and InMagicSock and InEngine should all be true.
   */
  InNetworkMap: z.boolean().default(false),
  /**
   * InMagicSock means that this peer is being tracked by magicsock.
   * In theory, all of InNetworkMap and InMagicSock and InEngine should all be true.
   */
  InMagicSock: z.boolean().default(false),
  /**
   * InEngine means that this peer is tracked by the wireguard engine.
   * In theory, all of InNetworkMap and InMagicSock and InEngine should all be true.
   */
  InEngine: z.boolean().default(false),
  /**
   * Expired means that this peer's node key has expired, based on either
   * information from control or optimisically set on the client if the
   * expiration time has passed.
   */
  Expired: z.boolean().nullish(),
  /**
   * KeyExpiry, if present, is the time at which the node key expired or
   * will expire.
   */
  KeyExpiry: z.string().nullish(),
  Location: LocationSchema.nullish(),
});
export type PeerStatus = z.infer<typeof PeerStatusSchema>;

/** ExitNodeStatus describes the current exit node. */
export const ExitNodeStatusSchema = z.object({
  /** ID is the exit node's ID. */
  ID: z.string().default(""),
  /** Online is whether the exit node is alive. */
  Online: z.boolean().default(false),
  /** TailscaleIPs are the exit node's IP addresses assigned to the node. */
  TailscaleIPs: goSlice(z.string()),
});
export type ExitNodeStatus = z.infer<typeof ExitNodeStatusSchema>;

/** TailnetStatus is information about a Tailscale network ("tailnet"). */
export const TailnetStatusSchema = z.object({
  /** Name is the name of the network that's currently in use. */
  Name: z.string().default(""),
  /**
   * MagicDNSSuffix is the network's MagicDNS suffix for nodes
   * in the network such as "userfoo.tailscale.net".
   * There are no surrounding dots.
   * MagicDNSSuffix should be populated regardless of whether a domain
   * has MagicDNS enabled.
   */
  MagicDNSSuffix: z.string().default(""),
  /**
   * MagicDNSEnabled is whether or not the network has MagicDNS enabled.
   * Note that the current device may still not support MagicDNS if
   * `--accept-dns=false` was used.
   */
  MagicDNSEnabled: z.boolean().default(false),
});
export type TailnetStatus = z.infer<typeof TailnetStatusSchema>;

/**
 * A UserProfile is display-friendly data for a [User].
 * It includes the LoginName for display purposes but *not* the Provider.
 * It also includes derived data from one of the user's logins.
 */
export const UserProfileSchema = z.object({
  ID: int64.default(0),
  /** "alice@smith.com"; for display purposes only (provider is not listed) */
  LoginName: z.string().default(""),
  /** "Alice Smith" */
  DisplayName: z.string().default(""),
  ProfilePicURL: z.string().nullish(),
});
export type UserProfile = z.infer<typeof UserProfileSchema>;

/**
 * ClientVersion is information about the latest client version that's available
 * for the client (and whether they're already running it).
 * 
 * It does not include a URL to download the client, as that varies by platform.
 */
export const ClientVersionSchema = z.object({
  /** RunningLatest is true if the client is running the latest build. */
  RunningLatest: z.boolean().nullish(),
  /**
   * LatestVersion is the latest version.Short ("1.34.2") version available
   * for download for the client's platform and packaging type.
   * It won't be populated if RunningLatest is true.
   */
  LatestVersion: z.string().nullish(),
  /**
   * UrgentSecurityUpdate is set when the client is missing an important
   * security update. That update may be in LatestVersion or earlier.
   * UrgentSecurityUpdate should not be set if RunningLatest is false.
   */
  UrgentSecurityUpdate: z.boolean().nullish(),
  /**
   * Notify is whether the client should do an OS-specific notification about
   * a new version being available. This should not be populated if
   * RunningLatest is true. The client should not notify multiple times for
   * the same LatestVersion value.
   */
  Notify: z.boolean().nullish(),
  /**
   * NotifyURL is a URL to open in the browser when the user clicks on the
   * notification, when Notify is true.
   */
  NotifyURL: z.string().nullish(),
  /** NotifyText is the text to show in the notification, when Notify is true. */
  NotifyText: z.string().nullish(),
});
export type ClientVersion = z.infer<typeof ClientVersionSchema>;

/** Status represents the entire state of the IPN network. */
export const StatusSchema = z.object({
  /** Version is the daemon's long version (see version.Long). */
  Version: z.string().default(""),
  /**
   * TUN is whether /dev/net/tun (or equivalent kernel interface) is being
   * used. If false, it's running in userspace mode.
   */
  TUN: z.boolean().default(false),
  /**
   * BackendState is an ipn.State string value:
   *  "NoState", "NeedsLogin", "NeedsMachineAuth", "Stopped",
   *  "Starting", "Running".
   */
  BackendState: z.string().default(""),
  /** HaveNodeKey is whether the current profile has a node key configured. */
  HaveNodeKey: z.boolean().nullish(),
  /** current URL provided by control to authorize client */
  AuthURL: z.string().default(""),
  /** Tailscale IP(s) assigned to this node */
  TailscaleIPs: goSlice(z.string()),
  Self: PeerStatusSchema.nullish(),
  /**
   * ExitNodeStatus describes the current exit node.
   * If nil, an exit node is not in use.
   */
  ExitNodeStatus: ExitNodeStatusSchema.nullish(),
  /**
   * Health contains health check problems.
   * Empty means everything is good. (or at least that no known
   * problems are detected)
   */
  Health: goSlice(z.string()),
  /**
   * This field is the legacy name of CurrentTailnet.MagicDNSSuffix.
   * 
   * Deprecated: use CurrentTailnet.MagicDNSSuffix instead.
   */
  MagicDNSSuffix: z.string().default(""),
  /**
   * CurrentTailnet is information about the tailnet that the node
   * is currently connected to. When not connected, this field is nil.
   */
  CurrentTailnet: TailnetStatusSchema.nullish(),
  /**
   * CertDomains are the set of DNS names for which the control
   * plane server will assist with provisioning TLS
   * certificates. See SetDNSRequest for dns-01 ACME challenges
   * for e.g. LetsEncrypt. These names are FQDNs without
   * trailing periods, and without any "_acme-challenge." prefix.
   */
  CertDomains: goSlice(z.string()),
  /** Peer is the state of each peer, keyed by each peer's current public key. */
  Peer: goMap(PeerStatusSchema),
  /**
   * User contains profile information about UserIDs referenced by
   * PeerStatus.UserID, PeerStatus.AltSharerUserID, etc.
   */
  User: goMap(UserProfileSchema),
  /**
   * ClientVersion, when non-nil, contains information about the latest
   * version of the Tailscale client that's available. Depending on
   * the platform and client settings, it may not be available.
   */
  ClientVersion: ClientVersionSchema.nullish(),
});
export type Status = z.infer<typeof StatusSchema>;

/**
 * PingResult contains response information for the "tailscale ping" subcommand,
 * saying how Tailscale can reach a Tailscale IP or subnet-routed IP.
 * See tailcfg.PingResponse for a related response that is sent back to control
 * for remote diagnostic pings.
 */
export const PingResultSchema = z.object({
  /** ping destination */
  IP: z.string().default(""),
  /** Tailscale IP of node handling IP (different for subnet routers) */
  NodeIP: z.string().default(""),
  /** DNS name base or (possibly not unique) hostname */
  NodeName: z.string().default(""),
  Err: z.string().default(""),
  LatencySeconds: z.number().default(0),
  /**
   * Endpoint is a string of the form "{ip}:{port}" if direct UDP was used. It
   * is not currently set for TSMP.
   */
  Endpoint: z.string().default(""),
  /**
   * PeerRelay is a string of the form "{ip}:{port}:vni:{vni}" if a peer
   * relay was used. It is not currently set for TSMP. Note that this field
   * is not omitted during JSON encoding if it contains a zero value. This is
   * done for consistency with the Endpoint field; this structure is exposed
   * externally via localAPI, so we want to maintain the existing convention.
   */
  PeerRelay: z.string().default(""),
  /**
   * DERPRegionID is non-zero DERP region ID if DERP was used.
   * It is not currently set for TSMP pings.
   */
  DERPRegionID: int64.default(0),
  /**
   * DERPRegionCode is the three-letter region code
   * corresponding to DERPRegionID.
   * It is not currently set for TSMP pings.
   */
  DERPRegionCode: z.string().default(""),
  /**
   * PeerAPIPort is set by TSMP ping responses for peers that
   * are running a peerapi server. This is the port they're
   * running the server on.
   */
  PeerAPIPort: z.number().nullish(),
  /**
   * PeerAPIURL is the URL that was hit for pings of type "peerapi" (tailcfg.PingPeerAPI).
   * It's of the form "http://ip:port" (or [ip]:port for IPv6).
   */
  PeerAPIURL: z.string().nullish(),
  /**
   * IsLocalIP is whether the ping request error is due to it being
   * a ping to the local node.
   */
  IsLocalIP: z.boolean().nullish(),
});
export type PingResult = z.infer<typeof PingResultSchema>;

/** TKAKey describes a key trusted by network lock. */
export const TKAKeySchema = z.object({
  Kind: z.string().default(""),
  Key: z.string().default(""),
  Metadata: goMap(z.string()),
  Votes: int64.default(0),
});
export type TKAKey = z.infer<typeof TKAKeySchema>;

/** TKAPeer describes a peer and its network lock details. */
export const TKAPeerSchema = z.object({
  /** DNS */
  Name: z.string().default(""),
  ID: int64.default(0),
  StableID: z.string().default(""),
  /** Tailscale IP(s) assigned to this node */
  TailscaleIPs: goSlice(z.string()),
  NodeKey: z.string().default(""),
  NodeKeySignature: z.unknown(),
});
export type TKAPeer = z.infer<typeof TKAPeerSchema>;

/**
 * NetworkLockStatus represents whether network-lock is enabled,
 * along with details about the locally-known state of the tailnet
 * key authority.
 */
export const NetworkLockStatusSchema = z.object({
  /** Enabled is true if network lock is enabled. */
  Enabled: z.boolean().default(false),
  /**
   * Head describes the AUM hash of the leaf AUM. Head is nil
   * if network lock is not enabled.
   */
  Head: z.string().nullish(),
  /**
   * PublicKey describes the node's network-lock public key.
   * It may be zero if the node has not logged in.
   */
  PublicKey: z.string().default(""),
  /**
   * NodeKey describes the node's current node-key. This field is not
   * populated if the node is not operating (i.e. waiting for a login).
   */
  NodeKey: z.string().nullish(),
  /** NodeKeySigned is true if our node is authorized by network-lock. */
  NodeKeySigned: z.boolean().default(false),
  /** NodeKeySignature is the current signature of this node's key. */
  NodeKeySignature: z.unknown().nullish(),
  /**
   * TrustedKeys describes the keys currently trusted to make changes
   * to network-lock.
   */
  TrustedKeys: goSlice(TKAKeySchema),
  /**
   * VisiblePeers describes peers which are visible in the netmap that
   * have valid Tailnet Lock signatures signatures.
   */
  VisiblePeers: goSlice(TKAPeerSchema),
  /**
   * FilteredPeers describes peers which were removed from the netmap
   * (i.e. no connectivity) because they failed tailnet lock
   * checks.
   */
  FilteredPeers: goSlice(TKAPeerSchema),
  /**
   * StateID is a nonce associated with the network lock authority,
   * generated upon enablement. This field is not populated if the
   * network lock is disabled.
   */
  StateID: int64.default(0),
});
export type NetworkLockStatus = z.infer<typeof NetworkLockStatusSchema>;

export const PeerStatusLiteSchema = z.object({
  /** NodeKey is this peer's public node key. */
  NodeKey: z.string().default(""),
  /**
   * TxBytes/RxBytes are the total number of bytes transmitted to/received
   * from this peer.
   */
  TxBytes: int64.default(0),
  /**
   * TxBytes/RxBytes are the total number of bytes transmitted to/received
   * from this peer.
   */
  RxBytes: int64.default(0),
  /**
   * LastHandshake is the last time a handshake succeeded with this peer. (Or
   * we got key confirmation via the first data message, which is
   * approximately the same thing.)
   * 
   * The time.Time zero value means that no handshake has succeeded, at least
   * since this peer was last known to WireGuard. (Tailscale removes peers
   * from the wireguard peer that are idle.)
   */
  LastHandshake: z.string().default(""),
});
export type PeerStatusLite = z.infer<typeof PeerStatusLiteSchema>;

/** Service represents a service running on a node. */
export const ServiceSchema = z.object({
  /**
   * Proto is the type of service. It's usually the constant TCP
   * or UDP ("tcp" or "udp"), but it can also be one of the
   * following meta service values:
   * 
   *     * "peerapi4": peerapi is available on IPv4; Port is the
   *        port number that the peerapi is running on the
   *        node's Tailscale IPv4 address.
   *     * "peerapi6": peerapi is available on IPv6; Port is the
   *        port number that the peerapi is running on the
   *        node's Tailscale IPv6 address.
   *     * "peerapi-dns-proxy": the local peerapi service supports
   *        being a DNS proxy (when the node is an exit
   *        node). For this service, the Port number must only be 1.
   */
  Proto: z.string().default(""),
  /**
   * Port is the port number.
   * 
   * For Proto "peerapi-dns", it must be 1.
   */
  Port: z.number().default(0),
  /**
   * Description is the textual description of the service,
   * usually the process name that's running.
   */
  Description: z.string().nullish(),
});
export type Service = z.infer<typeof ServiceSchema>;

/** NetInfo contains information about the host's network state. */
export const NetInfoSchema = z.object({
  /**
   * MappingVariesByDestIP says whether the host's NAT mappings
   * vary based on the destination IP.
   */
  MappingVariesByDestIP: z.boolean().nullish(),
  /** WorkingIPv6 is whether the host has IPv6 internet connectivity. */
  WorkingIPv6: z.boolean().nullish(),
  /**
   * OSHasIPv6 is whether the OS supports IPv6 at all, regardless of
   * whether IPv6 internet connectivity is available.
   */
  OSHasIPv6: z.boolean().nullish(),
  /** WorkingUDP is whether the host has UDP internet connectivity. */
  WorkingUDP: z.boolean().nullish(),
  /**
   * WorkingICMPv4 is whether ICMPv4 works.
   * Empty means not checked.
   */
  WorkingICMPv4: z.boolean().nullish(),
  /**
   * HavePortMap is whether we have an existing portmap open
   * (UPnP, PMP, or PCP).
   */
  HavePortMap: z.boolean().nullish(),
  /**
   * UPnP is whether UPnP appears present on the LAN.
   * Empty means not checked.
   */
  UPnP: z.boolean().nullish(),
  /**
   * PMP is whether NAT-PMP appears present on the LAN.
   * Empty means not checked.
   */
  PMP: z.boolean().nullish(),
  /**
   * PCP is whether PCP appears present on the LAN.
   * Empty means not checked.
   */
  PCP: z.boolean().nullish(),
  /**
   * PreferredDERP is this node's preferred (home) DERP region ID.
   * This is where the node expects to be contacted to begin a
   * peer-to-peer connection. The node might be be temporarily
   * connected to multiple DERP servers (to speak to other nodes
   * that are located elsewhere) but PreferredDERP is the region ID
   * that the node subscribes to traffic at.
   * Zero means disconnected or unknown.
   */
  PreferredDERP: int64.nullish(),
  /** LinkType is the current link type, if known. */
  LinkType: z.string().nullish(),
  /**
   * DERPLatency is the fastest recent time to reach various
   * DERP STUN servers, in seconds. The map key is the
   * "regionID-v4" or "-v6"; it was previously the DERP server's
   * STUN host:port.
   * 
   * This should only be updated rarely, or when there's a
   * material change, as any change here also gets uploaded to
   * the control plane.
   */
  DERPLatency: goMap(z.number()),
  /**
   * FirewallMode encodes both which firewall mode was selected and why.
   * It is Linux-specific (at least as of 2023-08-19) and is meant to help
   * debug iptables-vs-nftables issues. The string is of the form
   * "{nft,ift}-REASON", like "nft-forced" or "ipt-default". Empty means
   * either not Linux or a configuration in which the host firewall rules
   * are not managed by tailscaled.
   */
  FirewallMode: z.string().nullish(),
});
export type NetInfo = z.infer<typeof NetInfoSchema>;

/**
 * TPMInfo contains information about a TPM 2.0 device present on a node.
 * All fields are read from TPM_CAP_TPM_PROPERTIES, see Part 2, section 6.13 of
 * https://trustedcomputinggroup.org/resource/tpm-library-specification/.
 */
export const TPMInfoSchema = z.object({
  /**
   * Manufacturer is a 4-letter code from section 4.1 of
   * https://trustedcomputinggroup.org/resource/vendor-id-registry/,
   * for example "MSFT" for Microsoft.
   * Read from TPM_PT_MANUFACTURER.
   */
  Manufacturer: z.string().nullish(),
  /**
   * Vendor is a vendor ID string, up to 16 characters.
   * Read from TPM_PT_VENDOR_STRING_*.
   */
  Vendor: z.string().nullish(),
  /**
   * Model is a vendor-defined TPM model.
   * Read from TPM_PT_VENDOR_TPM_TYPE.
   */
  Model: int64.nullish(),
  /**
   * FirmwareVersion is the version number of the firmware.
   * Read from TPM_PT_FIRMWARE_VERSION_*.
   */
  FirmwareVersion: int64.nullish(),
  /**
   * SpecRevision is the TPM 2.0 spec revision encoded as a single number. All
   * revisions can be found at
   * https://trustedcomputinggroup.org/resource/tpm-library-specification/.
   * Before revision 184, TCG used the "01.83" format for revision 183.
   */
  SpecRevision: int64.nullish(),
  /**
   * FamilyIndicator is the TPM spec family, like "2.0".
   * Read from TPM_PT_FAMILY_INDICATOR.
   */
  FamilyIndicator: z.string().nullish(),
});
export type TPMInfo = z.infer<typeof TPMInfoSchema>;

/**
 * Hostinfo contains a summary of a Tailscale host.
 * 
 * Because it contains pointers (slices), this type should not be used
 * as a value type.
 */
export const HostinfoSchema = z.object({
  /** version of this code (in version.Long format) */
  IPNVersion: z.string().nullish(),
  /** logtail ID of frontend instance */
  FrontendLogID: z.string().nullish(),
  /** logtail ID of backend instance */
  BackendLogID: z.string().nullish(),
  /** operating system the client runs on (a version.OS value) */
  OS: z.string().nullish(),
  /**
   * OSVersion is the version of the OS, if available.
   * 
   * For Android, it's like "10", "11", "12", etc. For iOS and macOS it's like
   * "15.6.1" or "12.4.0". For Windows it's like "10.0.19044.1889". For
   * FreeBSD it's like "12.3-STABLE".
   * 
   * For Linux, prior to Tailscale 1.32, we jammed a bunch of fields into this
   * string on Linux, like "Debian 10.4; kernel=xxx; container; env=kn" and so
   * on. As of Tailscale 1.32, this is simply the kernel version on Linux, like
   * "5.10.0-17-amd64".
   */
  OSVersion: z.string().nullish(),
  /** best-effort whether the client is running in a container */
  Container: z.boolean().nullish(),
  /** a hostinfo.EnvType in string form */
  Env: z.string().nullish(),
  /** "debian", "ubuntu", "nixos", ... */
  Distro: z.string().nullish(),
  /** "20.04", ... */
  DistroVersion: z.string().nullish(),
  /** "jammy", "bullseye", ... */
  DistroCodeName: z.string().nullish(),
  /** App is used to disambiguate Tailscale clients that run using tsnet. */
  App: z.string().nullish(),
  /** if a desktop was detected on Linux */
  Desktop: z.boolean().nullish(),
  /** Tailscale package to disambiguate ("choco", "appstore", etc; "" for unknown) */
  Package: z.string().nullish(),
  /** mobile phone model ("Pixel 3a", "iPhone12,3") */
  DeviceModel: z.string().nullish(),
  /** macOS/iOS APNs device token for notifications (and Android in the future) */
  PushDeviceToken: z.string().nullish(),
  /** name of the host the client runs on */
  Hostname: z.string().nullish(),
  /** indicates whether the host is blocking incoming connections */
  ShieldsUp: z.boolean().nullish(),
  /** indicates this node exists in netmap because it's owned by a shared-to user */
  ShareeNode: z.boolean().nullish(),
  /** indicates that the user has opted out of sending logs and support */
  NoLogsNoSupport: z.boolean().nullish(),
  /**
   * WireIngress indicates that the node would like to be wired up server-side
   * (DNS, etc) to be able to use Tailscale Funnel, even if it's not currently
   * enabled. For example, the user might only use it for intermittent
   * foreground CLI serve sessions, for which they'd like it to work right
   * away, even if it's disabled most of the time. As an optimization, this is
   * only sent if IngressEnabled is false, as IngressEnabled implies that this
   * option is true.
   */
  WireIngress: z.boolean().nullish(),
  /** if the node has any funnel endpoint enabled */
  IngressEnabled: z.boolean().nullish(),
  /** indicates that the node has opted-in to admin-console-drive remote updates */
  AllowsUpdate: z.boolean().nullish(),
  /** the current host's machine type (uname -m) */
  Machine: z.string().nullish(),
  /** GOARCH value (of the built binary) */
  GoArch: z.string().nullish(),
  /** GOARM, GOAMD64, etc (of the built binary) */
  GoArchVar: z.string().nullish(),
  /** Go version binary was built with */
  GoVersion: z.string().nullish(),
  /** set of IP ranges this client can route */
  RoutableIPs: goSlice(z.string()),
  /** set of ACL tags this node wants to claim */
  RequestTags: goSlice(z.string()),
  /** MAC address(es) to send Wake-on-LAN packets to wake this node (lowercase hex w/ colons) */
  WoLMACs: goSlice(z.string()),
  /** services advertised by this machine */
  Services: goSlice(ServiceSchema),
  NetInfo: NetInfoSchema.nullish(),
  /** if advertised */
  sshHostKeys: goSlice(z.string()),
  Cloud: z.string().nullish(),
  /** if the client is running in userspace (netstack) mode */
  Userspace: z.boolean().nullish(),
  /** if the client's subnet router is running in userspace (netstack) mode */
  UserspaceRouter: z.boolean().nullish(),
  /** if the client is running the app-connector service */
  AppConnector: z.boolean().nullish(),
  /** opaque hash of the most recent list of tailnet services, change in hash indicates config should be fetched via c2n */
  ServicesHash: z.string().nullish(),
  /** the client’s selected exit node, empty when unselected. */
  ExitNodeID: z.string().nullish(),
  /**
   * Location represents geographical location data about a
   * Tailscale host. Location is optional and only set if
   * explicitly declared by a node.
   */
  Location: LocationSchema.nullish(),
  /** TPM device metadata, if available */
  TPM: TPMInfoSchema.nullish(),
  /**
   * StateEncrypted reports whether the node state is stored encrypted on
   * disk. The actual mechanism is platform-specific:
   *   * Apple nodes use the Keychain
   *   * Linux and Windows nodes use the TPM
   *   * Android apps use EncryptedSharedPreferences
   */
  StateEncrypted: z.boolean().nullish(),
});
export type Hostinfo = z.infer<typeof HostinfoSchema>;

/** Resolver is the configuration for one DNS resolver. */
export const ResolverSchema = z.object({
  /**
   * Addr is the address of the DNS resolver, one of:
   *  - A plain IP address for a "classic" UDP+TCP DNS resolver.
   *    This is the common format as sent by the control plane.
   *  - An IP:port, for tests.
   *  - "https://resolver.com/path" for DNS over HTTPS; currently
   *    as of 2022-09-08 only used for certain well-known resolvers
   *    (see the publicdns package) for which the IP addresses to dial DoH are
   *    known ahead of time, so bootstrap DNS resolution is not required.
   *  - "http://node-address:port/path" for DNS over HTTP over WireGuard. This
   *    is implemented in the PeerAPI for exit nodes and app connectors.
   *  - [TODO] "tls://resolver.com" for DNS over TCP+TLS
   */
  Addr: z.string().nullish(),
  /**
   * BootstrapResolution is an optional suggested resolution for the
   * DoT/DoH resolver, if the resolver URL does not reference an IP
   * address directly.
   * BootstrapResolution may be empty, in which case clients should
   * look up the DoT/DoH server using their local "classic" DNS
   * resolver.
   * 
   * As of 2022-09-08, BootstrapResolution is not yet used.
   */
  BootstrapResolution: goSlice(z.string()),
  /**
   * UseWithExitNode designates that this resolver should continue to be used when an
   * exit node is in use. Normally, DNS resolution is delegated to the exit node but
   * there are situations where it is preferable to still use a Split DNS server and/or
   * global DNS server instead of the exit node.
   */
  UseWithExitNode: z.boolean().nullish(),
});
export type Resolver = z.infer<typeof ResolverSchema>;

/** Node is a Tailscale device in a tailnet. */
export const NodeSchema = z.object({
  ID: int64.default(0),
  StableID: z.string().default(""),
  /**
   * Name is the FQDN of the node.
   * It is also the MagicDNS name for the node.
   * It has a trailing dot.
   * e.g. "host.tail-scale.ts.net."
   */
  Name: z.string().default(""),
  /**
   * User is the user who created the node. If ACL tags are in use for the
   * node then it doesn't reflect the ACL identity that the node is running
   * as.
   */
  User: int64.default(0),
  /** Sharer, if non-zero, is the user who shared this node, if different than User. */
  Sharer: int64.nullish(),
  Key: z.string().default(""),
  /** the zero value if this node does not expire */
  KeyExpiry: z.string().nullish(),
  KeySignature: z.string().nullish(),
  Machine: z.string().nullish(),
  DiscoKey: z.string().nullish(),
  /** Addresses are the IP addresses of this Node directly. */
  Addresses: goSlice(z.string()),
  /**
   * AllowedIPs are the IP ranges to route to this node.
   * 
   * As of CapabilityVersion 112, this may be nil (null or undefined) on the wire
   * to mean the same as Addresses. Internally, it is always filled in with
   * its possibly-implicit value.
   */
  AllowedIPs: goSlice(z.string()),
  /** IP+port (public via STUN, and local LANs) */
  Endpoints: goSlice(z.string()),
  /**
   * LegacyDERPString is this node's home LegacyDERPString region ID integer, but shoved into an
   * IP:port string for legacy reasons. The IP address is always "127.3.3.40"
   * (a loopback address (127) followed by the digits over the letters DERP on
   * a QWERTY keyboard (3.3.40)). The "port number" is the home LegacyDERPString region ID
   * integer.
   * 
   * Deprecated: HomeDERP has replaced this, but old servers might still send
   * this field. See tailscale/tailscale#14636. Do not use this field in code
   * other than in the upgradeNode func, which canonicalizes it to HomeDERP
   * if it arrives as a LegacyDERPString string on the wire.
   */
  DERP: z.string().nullish(),
  /**
   * HomeDERP is the modern version of the DERP string field, with just an
   * integer. The client advertises support for this as of capver 111.
   * 
   * HomeDERP may be zero if not (yet) known, but ideally always be non-zero
   * for magicsock connectivity to function normally.
   */
  HomeDERP: int64.nullish(),
  Hostinfo: HostinfoSchema.nullish(),
  Created: z.string().nullish(),
  /** if non-zero, the node's capability version; old servers might not send */
  Cap: int64.nullish(),
  /**
   * Tags are the list of ACL tags applied to this node.
   * Tags take the form of `tag:<value>` where value starts
   * with a letter and only contains alphanumerics and dashes `-`.
   * Some valid tag examples:
   *   `tag:prod`
   *   `tag:database`
   *   `tag:lab-1`
   */
  Tags: goSlice(z.string()),
  /**
   * PrimaryRoutes are the routes from AllowedIPs that this node
   * is currently the primary subnet router for, as determined
   * by the control plane. It does not include the self address
   * values from Addresses that are in AllowedIPs.
   */
  PrimaryRoutes: goSlice(z.string()),
  /**
   * LastSeen is when the node was last online. It is not
   * updated when Online is true. It is nil if the current
   * node doesn't have permission to know, or the node
   * has never been online.
   */
  LastSeen: z.string().nullish(),
  /**
   * Online is whether the node is currently connected to the
   * coordination server.  A value of nil means unknown, or the
   * current node doesn't have permission to know.
   */
  Online: z.boolean().nullish(),
  /** TODO(crawshaw): replace with MachineStatus */
  MachineAuthorized: z.boolean().nullish(),
  /**
   * Capabilities are capabilities that the node has.
   * They're free-form strings, but should be in the form of URLs/URIs
   * such as:
   *    "https://tailscale.com/cap/is-admin"
   *    "https://tailscale.com/cap/file-sharing"
   * 
   * Deprecated: use CapMap instead. See https://github.com/tailscale/tailscale/issues/11508
   */
  Capabilities: goSlice(z.string()),
  /**
   * CapMap is a map of capabilities to their optional argument/data values.
   * 
   * It is valid for a capability to not have any argument/data values; such
   * capabilities can be tested for using the HasCap method. These type of
   * capabilities are used to indicate that a node has a capability, but there
   * is no additional data associated with it. These were previously
   * represented by the Capabilities field, but can now be represented by
   * CapMap with an empty value.
   * 
   * See NodeCapability for more information on keys.
   * 
   * Metadata about nodes can be transmitted in 3 ways:
   * 1. MapResponse.Node.CapMap describes attributes that affect behavior for
   *    this node, such as which features have been enabled through the admin
   *    panel and any associated configuration details.
   * 2. MapResponse.PacketFilter(s) describes access (both IP and application
   *    based) that should be granted to peers.
   * 3. MapResponse.Peers[].CapMap describes attributes regarding a peer node,
   *    such as which features the peer supports or if that peer is preferred
   *    for a particular task vs other peers that could also be chosen.
   */
  CapMap: goMap(goSlice(z.unknown())),
  /**
   * UnsignedPeerAPIOnly means that this node is not signed nor subject to TKA
   * restrictions. However, in exchange for that privilege, it does not get
   * network access. It can only access this node's peerapi, which may not let
   * it do anything. It is the tailscaled client's job to double-check the
   * MapResponse's PacketFilter to verify that its AllowedIPs will not be
   * accepted by the packet filter.
   */
  UnsignedPeerAPIOnly: z.boolean().nullish(),
  /** MagicDNS base name (for normal non-shared-in nodes), FQDN (without trailing dot, for shared-in nodes), or Hostname (if no MagicDNS) */
  ComputedName: z.string().nullish(),
  /** either "ComputedName" or "ComputedName (computedHostIfDifferent)", if computedHostIfDifferent is set */
  ComputedNameWithHost: z.string().nullish(),
  /** DataPlaneAuditLogID is the per-node logtail ID used for data plane audit logging. */
  DataPlaneAuditLogID: z.string().nullish(),
  /**
   * Expired is whether this node's key has expired. Control may send
   * this; clients are only allowed to set this from false to true. On
   * the client, this is calculated client-side based on a timestamp sent
   * from control, to avoid clock skew issues.
   */
  Expired: z.boolean().nullish(),
  /**
   * SelfNodeV4MasqAddrForThisPeer is the IPv4 that this peer knows the current node as.
   * It may be empty if the peer knows the current node by its native
   * IPv4 address.
   * This field is only populated in a MapResponse for peers and not
   * for the current node.
   * 
   * If set, it should be used to masquerade traffic originating from the
   * current node to this peer. The masquerade address is only relevant
   * for this peer and not for other peers.
   * 
   * This only applies to traffic originating from the current node to the
   * peer or any of its subnets. Traffic originating from subnet routes will
   * not be masqueraded (e.g. in case of --snat-subnet-routes).
   */
  SelfNodeV4MasqAddrForThisPeer: z.string().nullish(),
  /**
   * SelfNodeV6MasqAddrForThisPeer is the IPv6 that this peer knows the current node as.
   * It may be empty if the peer knows the current node by its native
   * IPv6 address.
   * This field is only populated in a MapResponse for peers and not
   * for the current node.
   * 
   * If set, it should be used to masquerade traffic originating from the
   * current node to this peer. The masquerade address is only relevant
   * for this peer and not for other peers.
   * 
   * This only applies to traffic originating from the current node to the
   * peer or any of its subnets. Traffic originating from subnet routes will
   * not be masqueraded (e.g. in case of --snat-subnet-routes).
   */
  SelfNodeV6MasqAddrForThisPeer: z.string().nullish(),
  /**
   * IsWireGuardOnly indicates that this is a non-Tailscale WireGuard peer, it
   * is not expected to speak Disco or DERP, and it must have Endpoints in
   * order to be reachable.
   */
  IsWireGuardOnly: z.boolean().nullish(),
  /**
   * IsJailed indicates that this node is jailed and should not be allowed
   * initiate connections, however outbound connections to it should still be
   * allowed.
   */
  IsJailed: z.boolean().nullish(),
  /**
   * ExitNodeDNSResolvers is the list of DNS servers that should be used when this
   * node is marked IsWireGuardOnly and being used as an exit node.
   */
  ExitNodeDNSResolvers: goSlice(ResolverSchema),
});
export type Node = z.infer<typeof NodeSchema>;

/**
 * DERPHomeParams contains parameters from the server related to selecting a
 * DERP home region (sometimes referred to as the "preferred DERP").
 */
export const DERPHomeParamsSchema = z.object({
  /**
   * RegionScore scales latencies of DERP regions by a given scaling
   * factor when determining which region to use as the home
   * ("preferred") DERP. Scores in the range (0, 1) will cause this
   * region to be proportionally more preferred, and scores in the range
   * (1, ∞) will penalize a region.
   * 
   * If a region is not present in this map, it is treated as having a
   * score of 1.0.
   * 
   * Scores should not be 0 or negative; such scores will be ignored.
   * 
   * A nil map means no change from the previous value (if any); an empty
   * non-nil map can be sent to reset all scores back to 1.0.
   */
  RegionScore: goMap(z.number()),
});
export type DERPHomeParams = z.infer<typeof DERPHomeParamsSchema>;

/** DERPNode describes a DERP packet relay node running within a DERPRegion. */
export const DERPNodeSchema = z.object({
  /**
   * Name is a unique node name (across all regions).
   * It is not a host name.
   * It's typically of the form "1b", "2a", "3b", etc. (region
   * ID + suffix within that region)
   */
  Name: z.string().default(""),
  /**
   * RegionID is the RegionID of the DERPRegion that this node
   * is running in.
   */
  RegionID: int64.default(0),
  /**
   * HostName is the DERP node's hostname.
   * 
   * It is required but need not be unique; multiple nodes may
   * have the same HostName but vary in configuration otherwise.
   */
  HostName: z.string().default(""),
  /**
   * CertName optionally specifies the expected TLS cert common
   * name. If empty, HostName is used. If CertName is non-empty,
   * HostName is only used for the TCP dial (if IPv4/IPv6 are
   * not present) + TLS ClientHello.
   * 
   * As a special case, if CertName starts with "sha256-raw:",
   * then the rest of the string is a hex-encoded SHA256 of the
   * cert to expect. This is used for self-signed certs.
   * In this case, the HostName field will typically be an IP
   * address literal.
   */
  CertName: z.string().nullish(),
  /**
   * IPv4 optionally forces an IPv4 address to use, instead of using DNS.
   * If empty, A record(s) from DNS lookups of HostName are used.
   * If the string is not an IPv4 address, IPv4 is not used; the
   * conventional string to disable IPv4 (and not use DNS) is
   * "none".
   */
  IPv4: z.string().nullish(),
  /**
   * IPv6 optionally forces an IPv6 address to use, instead of using DNS.
   * If empty, AAAA record(s) from DNS lookups of HostName are used.
   * If the string is not an IPv6 address, IPv6 is not used; the
   * conventional string to disable IPv6 (and not use DNS) is
   * "none".
   */
  IPv6: z.string().nullish(),
  /**
   * Port optionally specifies a STUN port to use.
   * Zero means 3478.
   * To disable STUN on this node, use -1.
   */
  STUNPort: int64.nullish(),
  /**
   * STUNOnly marks a node as only a STUN server and not a DERP
   * server.
   */
  STUNOnly: z.boolean().nullish(),
  /**
   * DERPPort optionally provides an alternate TLS port number
   * for the DERP HTTPS server.
   * 
   * If zero, 443 is used.
   */
  DERPPort: int64.nullish(),
  /**
   * InsecureForTests is used by unit tests to disable TLS verification.
   * It should not be set by users.
   */
  InsecureForTests: z.boolean().nullish(),
  /**
   * STUNTestIP is used in tests to override the STUN server's IP.
   * If empty, it's assumed to be the same as the DERP server.
   */
  STUNTestIP: z.string().nullish(),
  /**
   * CanPort80 specifies whether this DERP node is accessible over HTTP
   * on port 80 specifically. This is used for captive portal checks.
   */
  CanPort80: z.boolean().nullish(),
});
export type DERPNode = z.infer<typeof DERPNodeSchema>;

/**
 * DERPRegion is a geographic region running DERP relay node(s).
 * 
 * Client nodes discover which region they're closest to, advertise
 * that "home" DERP region (previously called "home node", when there
 * was only 1 node per region) and maintain a persistent connection
 * that region as long as it's the closest. Client nodes will further
 * connect to other regions as necessary to communicate with peers
 * advertising other regions as their homes.
 */
export const DERPRegionSchema = z.object({
  /**
   * RegionID is a unique integer for a geographic region.
   * 
   * It corresponds to the legacy derpN.tailscale.com hostnames
   * used by older clients. (Older clients will continue to resolve
   * derpN.tailscale.com when contacting peers, rather than use
   * the server-provided DERPMap)
   * 
   * RegionIDs must be non-zero, positive, and guaranteed to fit
   * in a JavaScript number.
   * 
   * RegionIDs in range 900-999 are reserved for end users to run their
   * own DERP nodes.
   */
  RegionID: int64.default(0),
  /**
   * RegionCode is a short name for the region. It's usually a popular
   * city or airport code in the region: "nyc", "sf", "sin",
   * "fra", etc.
   */
  RegionCode: z.string().default(""),
  /**
   * RegionName is a long English name for the region: "New York City",
   * "San Francisco", "Singapore", "Frankfurt", etc.
   */
  RegionName: z.string().default(""),
  /** Latitude, Longitude are optional geographical coordinates of the DERP region's city, in degrees. */
  Latitude: z.number().nullish(),
  Longitude: z.number().nullish(),
  /**
   * Avoid is whether the client should avoid picking this as its home region.
   * The region should only be used if a peer is there. Clients already using
   * this region as their home should migrate away to a new region without
   * Avoid set.
   * 
   * Deprecated: because of bugs in past implementations combined with unclear
   * docs that caused people to think the bugs were intentional, this field is
   * deprecated. It was never supposed to cause STUN/DERP measurement probes,
   * but due to bugs, it sometimes did. And then some parts of the code began
   * to rely on that property. But then we were unable to use this field for
   * its original purpose, nor its later imagined purpose, because various
   * parts of the codebase thought it meant one thing and others thought it
   * meant another. But it did something in the middle instead. So we're retiring
   * it. Use NoMeasureNoHome instead.
   */
  Avoid: z.boolean().nullish(),
  /**
   * NoMeasureNoHome says that this regions should not be measured for its
   * latency distance (STUN, HTTPS, etc) or availability (e.g. captive portal
   * checks) and should never be selected as the node's home region. However,
   * if a peer declares this region as its home, then this client is allowed
   * to connect to it for the purpose of communicating with that peer.
   * 
   * This is what the now deprecated Avoid bool was supposed to mean
   * originally but had implementation bugs and documentation omissions.
   */
  NoMeasureNoHome: z.boolean().nullish(),
  /**
   * Nodes are the DERP nodes running in this region, in
   * priority order for the current client. Client TLS
   * connections should ideally only go to the first entry
   * (falling back to the second if necessary). STUN packets
   * should go to the first 1 or 2.
   * 
   * If nodes within a region route packets amongst themselves,
   * but not to other regions. That said, each user/domain
   * should get a the same preferred node order, so if all nodes
   * for a user/network pick the first one (as they should, when
   * things are healthy), the inter-cluster routing is minimal
   * to zero.
   */
  Nodes: goSlice(DERPNodeSchema),
});
export type DERPRegion = z.infer<typeof DERPRegionSchema>;

/** DERPMap describes the set of DERP packet relay servers that are available. */
export const DERPMapSchema = z.object({
  /**
   * HomeParams, if non-nil, is a change in home parameters.
   * 
   * The rest of the DEPRMap fields, if zero, means unchanged.
   */
  HomeParams: DERPHomeParamsSchema.nullish(),
  /**
   * Regions is the set of geographic regions running DERP node(s).
   * 
   * It's keyed by the DERPRegion.RegionID.
   * 
   * The numbers are not necessarily contiguous.
   */
  Regions: goMap(DERPRegionSchema),
  /**
   * OmitDefaultRegions specifies to not use Tailscale's DERP servers, and only use those
   * specified in this DERPMap. If there are none set outside of the defaults, this is a noop.
   * 
   * This field is only meaningful if the Regions map is non-nil (indicating a change).
   */
  omitDefaultRegions: z.boolean().nullish(),
});
export type DERPMap = z.infer<typeof DERPMapSchema>;

/** PortRange represents a range of UDP or TCP port numbers. */
export const PortRangeSchema = z.object({
  First: z.number().default(0),
  Last: z.number().default(0),
});
export type PortRange = z.infer<typeof PortRangeSchema>;

/**
 * ProtoPortRange is used to encode "proto:port" format.
 * The following formats are supported:
 * 
 * 	"*" allows all TCP, UDP and ICMP traffic on all ports.
 * 	"<ports>" allows all TCP, UDP and ICMP traffic on the specified ports.
 * 	"proto:*" allows traffic of the specified proto on all ports.
 * 	"proto:<port>" allows traffic of the specified proto on the specified port.
 * 
 * Ports are either a single port number or a range of ports (e.g. "80-90").
 * String named protocols support names that ipproto.Proto accepts.
 */
export const ProtoPortRangeSchema = z.object({
  /**
   * Proto is the IP protocol number.
   * If Proto is 0, it means TCP+UDP+ICMP(4+6).
   */
  Proto: int64.default(0),
  Ports: PortRangeSchema.default({}),
});
export type ProtoPortRange = z.infer<typeof ProtoPortRangeSchema>;

/**
 * VIPService represents a service created on a tailnet from the
 * perspective of a node providing that service. These services
 * have an virtual IP (VIP) address pair distinct from the node's IPs.
 */
export const VIPServiceSchema = z.object({
  /**
   * Name is the name of the service. The Name uniquely identifies a service
   * on a particular tailnet, and so also corresponds uniquely to the pair of
   * IP addresses belonging to the VIP service.
   */
  Name: z.string().default(""),
  /**
   * Ports specify which ProtoPorts are made available by this node
   * on the service's IPs.
   */
  Ports: goSlice(ProtoPortRangeSchema),
  /**
   * Active specifies whether new requests for the service should be
   * sent to this node by control.
   */
  Active: z.boolean().default(false),
});
export type VIPService = z.infer<typeof VIPServiceSchema>;

/** AutoUpdatePrefs are the auto update settings for the node agent. */
export const AutoUpdatePrefsSchema = z.object({
  /**
   * Check specifies whether background checks for updates are enabled. When
   * enabled, tailscaled will periodically check for available updates and
   * notify the user about them.
   */
  Check: z.boolean().default(false),
  /**
   * Apply specifies whether background auto-updates are enabled. When
   * enabled, tailscaled will apply available updates in the background.
   * Check must also be set when Apply is set.
   */
  Apply: z.boolean().nullish(),
});
export type AutoUpdatePrefs = z.infer<typeof AutoUpdatePrefsSchema>;

/** AppConnectorPrefs are the app connector settings for the node agent. */
export const AppConnectorPrefsSchema = z.object({
  /**
   * Advertise specifies whether the app connector subsystem is advertising
   * this node as a connector.
   */
  Advertise: z.boolean().default(false),
});
export type AppConnectorPrefs = z.infer<typeof AppConnectorPrefsSchema>;

/**
 * Prefs are the user modifiable settings of the Tailscale node agent.
 * When you add a Pref to this struct, remember to add a corresponding
 * field in MaskedPrefs, and check your field for equality in Prefs.Equals().
 */
export const PrefsSchema = z.object({
  /**
   * ControlURL is the URL of the control server to use.
   * 
   * If empty, the default for new installs, DefaultControlURL
   * is used. It's set non-empty once the daemon has been started
   * for the first time.
   * 
   * TODO(apenwarr): Make it safe to update this with EditPrefs().
   * Right now, you have to pass it in the initial prefs in Start(),
   * which is the only code that actually uses the ControlURL value.
   * It would be more consistent to restart controlclient
   * automatically whenever this variable changes.
   * 
   * Meanwhile, you have to provide this as part of
   * Options.LegacyMigrationPrefs or Options.UpdatePrefs when
   * calling Backend.Start().
   */
  ControlURL: z.string().default(""),
  /**
   * RouteAll specifies whether to accept subnets advertised by
   * other nodes on the Tailscale network. Note that this does not
   * include default routes (0.0.0.0/0 and ::/0), those are
   * controlled by ExitNodeID/IP below.
   */
  RouteAll: z.boolean().default(false),
  /**
   * ExitNodeID and ExitNodeIP specify the node that should be used
   * as an exit node for internet traffic. At most one of these
   * should be non-zero.
   * 
   * The preferred way to express the chosen node is ExitNodeID, but
   * in some cases it's not possible to use that ID (e.g. in the
   * linux CLI, before tailscaled has a netmap). For those
   * situations, we allow specifying the exit node by IP, and
   * ipnlocal.LocalBackend will translate the IP into an ID when the
   * node is found in the netmap.
   * 
   * If the selected exit node doesn't exist (e.g. it's not part of
   * the current tailnet), or it doesn't offer exit node services, a
   * blackhole route will be installed on the local system to
   * prevent any traffic escaping to the local network.
   */
  ExitNodeID: z.string().default(""),
  ExitNodeIP: z.string().default(""),
  /**
   * AutoExitNode is an optional expression that specifies whether and how
   * tailscaled should pick an exit node automatically.
   * 
   * If specified, tailscaled will use an exit node based on the expression,
   * and will re-evaluate the selection periodically as network conditions,
   * available exit nodes, or policy settings change. A blackhole route will
   * be installed to prevent traffic from escaping to the local network until
   * an exit node is selected. It takes precedence over ExitNodeID and ExitNodeIP.
   * 
   * If empty, tailscaled will not automatically select an exit node.
   * 
   * If the specified expression is invalid or unsupported by the client,
   * it falls back to the behavior of [AnyExitNode].
   * 
   * As of 2025-07-02, the only supported value is [AnyExitNode].
   * It's a string rather than a boolean to allow future extensibility
   * (e.g., AutoExitNode = "mullvad" or AutoExitNode = "geo:us").
   */
  AutoExitNode: z.string().nullish(),
  /**
   * InternalExitNodePrior is the most recently used ExitNodeID in string form. It is set by
   * the backend on transition from exit node on to off and used by the
   * backend.
   * 
   * As an Internal field, it can't be set by LocalAPI clients, rather it is set indirectly
   * when the ExitNodeID value is zero'd and via the set-use-exit-node-enabled endpoint.
   */
  InternalExitNodePrior: z.string().default(""),
  /**
   * ExitNodeAllowLANAccess indicates whether locally accessible subnets should be
   * routed directly or via the exit node.
   */
  ExitNodeAllowLANAccess: z.boolean().default(false),
  /**
   * CorpDNS specifies whether to install the Tailscale network's
   * DNS configuration, if it exists.
   */
  CorpDNS: z.boolean().default(false),
  /**
   * RunSSH bool is whether this node should run an SSH
   * server, permitting access to peers according to the
   * policies as configured by the Tailnet's admin(s).
   */
  RunSSH: z.boolean().default(false),
  /**
   * RunWebClient bool is whether this node should expose
   * its web client over Tailscale at port 5252,
   * permitting access to peers according to the
   * policies as configured by the Tailnet's admin(s).
   */
  RunWebClient: z.boolean().default(false),
  /**
   * WantRunning indicates whether networking should be active on
   * this node.
   */
  WantRunning: z.boolean().default(false),
  /**
   * LoggedOut indicates whether the user intends to be logged out.
   * There are other reasons we may be logged out, including no valid
   * keys.
   * We need to remember this state so that, on next startup, we can
   * generate the "Login" vs "Connect" buttons correctly, without having
   * to contact the server to confirm our nodekey status first.
   */
  LoggedOut: z.boolean().default(false),
  /**
   * ShieldsUp indicates whether to block all incoming connections,
   * regardless of the control-provided packet filter. If false, we
   * use the packet filter as provided. If true, we block incoming
   * connections. This overrides tailcfg.Hostinfo's ShieldsUp.
   */
  ShieldsUp: z.boolean().default(false),
  /**
   * AdvertiseTags specifies tags that should be applied to this node, for
   * purposes of ACL enforcement. These can be referenced from the ACL policy
   * document. Note that advertising a tag on the client doesn't guarantee
   * that the control server will allow the node to adopt that tag.
   */
  AdvertiseTags: goSlice(z.string()),
  /**
   * Hostname is the hostname to use for identifying the node. If
   * not set, os.Hostname is used.
   */
  Hostname: z.string().default(""),
  /**
   * NotepadURLs is a debugging setting that opens OAuth URLs in
   * notepad.exe on Windows, rather than loading them in a browser.
   * 
   * apenwarr 2020-04-29: Unfortunately this is still needed sometimes.
   * Windows' default browser setting is sometimes screwy and this helps
   * users narrow it down a bit.
   */
  NotepadURLs: z.boolean().default(false),
  /**
   * ForceDaemon specifies whether a platform that normally
   * operates in "client mode" (that is, requires an active user
   * logged in with the GUI app running) should keep running after the
   * GUI ends and/or the user logs out.
   * 
   * The only current applicable platform is Windows. This
   * forced Windows to go into "server mode" where Tailscale is
   * running even with no users logged in. This might also be
   * used for macOS in the future. This setting has no effect
   * for Linux/etc, which always operate in daemon mode.
   */
  ForceDaemon: z.boolean().nullish(),
  /** Egg is a optional debug flag. */
  Egg: z.boolean().nullish(),
  /**
   * AdvertiseRoutes specifies CIDR prefixes to advertise into the
   * Tailscale network as reachable through the current
   * node.
   */
  AdvertiseRoutes: goSlice(z.string()),
  /**
   * AdvertiseServices specifies the list of services that this
   * node can serve as a destination for. Note that an advertised
   * service must still go through the approval process from the
   * control server.
   */
  AdvertiseServices: goSlice(z.string()),
  /**
   * Sync is whether this node should sync its configuration from
   * the control plane. If unset, this defaults to true.
   * This exists primarily for testing, to verify that netmap caching
   * and offline operation work correctly.
   */
  Sync: z.boolean().nullish(),
  /**
   * NoSNAT specifies whether to source NAT traffic going to
   * destinations in AdvertiseRoutes. The default is to apply source
   * NAT, which makes the traffic appear to come from the router
   * machine rather than the peer's Tailscale IP.
   * 
   * Disabling SNAT requires additional manual configuration in your
   * network to route Tailscale traffic back to the subnet relay
   * machine.
   * 
   * Linux-only.
   */
  NoSNAT: z.boolean().default(false),
  /**
   * NoStatefulFiltering specifies whether to apply stateful filtering when
   * advertising routes in AdvertiseRoutes. The default is to not apply
   * stateful filtering.
   * 
   * To allow inbound connections from advertised routes, both NoSNAT and
   * NoStatefulFiltering must be true.
   * 
   * This is an opt.Bool because it was first added after NoSNAT, with a
   * backfill based on the value of that parameter. The backfill has been
   * removed since then, but the field remains an opt.Bool.
   * 
   * Linux-only.
   */
  NoStatefulFiltering: z.boolean().nullish(),
  /**
   * NetfilterMode specifies how much to manage netfilter rules for
   * Tailscale, if at all.
   */
  NetfilterMode: int64.default(0),
  /**
   * OperatorUser is the local machine user name who is allowed to
   * operate tailscaled without being root or using sudo.
   */
  OperatorUser: z.string().nullish(),
  /**
   * ProfileName is the desired name of the profile. If empty, then the user's
   * LoginName is used. It is only used for display purposes in the client UI
   * and CLI.
   */
  ProfileName: z.string().nullish(),
  /**
   * AutoUpdate sets the auto-update preferences for the node agent. See
   * AutoUpdatePrefs docs for more details.
   */
  AutoUpdate: AutoUpdatePrefsSchema.default({}),
  /**
   * AppConnector sets the app connector preferences for the node agent. See
   * AppConnectorPrefs docs for more details.
   */
  AppConnector: AppConnectorPrefsSchema.default({}),
  /**
   * PostureChecking enables the collection of information used for device
   * posture checks.
   * 
   * Note: this should be named ReportPosture, but it was shipped as
   * PostureChecking in some early releases and this JSON field is written to
   * disk, so we just keep its old name. (akin to CorpDNS which is an internal
   * pref name that doesn't match the public interface)
   */
  PostureChecking: z.boolean().default(false),
  /**
   * NetfilterKind specifies what netfilter implementation to use.
   * 
   * It can be "iptables", "nftables", or "" to auto-detect.
   * 
   * Linux-only.
   */
  NetfilterKind: z.string().default(""),
  /**
   * DriveShares are the configured DriveShares, stored in increasing order
   * by name.
   */
  DriveShares: goSlice(z.unknown()),
  /**
   * RelayServerPort is the UDP port number for the relay server to bind to,
   * on all interfaces. A non-nil zero value signifies a random unused port
   * should be used. A nil value signifies relay server functionality
   * should be disabled.
   */
  RelayServerPort: z.number().nullish(),
  /**
   * RelayServerStaticEndpoints are static IP:port endpoints to advertise as
   * candidates for relay connections. Only relevant when RelayServerPort is
   * non-nil.
   */
  RelayServerStaticEndpoints: goSlice(z.string()),
  /**
   * AllowSingleHosts was a legacy field that was always true
   * for the past 4.5 years. It controlled whether Tailscale
   * peers got /32 or /128 routes for each other.
   * As of 2024-05-17 we're starting to ignore it, but to let
   * people still downgrade Tailscale versions and not break
   * all peer-to-peer networking we still write it to disk (as JSON)
   * so it can be loaded back by old versions.
   * TODO(bradfitz): delete this in 2025 sometime. See #12058.
   */
  AllowSingleHosts: z.unknown(),
  /**
   * The Persist field is named 'Config' in the file for backward
   * compatibility with earlier versions.
   * TODO(apenwarr): We should move this out of here, it's not a pref.
   *  We can maybe do that once we're sure which module should persist
   *  it (backend or frontend?)
   */
  Config: z.unknown().nullish(),
});
export type Prefs = z.infer<typeof PrefsSchema>;

export const AutoUpdatePrefsMaskSchema = z.object({
  CheckSet: z.boolean().nullish(),
  ApplySet: z.boolean().nullish(),
});
export type AutoUpdatePrefsMask = z.infer<typeof AutoUpdatePrefsMaskSchema>;

/**
 * MaskedPrefs is a Prefs with an associated bitmask of which fields are set.
 * 
 * Each FooSet field maps to a corresponding Foo field in Prefs. FooSet can be
 * a struct, in which case inner fields of FooSet map to inner fields of Foo in
 * Prefs (see AutoUpdateSet for example).
 */
export const MaskedPrefsSchema = z.object({
  /**
   * ControlURL is the URL of the control server to use.
   * 
   * If empty, the default for new installs, DefaultControlURL
   * is used. It's set non-empty once the daemon has been started
   * for the first time.
   * 
   * TODO(apenwarr): Make it safe to update this with EditPrefs().
   * Right now, you have to pass it in the initial prefs in Start(),
   * which is the only code that actually uses the ControlURL value.
   * It would be more consistent to restart controlclient
   * automatically whenever this variable changes.
   * 
   * Meanwhile, you have to provide this as part of
   * Options.LegacyMigrationPrefs or Options.UpdatePrefs when
   * calling Backend.Start().
   */
  ControlURL: z.string().default(""),
  /**
   * RouteAll specifies whether to accept subnets advertised by
   * other nodes on the Tailscale network. Note that this does not
   * include default routes (0.0.0.0/0 and ::/0), those are
   * controlled by ExitNodeID/IP below.
   */
  RouteAll: z.boolean().default(false),
  /**
   * ExitNodeID and ExitNodeIP specify the node that should be used
   * as an exit node for internet traffic. At most one of these
   * should be non-zero.
   * 
   * The preferred way to express the chosen node is ExitNodeID, but
   * in some cases it's not possible to use that ID (e.g. in the
   * linux CLI, before tailscaled has a netmap). For those
   * situations, we allow specifying the exit node by IP, and
   * ipnlocal.LocalBackend will translate the IP into an ID when the
   * node is found in the netmap.
   * 
   * If the selected exit node doesn't exist (e.g. it's not part of
   * the current tailnet), or it doesn't offer exit node services, a
   * blackhole route will be installed on the local system to
   * prevent any traffic escaping to the local network.
   */
  ExitNodeID: z.string().default(""),
  ExitNodeIP: z.string().default(""),
  /**
   * AutoExitNode is an optional expression that specifies whether and how
   * tailscaled should pick an exit node automatically.
   * 
   * If specified, tailscaled will use an exit node based on the expression,
   * and will re-evaluate the selection periodically as network conditions,
   * available exit nodes, or policy settings change. A blackhole route will
   * be installed to prevent traffic from escaping to the local network until
   * an exit node is selected. It takes precedence over ExitNodeID and ExitNodeIP.
   * 
   * If empty, tailscaled will not automatically select an exit node.
   * 
   * If the specified expression is invalid or unsupported by the client,
   * it falls back to the behavior of [AnyExitNode].
   * 
   * As of 2025-07-02, the only supported value is [AnyExitNode].
   * It's a string rather than a boolean to allow future extensibility
   * (e.g., AutoExitNode = "mullvad" or AutoExitNode = "geo:us").
   */
  AutoExitNode: z.string().nullish(),
  /**
   * InternalExitNodePrior is the most recently used ExitNodeID in string form. It is set by
   * the backend on transition from exit node on to off and used by the
   * backend.
   * 
   * As an Internal field, it can't be set by LocalAPI clients, rather it is set indirectly
   * when the ExitNodeID value is zero'd and via the set-use-exit-node-enabled endpoint.
   */
  InternalExitNodePrior: z.string().default(""),
  /**
   * ExitNodeAllowLANAccess indicates whether locally accessible subnets should be
   * routed directly or via the exit node.
   */
  ExitNodeAllowLANAccess: z.boolean().default(false),
  /**
   * CorpDNS specifies whether to install the Tailscale network's
   * DNS configuration, if it exists.
   */
  CorpDNS: z.boolean().default(false),
  /**
   * RunSSH bool is whether this node should run an SSH
   * server, permitting access to peers according to the
   * policies as configured by the Tailnet's admin(s).
   */
  RunSSH: z.boolean().default(false),
  /**
   * RunWebClient bool is whether this node should expose
   * its web client over Tailscale at port 5252,
   * permitting access to peers according to the
   * policies as configured by the Tailnet's admin(s).
   */
  RunWebClient: z.boolean().default(false),
  /**
   * WantRunning indicates whether networking should be active on
   * this node.
   */
  WantRunning: z.boolean().default(false),
  /**
   * LoggedOut indicates whether the user intends to be logged out.
   * There are other reasons we may be logged out, including no valid
   * keys.
   * We need to remember this state so that, on next startup, we can
   * generate the "Login" vs "Connect" buttons correctly, without having
   * to contact the server to confirm our nodekey status first.
   */
  LoggedOut: z.boolean().default(false),
  /**
   * ShieldsUp indicates whether to block all incoming connections,
   * regardless of the control-provided packet filter. If false, we
   * use the packet filter as provided. If true, we block incoming
   * connections. This overrides tailcfg.Hostinfo's ShieldsUp.
   */
  ShieldsUp: z.boolean().default(false),
  /**
   * AdvertiseTags specifies tags that should be applied to this node, for
   * purposes of ACL enforcement. These can be referenced from the ACL policy
   * document. Note that advertising a tag on the client doesn't guarantee
   * that the control server will allow the node to adopt that tag.
   */
  AdvertiseTags: goSlice(z.string()),
  /**
   * Hostname is the hostname to use for identifying the node. If
   * not set, os.Hostname is used.
   */
  Hostname: z.string().default(""),
  /**
   * NotepadURLs is a debugging setting that opens OAuth URLs in
   * notepad.exe on Windows, rather than loading them in a browser.
   * 
   * apenwarr 2020-04-29: Unfortunately this is still needed sometimes.
   * Windows' default browser setting is sometimes screwy and this helps
   * users narrow it down a bit.
   */
  NotepadURLs: z.boolean().default(false),
  /**
   * ForceDaemon specifies whether a platform that normally
   * operates in "client mode" (that is, requires an active user
   * logged in with the GUI app running) should keep running after the
   * GUI ends and/or the user logs out.
   * 
   * The only current applicable platform is Windows. This
   * forced Windows to go into "server mode" where Tailscale is
   * running even with no users logged in. This might also be
   * used for macOS in the future. This setting has no effect
   * for Linux/etc, which always operate in daemon mode.
   */
  ForceDaemon: z.boolean().nullish(),
  /** Egg is a optional debug flag. */
  Egg: z.boolean().nullish(),
  /**
   * AdvertiseRoutes specifies CIDR prefixes to advertise into the
   * Tailscale network as reachable through the current
   * node.
   */
  AdvertiseRoutes: goSlice(z.string()),
  /**
   * AdvertiseServices specifies the list of services that this
   * node can serve as a destination for. Note that an advertised
   * service must still go through the approval process from the
   * control server.
   */
  AdvertiseServices: goSlice(z.string()),
  /**
   * Sync is whether this node should sync its configuration from
   * the control plane. If unset, this defaults to true.
   * This exists primarily for testing, to verify that netmap caching
   * and offline operation work correctly.
   */
  Sync: z.boolean().nullish(),
  /**
   * NoSNAT specifies whether to source NAT traffic going to
   * destinations in AdvertiseRoutes. The default is to apply source
   * NAT, which makes the traffic appear to come from the router
   * machine rather than the peer's Tailscale IP.
   * 
   * Disabling SNAT requires additional manual configuration in your
   * network to route Tailscale traffic back to the subnet relay
   * machine.
   * 
   * Linux-only.
   */
  NoSNAT: z.boolean().default(false),
  /**
   * NoStatefulFiltering specifies whether to apply stateful filtering when
   * advertising routes in AdvertiseRoutes. The default is to not apply
   * stateful filtering.
   * 
   * To allow inbound connections from advertised routes, both NoSNAT and
   * NoStatefulFiltering must be true.
   * 
   * This is an opt.Bool because it was first added after NoSNAT, with a
   * backfill based on the value of that parameter. The backfill has been
   * removed since then, but the field remains an opt.Bool.
   * 
   * Linux-only.
   */
  NoStatefulFiltering: z.boolean().nullish(),
  /**
   * NetfilterMode specifies how much to manage netfilter rules for
   * Tailscale, if at all.
   */
  NetfilterMode: int64.default(0),
  /**
   * OperatorUser is the local machine user name who is allowed to
   * operate tailscaled without being root or using sudo.
   */
  OperatorUser: z.string().nullish(),
  /**
   * ProfileName is the desired name of the profile. If empty, then the user's
   * LoginName is used. It is only used for display purposes in the client UI
   * and CLI.
   */
  ProfileName: z.string().nullish(),
  /**
   * AutoUpdate sets the auto-update preferences for the node agent. See
   * AutoUpdatePrefs docs for more details.
   */
  AutoUpdate: AutoUpdatePrefsSchema.default({}),
  /**
   * AppConnector sets the app connector preferences for the node agent. See
   * AppConnectorPrefs docs for more details.
   */
  AppConnector: AppConnectorPrefsSchema.default({}),
  /**
   * PostureChecking enables the collection of information used for device
   * posture checks.
   * 
   * Note: this should be named ReportPosture, but it was shipped as
   * PostureChecking in some early releases and this JSON field is written to
   * disk, so we just keep its old name. (akin to CorpDNS which is an internal
   * pref name that doesn't match the public interface)
   */
  PostureChecking: z.boolean().default(false),
  /**
   * NetfilterKind specifies what netfilter implementation to use.
   * 
   * It can be "iptables", "nftables", or "" to auto-detect.
   * 
   * Linux-only.
   */
  NetfilterKind: z.string().default(""),
  /**
   * DriveShares are the configured DriveShares, stored in increasing order
   * by name.
   */
  DriveShares: goSlice(z.unknown()),
  /**
   * RelayServerPort is the UDP port number for the relay server to bind to,
   * on all interfaces. A non-nil zero value signifies a random unused port
   * should be used. A nil value signifies relay server functionality
   * should be disabled.
   */
  RelayServerPort: z.number().nullish(),
  /**
   * RelayServerStaticEndpoints are static IP:port endpoints to advertise as
   * candidates for relay connections. Only relevant when RelayServerPort is
   * non-nil.
   */
  RelayServerStaticEndpoints: goSlice(z.string()),
  /**
   * AllowSingleHosts was a legacy field that was always true
   * for the past 4.5 years. It controlled whether Tailscale
   * peers got /32 or /128 routes for each other.
   * As of 2024-05-17 we're starting to ignore it, but to let
   * people still downgrade Tailscale versions and not break
   * all peer-to-peer networking we still write it to disk (as JSON)
   * so it can be loaded back by old versions.
   * TODO(bradfitz): delete this in 2025 sometime. See #12058.
   */
  AllowSingleHosts: z.unknown(),
  /**
   * The Persist field is named 'Config' in the file for backward
   * compatibility with earlier versions.
   * TODO(apenwarr): We should move this out of here, it's not a pref.
   *  We can maybe do that once we're sure which module should persist
   *  it (backend or frontend?)
   */
  Config: z.unknown().nullish(),
  ControlURLSet: z.boolean().nullish(),
  RouteAllSet: z.boolean().nullish(),
  ExitNodeIDSet: z.boolean().nullish(),
  ExitNodeIPSet: z.boolean().nullish(),
  AutoExitNodeSet: z.boolean().nullish(),
  /** Internal; can't be set by LocalAPI clients */
  InternalExitNodePriorSet: z.boolean().nullish(),
  ExitNodeAllowLANAccessSet: z.boolean().nullish(),
  CorpDNSSet: z.boolean().nullish(),
  RunSSHSet: z.boolean().nullish(),
  RunWebClientSet: z.boolean().nullish(),
  WantRunningSet: z.boolean().nullish(),
  LoggedOutSet: z.boolean().nullish(),
  ShieldsUpSet: z.boolean().nullish(),
  AdvertiseTagsSet: z.boolean().nullish(),
  HostnameSet: z.boolean().nullish(),
  NotepadURLsSet: z.boolean().nullish(),
  ForceDaemonSet: z.boolean().nullish(),
  EggSet: z.boolean().nullish(),
  AdvertiseRoutesSet: z.boolean().nullish(),
  AdvertiseServicesSet: z.boolean().nullish(),
  SyncSet: z.boolean().nullish(),
  NoSNATSet: z.boolean().nullish(),
  NoStatefulFilteringSet: z.boolean().nullish(),
  NetfilterModeSet: z.boolean().nullish(),
  OperatorUserSet: z.boolean().nullish(),
  ProfileNameSet: z.boolean().nullish(),
  AutoUpdateSet: AutoUpdatePrefsMaskSchema.nullish(),
  AppConnectorSet: z.boolean().nullish(),
  PostureCheckingSet: z.boolean().nullish(),
  NetfilterKindSet: z.boolean().nullish(),
  DriveSharesSet: z.boolean().nullish(),
  RelayServerPortSet: z.boolean().nullish(),
  RelayServerStaticEndpointsSet: z.boolean().nullish(),
});
export type MaskedPrefs = z.infer<typeof MaskedPrefsSchema>;

/** EngineStatus contains WireGuard engine stats. */
export const EngineStatusSchema = z.object({
  RBytes: int64.default(0),
  WBytes: int64.default(0),
  NumLive: int64.default(0),
  /** number of active DERP connections */
  LiveDERPs: int64.default(0),
  LivePeers: goMap(PeerStatusLiteSchema),
});
export type EngineStatus = z.infer<typeof EngineStatusSchema>;

/** PartialFile represents an in-progress incoming file transfer. */
export const PartialFileSchema = z.object({
  /** e.g. "foo.jpg" */
  Name: z.string().default(""),
  /** time transfer started */
  Started: z.string().default(""),
  /** or -1 if unknown */
  DeclaredSize: int64.default(0),
  /** bytes copied thus far */
  Received: int64.default(0),
  /**
   * PartialPath is set non-empty in "direct" file mode to the
   * in-progress '*.partial' file's path when the peerapi isn't
   * being used; see LocalBackend.SetDirectFileRoot.
   */
  PartialPath: z.string().nullish(),
  FinalPath: z.string().nullish(),
  /**
   * Done is set in "direct" mode when the partial file has been
   * closed and is ready for the caller to rename away the
   * ".partial" suffix.
   */
  Done: z.boolean().nullish(),
});
export type PartialFile = z.infer<typeof PartialFileSchema>;

/** OutgoingFile represents an in-progress outgoing file transfer. */
export const OutgoingFileSchema = z.object({
  /** unique identifier for this transfer (a type 4 UUID) */
  ID: z.string().nullish(),
  /** identifier for the peer to which this is being transferred */
  PeerID: z.string().nullish(),
  /** e.g. "foo.jpg" */
  Name: z.string().nullish(),
  /** time transfer started */
  Started: z.string().default(""),
  /** or -1 if unknown */
  DeclaredSize: int64.default(0),
  /** bytes copied thus far */
  Sent: int64.default(0),
  /** indicates whether or not the transfer finished */
  Finished: z.boolean().default(false),
  /** for a finished transfer, indicates whether or not it was successful */
  Succeeded: z.boolean().default(false),
});
export type OutgoingFile = z.infer<typeof OutgoingFileSchema>;

/**
 * Notify is a communication from a backend (e.g. tailscaled) to a frontend
 * (cmd/tailscale, iOS, macOS, Win Tasktray).
 * In any given notification, any or all of these may be nil, meaning
 * that they have not changed.
 * They are JSON-encoded on the wire, despite the lack of struct tags.
 */
export const NotifySchema = z.object({
  /** version number of IPN backend */
  Version: z.string().default(""),
  /**
   * SessionID identifies the unique WatchIPNBus session.
   * This field is only set in the first message when requesting
   * NotifyInitialState. Clients must store it on their side as
   * following notifications will not include this field.
   */
  SessionID: z.string().nullish(),
  /**
   * ErrMessage, if non-nil, contains a critical error message.
   * For State InUseOtherUser, ErrMessage is not critical and just contains the details.
   */
  ErrMessage: z.string().nullish(),
  /** non-nil when/if the login process succeeded */
  LoginFinished: z.unknown().nullish(),
  /** if non-nil, the new or current IPN state */
  State: int64.nullish(),
  /** if non-nil && Valid, the new or current preferences */
  Prefs: PrefsSchema.nullish(),
  /** if non-nil, the new or current netmap */
  NetMap: z.unknown().nullish(),
  /** if non-nil, the new or current wireguard stats */
  Engine: EngineStatusSchema.nullish(),
  /** if non-nil, UI should open a browser right now */
  BrowseToURL: z.string().nullish(),
  /**
   * FilesWaiting if non-nil means that files are buffered in
   * the Tailscale daemon and ready for local transfer to the
   * user's preferred storage location.
   * 
   * Deprecated: use LocalClient.AwaitWaitingFiles instead.
   */
  FilesWaiting: z.unknown().nullish(),
  /**
   * IncomingFiles, if non-nil, specifies which files are in the
   * process of being received. A nil IncomingFiles means this
   * Notify should not update the state of file transfers. A non-nil
   * but empty IncomingFiles means that no files are in the middle
   * of being transferred.
   * 
   * Deprecated: use LocalClient.AwaitWaitingFiles instead.
   */
  IncomingFiles: goSlice(PartialFileSchema),
  /**
   * OutgoingFiles, if non-nil, tracks which files are in the process of
   * being sent via TailDrop, including files that finished, whether
   * successful or failed. This slice is sorted by Started time, then Name.
   */
  OutgoingFiles: goSlice(OutgoingFileSchema),
  /**
   * LocalTCPPort, if non-nil, informs the UI frontend which
   * (non-zero) localhost TCP port it's listening on.
   * This is currently only used by Tailscale when run in the
   * macOS Network Extension.
   */
  LocalTCPPort: z.number().nullish(),
  /**
   * ClientVersion, if non-nil, describes whether a client version update
   * is available.
   */
  ClientVersion: ClientVersionSchema.nullish(),
  /**
   * DriveShares tracks the full set of current DriveShares that we're
   * publishing. Some client applications, like the MacOS and Windows clients,
   * will listen for updates to this and handle serving these shares under
   * the identity of the unprivileged user that is running the application. A
   * nil value here means that we're not broadcasting shares information, an
   * empty value means that there are no shares.
   */
  DriveShares: goSlice(z.unknown()),
  /**
   * Health is the last-known health state of the backend. When this field is
   * non-nil, a change in health verified, and the API client should surface
   * any changes to the user in the UI.
   */
  Health: z.unknown().nullish(),
  /**
   * SuggestedExitNode, if non-nil, is the node that the backend has determined to
   * be the best exit node for the current network conditions.
   */
  SuggestedExitNode: z.string().nullish(),
});
export type Notify = z.infer<typeof NotifySchema>;

/**
 * TCPPortHandler describes what to do when handling a TCP
 * connection.
 */
export const TCPPortHandlerSchema = z.object({
  /**
   * HTTPS, if true, means that tailscaled should handle this connection as an
   * HTTPS request as configured by ServeConfig.Web.
   * 
   * It is mutually exclusive with TCPForward.
   */
  HTTPS: z.boolean().nullish(),
  /**
   * HTTP, if true, means that tailscaled should handle this connection as an
   * HTTP request as configured by ServeConfig.Web.
   * 
   * It is mutually exclusive with TCPForward.
   */
  HTTP: z.boolean().nullish(),
  /**
   * TCPForward is the IP:port to forward TCP connections to.
   * Whether or not TLS is terminated by tailscaled depends on
   * TerminateTLS.
   * 
   * It is mutually exclusive with HTTPS.
   */
  TCPForward: z.string().nullish(),
  /**
   * TerminateTLS, if non-empty, means that tailscaled should terminate the
   * TLS connections before forwarding them to TCPForward, permitting only the
   * SNI name with this value. It is only used if TCPForward is non-empty.
   * (the HTTPS mode uses ServeConfig.Web)
   */
  TerminateTLS: z.string().nullish(),
  /**
   * ProxyProtocol indicates whether to send a PROXY protocol header
   * before forwarding the connection to TCPForward.
   * 
   * This is only valid if TCPForward is non-empty.
   */
  ProxyProtocol: int64.nullish(),
});
export type TCPPortHandler = z.infer<typeof TCPPortHandlerSchema>;

/** HTTPHandler is either a path or a proxy to serve. */
export const HTTPHandlerSchema = z.object({
  /** absolute path to directory or file to serve */
  Path: z.string().nullish(),
  /** http://localhost:3000/, localhost:3030, 3030 */
  Proxy: z.string().nullish(),
  /** plaintext to serve (primarily for testing) */
  Text: z.string().nullish(),
  /** peer capabilities to forward in grant header, e.g. example.com/cap/mon */
  AcceptAppCaps: goSlice(z.string()),
  /**
   * Redirect, if not empty, is the target URL to redirect requests to.
   * By default, we redirect with HTTP 302 (Found) status.
   * If Redirect starts with '<httpcode>:', then we use that status instead.
   * 
   * The target URL supports the following expansion variables:
   *   - ${HOST}: replaced with the request's Host header value
   *   - ${REQUEST_URI}: replaced with the request's full URI (path and query string)
   */
  Redirect: z.string().nullish(),
});
export type HTTPHandler = z.infer<typeof HTTPHandlerSchema>;

/** WebServerConfig describes a web server's configuration. */
export const WebServerConfigSchema = z.object({
  /** mountPoint => handler */
  Handlers: goMap(HTTPHandlerSchema),
});
export type WebServerConfig = z.infer<typeof WebServerConfigSchema>;

/**
 * ServiceConfig contains the config information for a single service.
 * it contains a bool to indicate if the service is in Tun mode (L3 forwarding).
 * If the service is not in Tun mode, the service is configured by the L4 forwarding
 * (TCP ports) and/or the L7 forwarding (http handlers) information.
 */
export const ServiceConfigSchema = z.object({
  /**
   * TCP are the list of TCP port numbers that tailscaled should handle for
   * the Tailscale IP addresses. (not subnet routers, etc)
   */
  TCP: goMap(TCPPortHandlerSchema),
  /**
   * Web maps from "$SNI_NAME:$PORT" to a set of HTTP handlers
   * keyed by mount point ("/", "/foo", etc)
   */
  Web: goMap(WebServerConfigSchema),
  /** Tun determines if the service should be using L3 forwarding (Tun mode). */
  Tun: z.boolean().nullish(),
});
export type ServiceConfig = z.infer<typeof ServiceConfigSchema>;

const _ServeConfigRef: z.ZodTypeAny = z.lazy(() => ServeConfigSchema);
/**
 * ServeConfig is the JSON type stored in the StateStore for
 * StateKey "_serve/$PROFILE_ID" as returned by ServeConfigKey.
 */
export const ServeConfigSchema = z.object({
  /**
   * TCP are the list of TCP port numbers that tailscaled should handle for
   * the Tailscale IP addresses. (not subnet routers, etc)
   */
  TCP: goMap(TCPPortHandlerSchema),
  /**
   * Web maps from "$SNI_NAME:$PORT" to a set of HTTP handlers
   * keyed by mount point ("/", "/foo", etc)
   */
  Web: goMap(WebServerConfigSchema),
  /**
   * Services maps from service name (in the form "svc:dns-label") to a ServiceConfig.
   * Which describes the L3, L4, and L7 forwarding information for the service.
   */
  Services: goMap(ServiceConfigSchema),
  /**
   * AllowFunnel is the set of SNI:port values for which funnel
   * traffic is allowed, from trusted ingress peers.
   */
  AllowFunnel: goMap(z.boolean()),
  /**
   * Foreground is a map of an IPN Bus session ID to an alternate foreground serve config that's valid for the
   * life of that WatchIPNBus session ID. This allows the config to specify ephemeral configs that are used
   * in the CLI's foreground mode to ensure ungraceful shutdowns of either the client or the LocalBackend does not
   * expose ports that users are not aware of. In practice this contains any serve config set via 'tailscale
   * serve' command run without the '--bg' flag. ServeConfig contained by Foreground is not expected itself to contain
   * another Foreground block.
   */
  Foreground: goMap(_ServeConfigRef),
});
export type ServeConfig = z.infer<typeof ServeConfigSchema>;

/**
 * NetworkProfile is a subset of netmap.NetworkMap
 * that should be saved with each user profile.
 */
export const NetworkProfileSchema = z.object({
  MagicDNSName: z.string().default(""),
  DomainName: z.string().default(""),
  DisplayName: z.string().default(""),
});
export type NetworkProfile = z.infer<typeof NetworkProfileSchema>;

/**
 * LoginProfile represents a single login profile as managed
 * by the ProfileManager.
 */
export const LoginProfileSchema = z.object({
  /**
   * ID is a unique identifier for this profile.
   * It is assigned on creation and never changes.
   * It may seem redundant to have both ID and UserProfile.ID
   * but they are different things. UserProfile.ID may change
   * over time (e.g. if a device is tagged).
   */
  ID: z.string().default(""),
  /**
   * Name is the user-visible name of this profile.
   * It is filled in from the UserProfile.LoginName field.
   */
  Name: z.string().default(""),
  /**
   * NetworkProfile is a subset of netmap.NetworkMap that we
   * store to remember information about the tailnet that this
   * profile was logged in with.
   * 
   * This field was added on 2023-11-17.
   */
  NetworkProfile: NetworkProfileSchema.default({}),
  /**
   * Key is the StateKey under which the profile is stored.
   * It is assigned once at profile creation time and never changes.
   */
  Key: z.string().default(""),
  /**
   * UserProfile is the server provided UserProfile for this profile.
   * This is updated whenever the server provides a new UserProfile.
   */
  UserProfile: UserProfileSchema.default({}),
  /**
   * NodeID is the NodeID of the node that this profile is logged into.
   * This should be stable across tagging and untagging nodes.
   * It may seem redundant to check against both the UserProfile.UserID
   * and the NodeID. However the NodeID can change if the node is deleted
   * from the admin panel.
   */
  NodeID: z.string().default(""),
  /**
   * LocalUserID is the user ID of the user who created this profile.
   * It is only relevant on Windows where we have a multi-user system.
   * It is assigned once at profile creation time and never changes.
   */
  LocalUserID: z.string().default(""),
  /**
   * ControlURL is the URL of the control server that this profile is logged
   * into.
   */
  ControlURL: z.string().default(""),
});
export type LoginProfile = z.infer<typeof LoginProfileSchema>;

/**
 * WhoIsResponse is the JSON type returned by tailscaled debug server's /whois?ip=$IP handler.
 * In successful whois responses, Node and UserProfile are never nil.
 */
export const WhoIsResponseSchema = z.object({
  Node: NodeSchema.nullish(),
  UserProfile: UserProfileSchema.nullish(),
  /**
   * CapMap is a map of capabilities to their values.
   * See tailcfg.PeerCapMap and tailcfg.PeerCapability for details.
   */
  CapMap: goMap(goSlice(z.unknown())),
});
export type WhoIsResponse = z.infer<typeof WhoIsResponseSchema>;

export const WaitingFileSchema = z.object({
  Name: z.string().default(""),
  Size: int64.default(0),
});
export type WaitingFile = z.infer<typeof WaitingFileSchema>;

/**
 * FileTarget is a node to which files can be sent, and the PeerAPI
 * URL base to do so via.
 */
export const FileTargetSchema = z.object({
  Node: NodeSchema.nullish(),
  /**
   * PeerAPI is the http://ip:port URL base of the node's PeerAPI,
   * without any path (not even a single slash).
   */
  PeerAPIURL: z.string().default(""),
});
export type FileTarget = z.infer<typeof FileTargetSchema>;

/**
 * ExitNodeSuggestionResponse is the response to a LocalAPI suggest-exit-node GET request.
 * It returns the StableNodeID, name, and location of a suggested exit node for the client making the request.
 */
export const ExitNodeSuggestionResponseSchema = z.object({
  ID: z.string().default(""),
  Name: z.string().default(""),
  Location: LocationSchema.nullish(),
});
export type ExitNodeSuggestionResponse = z.infer<typeof ExitNodeSuggestionResponseSchema>;

/**
 * ReloadConfigResponse is the response to a LocalAPI reload-config request.
 * 
 * There are three possible outcomes: (false, "") if no config mode in use,
 * (true, "") on success, or (false, "error message") on failure.
 */
export const ReloadConfigResponseSchema = z.object({
  /** whether the config was reloaded */
  Reloaded: z.boolean().default(false),
  /** any error message */
  Err: z.string().default(""),
});
export type ReloadConfigResponse = z.infer<typeof ReloadConfigResponseSchema>;

/**
 * DNSOSConfig mimics dns.OSConfig without forcing us to import the entire dns package
 * into the CLI.
 */
export const DNSOSConfigSchema = z.object({
  Nameservers: goSlice(z.string()),
  SearchDomains: goSlice(z.string()),
  MatchDomains: goSlice(z.string()),
});
export type DNSOSConfig = z.infer<typeof DNSOSConfigSchema>;

/** DNSQueryResponse is the response to a DNS query request sent via LocalAPI. */
export const DNSQueryResponseSchema = z.object({
  /** Bytes is the raw DNS response bytes. */
  Bytes: z.string().default(""),
  /** Resolvers is the list of resolvers that the forwarder deemed able to resolve the query. */
  Resolvers: goSlice(ResolverSchema),
});
export type DNSQueryResponse = z.infer<typeof DNSQueryResponseSchema>;

/** OptionalFeatures describes which optional features are enabled in the build. */
export const OptionalFeaturesSchema = z.object({
  /**
   * Features is the map of optional feature names to whether they are
   * enabled.
   * 
   * Disabled features may be absent from the map. (That is, false values
   * are not guaranteed to be present.)
   */
  Features: goMap(z.boolean()),
});
export type OptionalFeatures = z.infer<typeof OptionalFeaturesSchema>;

/** SetPushDeviceTokenRequest is the body POSTed to the LocalAPI endpoint /set-device-token. */
export const SetPushDeviceTokenRequestSchema = z.object({
  /** PushDeviceToken is the iOS/macOS APNs device token (and any future Android equivalent). */
  PushDeviceToken: z.string().default(""),
});
export type SetPushDeviceTokenRequest = z.infer<typeof SetPushDeviceTokenRequestSchema>;

/** Alias for TailnetStatus for backward compatibility. */
export const CurrentTailnetSchema = z.object({
  Name: z.string(),
  MagicDNSSuffix: z.string(),
  MagicDNSEnabled: z.boolean(),
});
export type CurrentTailnet = z.infer<typeof CurrentTailnetSchema>;

/** Profile status containing current and all profiles. */
export const ProfileStatusSchema = z.object({
  CurrentProfile: LoginProfileSchema,
  AllProfiles: z.array(LoginProfileSchema),
});
export type ProfileStatus = z.infer<typeof ProfileStatusSchema>;

/** Bitmask for IPN bus watch notifications. */
export enum NotifyWatchOpt {
  /** Receive initial state at start of watch. */
  NotifyInitialState = 1 << 1,
  /** Receive full network map updates. */
  NotifyInitialNetMap = 1 << 2,
  /** Receive partial state updates. */
  NotifyInitialDriveShares = 1 << 3,
  /** Receive full prefs in initial state. */
  NotifyInitialPrefs = 1 << 4,
  /** Receive outgoing file updates. */
  NotifyInitialOutgoingFiles = 1 << 5,
}
